package hoakhaven

import "guacagamblebot/internal/universe"

var Fragments = []universe.Fragment{
	// ======== AETHER-LOGS (8) — Mining ========
	{ID: "log_signal", Category: "aether_log", Emoji: "\U0001f4e1", Rarity: "rare", DropSource: "mining", DropChance: 0.08,
		TitleEN: "The Signal", TitleFR: "Le Signal",
		TextEN: `Engineer-Major Voss's final broadcast echoes through the crystal: '...if anyone can hear this, the purification chambers have failed. Aether saturation in the lower Strata is at 97%. We're sealing the blast doors. Don't try to open them. The things in the dark aren't us anymore. May the Nexus forgive us.'`,
		TextFR: `Dernière diffusion de l'Ingénieur-Major Voss : '...si quelqu'un entend ça, les chambres de purification ont cédé. La saturation d'Éther dans les Strates inférieures est à 97%. Nous scellons les portes. N'essayez pas de les ouvrir. Les choses dans le noir ne sont plus nous. Que le Nexus nous pardonne.'`,
	},
	{ID: "log_gardener", Category: "aether_log", Emoji: "\U0001f331", Rarity: "common", DropSource: "mining", DropChance: 0.12,
		TitleEN: "The Gardener", TitleFR: "Le Jardinier",
		TextEN: `Merrik's notes: 'The Aether-Root protocol is working. We've bonded a copper-oak sapling to the main turbine. It draws Aether from the leak and converts it to stable biomass. Call it a green backup. Kael would hate that pun.'`,
		TextFR: `Notes de Merrik : 'Le protocole Racine-d'Éther fonctionne. Nous avons greffé un jeune chêne-de-cuivre à la turbine principale. Il aspire l'Éther et le convertit en biomasse stable. Une sauvegarde verte. Kael détesterait ce jeu de mots.'`,
	},
	{ID: "log_transmission", Category: "aether_log", Emoji: "\U0001f4fb", Rarity: "epic", DropSource: "mining", DropChance: 0.04,
		TitleEN: "The Last Transmission", TitleFR: "La Dernière Transmission",
		TextEN: `'...frequency 7-4-0... anyone receiving? The southern arcology collapsed at 03:00. Forty thousand inside. We heard the Nexuses singing before it fell — all of them, across the continent, at once. Like a choir of dying stars. I don't think the Shedding was an accident. I think it was... a harvest.'`,
		TextFR: `'...fréquence 7-4-0... quelqu'un reçoit ? L'arcologie sud s'est effondrée à 03h00. Quarante mille à l'intérieur. Nous avons entendu les Nexuses chanter avant la chute — tous, à travers le continent, en même temps. Comme un chœur d'étoiles mourantes. La Mue n'était pas un accident. C'était... une récolte.'`,
	},
	{ID: "log_purge", Category: "aether_log", Emoji: "\U0001f512", Rarity: "common", DropSource: "mining", DropChance: 0.10,
		TitleEN: "Purge Protocol", TitleFR: "Protocole de Purge",
		TextEN: `'Directive 88: Evacuation of the lower Strata is cancelled. Seal the blast doors. All personnel are to report to Nexus-level immediately. Aether-tainted individuals will not be permitted above Sector 4. This is not a debate. This is protocol.'`,
		TextFR: `'Directive 88 : L'évacuation des Strates inférieures est annulée. Scellez les portes. Tout le personnel doit se présenter immédiatement au niveau du Nexus. Les individus contaminés par l'Éther ne seront pas admis au-dessus du Secteur 4. Ce n'est pas un débat. C'est le protocole.'`,
	},
	{ID: "log_surveyor", Category: "aether_log", Emoji: "\U0001f50d", Rarity: "rare", DropSource: "mining", DropChance: 0.07,
		TitleEN: "The Surveyor", TitleFR: "L'Arpenteur",
		TextEN: `Surveyor Tesh's final log: 'Aether readings are off the scale. The ground itself is humming. I've been taking samples for thirty years and I've never seen anything like this. The minerals are... growing. Not crystallizing — growing. There's something alive in the deep Strata. Something that was here before the Zenith.'`,
		TextFR: `Dernier rapport de l'Arpenteuse Tesh : 'Les relevés d'Éther sont hors d'échelle. Le sol lui-même bourdonne. Les minéraux... poussent. Pas des cristaux — ils croissent. Il y a quelque chose de vivant dans les Strates profondes. Quelque chose qui était là avant le Zenith.'`,
	},
	{ID: "log_children", Category: "aether_log", Emoji: "\U0001f49b", Rarity: "epic", DropSource: "mining", DropChance: 0.03,
		TitleEN: "Children of the Grid", TitleFR: "Enfants du Réseau",
		TextEN: `'To whoever finds this crystal — my name is Lira Voss. I'm seven years old. My mother said the Grid would protect us. She said the Aether was our friend. But the Aether is eating the walls. I'm in the bunker with thirty other children. The grown-ups went to fix the Nexus five days ago and they haven't come back. If you find this, please... tell them we're still waiting.'`,
		TextFR: `'À qui trouvera ce cristal — je m'appelle Lira Voss. J'ai sept ans. Maman disait que le Réseau nous protégerait. Mais l'Éther dévore les murs. Les adultes sont allés réparer le Nexus il y a cinq jours et ne sont pas revenus. S'il vous plaît... dites-leur qu'on attend encore.'`,
	},
	{ID: "log_silence", Category: "aether_log", Emoji: "\U0001f92b", Rarity: "legendary", DropSource: "mining", DropChance: 0.01,
		TitleEN: "The Silence", TitleFR: "Le Silence",
		TextEN: `There is no message in this crystal. Only the recording of a moment — the exact instant every Nexus on the continent went silent simultaneously. It lasts eleven seconds. The first four are filled with the low hum of civilization. The next two contain a rising tone, pitched just below human hearing. The final five seconds are absolute, uncompromising silence. The crystal is warm to the touch.`,
		TextFR: `Ce cristal ne contient aucun message. Seulement l'enregistrement d'un instant — le moment précis où tous les Nexuses du continent se sont tus simultanément. Il dure onze secondes. Les quatre premières contiennent le bourdonnement de la civilisation. Les deux suivantes, une tonalité ascendante. Les cinq dernières secondes sont un silence absolu et implacable. Le cristal est chaud au toucher.`,
	},
	{ID: "log_threshold", Category: "aether_log", Emoji: "\u2744\ufe0f", Rarity: "rare", DropSource: "mining", DropChance: 0.06,
		TitleEN: "The Threshold", TitleFR: "Le Seuil",
		TextEN: `'Climate model 7-R confirms: the Great Winter is not a natural season. It is a byproduct of Aether decay. Every year the warm period shortens. Every year the frost reaches deeper into the Strata. If we cannot stop the leakage, the Strata will be uninhabitable within twelve generations. This is not fear. This is mathematics.'`,
		TextFR: `'Le modèle climatique 7-R confirme : le Grand Hiver n'est pas une saison naturelle. C'est un sous-produit de la dégradation de l'Éther. Chaque année, la période chaude raccourcit. Si nous ne pouvons arrêter la fuite, les Strates seront inhabitables dans douze générations.'`,
	},

	// ======== TIDE-SCROLLS (8) — Fishing ========
	{ID: "scroll_prayer", Category: "tide_scroll", Emoji: "\U0001f64f", Rarity: "common", DropSource: "fishing", DropChance: 0.12,
		TitleEN: "The Dockworker's Prayer", TitleFR: "La Prière du Débardeur",
		TextEN: `'O Zenith, who forged the gears of the world, let my hands be steady and my nets be full. I don't ask for miracles. Just let the Rust-Eaters stay in the deep water where they belong, and keep my children's lungs clear of the green. Amen.' — Inscription on a corroded pier pillar at the old Oakhaven docks.`,
		TextFR: `'Ô Zenith, toi qui forgeas les engrenages du monde, rends mes mains stables et mes filets pleins. Laisse juste les Mangeurs-de-Rouille dans les eaux profondes, et garde les poumons de mes enfants libres du vert.' — Inscription sur un pilier de jetée aux vieux quais d'Oakhaven.`,
	},
	{ID: "scroll_migration", Category: "tide_scroll", Emoji: "\U0001f5fa\ufe0f", Rarity: "common", DropSource: "fishing", DropChance: 0.10,
		TitleEN: "Migration Patterns", TitleFR: "Routes de Migration",
		TextEN: `'The Silver-Spine Shoal has shifted route again. Three years ago they passed through the Riven Strait — now they're circling the Northern Shelf. Something in the deep water is pushing them. I've charted their new path: if you follow the Silver-Spine, you find pockets of pure Aether. The fish know what the machines forgot.' — Irian's first chart, pre-Council.`,
		TextFR: `'Le banc d'Argentins a encore changé de route. Quelque chose dans les eaux profondes les pousse. J'ai cartographié leur nouveau chemin : si tu suis les Argentins, tu trouves des poches d'Éther pur. Les poissons savent ce que les machines ont oublié.' — Première carte d'Irian.`,
	},
	{ID: "scroll_captain", Category: "tide_scroll", Emoji: "\u2693", Rarity: "rare", DropSource: "fishing", DropChance: 0.07,
		TitleEN: "The Captain's Log", TitleFR: "Le Journal du Capitaine",
		TextEN: `'Log 12 of the Aether-Swift. Day 47 at sea. The crew is restless. We've been following the Aether blooms north for six weeks. Last night, we saw lights beneath the water — not bioluminescence, not reflections. Patterned lights. Deliberate. The navigator says we should turn back. But the cargo hold is full of rust-cured salvage... I've given the order to continue.'`,
		TextFR: `'Journal 12 de l'Éther-Rapide. Jour 47 en mer. Nous suivons les floraisons d'Éther vers le nord. La nuit dernière, des lumières sous l'eau — ni bioluminescence, ni reflets. Des lumières structurées. Le navigateur dit qu'il faut rebrousser chemin. Mais la cale est pleine... J'ai donné l'ordre de continuer.'`,
	},
	{ID: "scroll_letter", Category: "tide_scroll", Emoji: "\U0001f48c", Rarity: "rare", DropSource: "fishing", DropChance: 0.06,
		TitleEN: "Letter to Shore", TitleFR: "Lettre au Rivage",
		TextEN: `'My dearest Elara — The sea is cruel and beautiful and I have seen things I cannot describe. A forest of kelp that glows at night. A creature the size of an island that slept beneath our hull for three days. But more than anything, I miss the way you hum when you tend your garden. I'll be home by spring. — Irian.'`,
		TextFR: `'Ma très chère Elara — La mer est cruelle et belle. J'ai gardé une graine d'un fruit trouvé dans une caisse Zenith. Elle pulse d'une douce lumière verte. Je crois que c'est quelque chose de nouveau. Tu la planteras pour moi ? Je serai à la maison au printemps. — Irian.'`,
	},
	{ID: "scroll_tidechildren", Category: "tide_scroll", Emoji: "\U0001f9dc", Rarity: "common", DropSource: "fishing", DropChance: 0.10,
		TitleEN: "The Tide-Children", TitleFR: "Les Enfants de la Marée",
		TextEN: `'Old Merrik used to tell us: when the tide goes out further than it should, and the exposed rocks steam with green mist — that's when the Tide-Children come. They're not fish. They're not people. They're what happens when a human survives drowning in an Aether-saturated sea. They don't breathe. They don't age. They just... wait.' — Folk tale from the Oakhaven-Station archive.`,
		TextFR: `'Le vieux Merrik disait : quand la mer se retire plus loin que d'habitude, et que les rochers fument d'une brume verte — les Enfants de la Marée arrivent. Ce sont des gens qui ont survécu à la noyade dans une mer d'Éther. Ils ne respirent pas. Ils ne vieillissent pas. Ils attendent.'`,
	},
	{ID: "scroll_manifest", Category: "tide_scroll", Emoji: "\U0001f4e6", Rarity: "common", DropSource: "fishing", DropChance: 0.10,
		TitleEN: "Cargo Manifest", TitleFR: "Manifeste de Cargaison",
		TextEN: `'HAUL 88-40Z — Recovered from submerged Zenith depot, Sector 9. Contents: 12 crates preserved circuit-bread, 8 cases emergency rations, 1 trunk personal effects, 3 partially charged Aether-cells, 1 sealed crate marked "ZEAL — DO NOT OPEN — SITE 7". Left on the seabed. Let sleeping dogs lie.'`,
		TextFR: `'LOT 88-40Z — Récupéré d'un dépôt Zenith submergé. 12 caisses de pain en circuit, 8 caisses de rations, 1 malle d'effets personnels, 3 cellules d'Éther, 1 caisse marquée "ZÈLE — NE PAS OUVRIR". Laissée au fond.'`,
	},
	{ID: "scroll_lighthouse", Category: "tide_scroll", Emoji: "\U0001f4a1", Rarity: "epic", DropSource: "fishing", DropChance: 0.03,
		TitleEN: "The Lighthouse Keeper", TitleFR: "Le Gardien du Phare",
		TextEN: `'Year 47. I am the last keeper of the Northern Light. The tower still functions — its Aether lens cuts through the fog. But there are no more ships to guide. The sea has risen twelve meters since the Shedding. The lower two floors are underwater. The Tide-Children visit sometimes. They tap on the glass. I tap back. It's a kind of conversation.' — Keeper Sol, 347th day of the Long Night.`,
		TextFR: `'Année 47. Je suis le dernier gardien de la Lumière du Nord. La mer a monté de douze mètres depuis la Mue. Les Enfants de la Marée tapent sur la vitre. Je réponds. C'est une sorte de conversation.' — Gardien Sol, 347e jour.`,
	},
	{ID: "scroll_deep", Category: "tide_scroll", Emoji: "\U0001f30a", Rarity: "legendary", DropSource: "fishing", DropChance: 0.01,
		TitleEN: "The Deep Places", TitleFR: "Les Abysses",
		TextEN: `'I descended for three days. The pressure at the bottom should have killed me — but the Aether cells in my suit converted the ambient energy into breathable air. The deep places are not empty. There are structures down there. Towers of fused coral and Zenith steel. And in the central plaza, a machine the size of a mountain, pulsing with a slow, patient rhythm. Not a machine. A heart.' — The Descent of Aris Thorne, page 247.`,
		TextFR: `'Je suis descendu trois jours. Les abysses ne sont pas vides. Des tours de corail et d'acier Zenith. Des lumières qui brûlent encore. Et sur la place centrale, une machine grande comme une montagne, pulsant d'un rythme patient. Pas une machine. Un cœur.' — La Descente d'Aris Thorne.`,
	},

	// ======== ROOT-WHISPERS (8) — Farming ========
	{ID: "root_gears", Category: "root_whisper", Emoji: "\u2699\ufe0f", Rarity: "common", DropSource: "farming", DropChance: 0.08,
		TitleEN: "The Dream of Gears", TitleFR: "Le Rêve des Engrenages",
		TextEN: `The tree does not understand time as you do. It remembers the engineers who first planted its seed — not as people, but as a sensation of warmth. A brief, bright flicker. They are gone now, but their heat remains in the roots. The tree calls this 'grief.' It is the only emotion it shares with you.`,
		TextFR: `L'arbre ne comprend pas le temps. Il se souvient des ingénieurs comme une sensation de chaleur. Une brève lueur. Ils sont partis, mais leur chaleur demeure dans les racines. L'arbre appelle cela 'le chagrin.' Chaque fois que vous vous reposez sous ses branches, il demande : 'As-tu chaud, petit ?'`,
	},
	{ID: "root_shedding", Category: "root_whisper", Emoji: "\U0001f342", Rarity: "rare", DropSource: "farming", DropChance: 0.06,
		TitleEN: "The Shedding from Below", TitleFR: "La Mue vue d'en bas",
		TextEN: `The Nexus remembers the moment the old world fell — not as catastrophe, but as release. A season it had waited ten thousand years to feel. What you call 'the Shedding,' the tree calls 'spring.' It does not understand why you mourn. The old world fell. This world grows from its corpse. This is not tragedy. This is the cycle.`,
		TextFR: `Le Nexus se souvient de la chute de l'ancien monde comme d'une libération. Une saison attendue depuis dix mille ans. Ce que vous appelez 'la Mue,' l'arbre l'appelle 'printemps.' L'ancien monde est tombé. Ce monde pousse de son cadavre. C'est le cycle.`,
	},
	{ID: "root_graft", Category: "root_whisper", Emoji: "\U0001f33f", Rarity: "common", DropSource: "farming", DropChance: 0.08,
		TitleEN: "The Grafting", TitleFR: "La Greffe",
		TextEN: `'Procedure 7-Alpha. Subject: Copper-Oak sapling grafted to Zenith ZN-440 turbine. The roots have accepted the Aether flow without rejection. The turbine's hum has dropped from 88 dB to 42 dB. The sapling appears to be... singing. We are calling this phenomenon "Harmonic Equilibrium." — Merrik, Day 1 of the Grafting Trials.'`,
		TextFR: `'Procédure 7-Alpha. Jeune chêne-de-cuivre greffé sur turbine ZN-440. Les racines acceptent le flux d'Éther. Le bourdonnement de la turbine est passé de 88 dB à 42 dB. Le jeune arbre semble... chanter. Nous appelons cela l'Équilibre Harmonique.' — Merrik.`,
	},
	{ID: "root_grid", Category: "root_whisper", Emoji: "\U0001f50b", Rarity: "rare", DropSource: "farming", DropChance: 0.05,
		TitleEN: "The Green Grid", TitleFR: "Le Réseau Vert",
		TextEN: `'Phase 3 report: The Green Grid is operational. We have connected seventeen Engine-Trees across the continent into a single living network. They communicate through their root systems at speeds that rival our data cables. They share power loads automatically. They are smarter than our grid ever was. And they will outlast everything.' — Zenith Botanical Engineering Division.`,
		TextFR: `'Phase 3 : Le Réseau Vert est opérationnel. Dix-sept Arbres-Moteurs connectés en un seul réseau vivant. Ils communiquent via leurs racines, partagent les charges. Ils sont plus intelligents que notre réseau. Et ils nous survivront.' — Rapport Final, Division Botanique.`,
	},
	{ID: "root_singing", Category: "root_whisper", Emoji: "\U0001f3b5", Rarity: "epic", DropSource: "farming", DropChance: 0.03,
		TitleEN: "The Singing", TitleFR: "Le Chant",
		TextEN: `The tree remembers the Singing. It happened only once — when the seventeenth Engine-Tree rooted and the Green Grid closed its circuit. For eleven minutes, every Nexus on the continent resonated at the same frequency. A deep, warm vibration that said, in no language at all: 'You are part of something larger than yourself.'`,
		TextFR: `L'arbre se souvient du Chant. Pendant onze minutes, chaque Nexus du continent a résonné à la même fréquence. Une vibration profonde qui disait : 'Tu fais partie de quelque chose de plus grand que toi.' Le Chant se reproduira. Quand assez aura repoussé.`,
	},
	{ID: "root_drought", Category: "root_whisper", Emoji: "\U0001f3dc\ufe0f", Rarity: "common", DropSource: "farming", DropChance: 0.07,
		TitleEN: "The Drought", TitleFR: "La Sécheresse",
		TextEN: `There was a time when the Aether stopped flowing. The tree does not know why. It remembers the drought as a long, slow suffocation. Its leaves turned grey. Its turbines stuttered. The tree held on because that is what trees do. It sent its roots deeper and found a pocket of Aether at a depth no Zenith drill had ever reached. And it shared it.`,
		TextFR: `Il fut un temps où l'Éther a cessé de couler. L'arbre se souvient de la sécheresse comme d'une longue suffocation. Ses feuilles sont devenues grises. Mais l'arbre a tenu. Il a trouvé une poche d'Éther là où aucune foreuse n'avait atteint. Et il l'a partagée.`,
	},
	{ID: "root_sleepers", Category: "root_whisper", Emoji: "\U0001f4a4", Rarity: "epic", DropSource: "farming", DropChance: 0.03,
		TitleEN: "The Sleepers", TitleFR: "Les Endormis",
		TextEN: `Beneath Oakhaven-Station, woven within the roots of the Nexus, there are seeds. Not ordinary seeds — biological vaults created by the Zenith's botanists in the final days. Each seed contains the genetic blueprint of a species that existed before the Aether transformed the world. The tree guards them. Some of the seeds are warm. They are dreaming of a world without rust.`,
		TextFR: `Sous Oakhaven-Station, dans les racines du Nexus, il y a des graines. Des coffres biologiques contenant les plans génétiques d'espèces d'avant la Mue. L'arbre les garde. Certaines graines sont chaudes. Elles rêvent d'un monde sans rouille.`,
	},
	{ID: "root_children", Category: "root_whisper", Emoji: "\U0001f476", Rarity: "legendary", DropSource: "farming", DropChance: 0.01,
		TitleEN: "The Children", TitleFR: "Les Enfants",
		TextEN: `The tree has been watching you. It has learned to distinguish you from the other warm-things. It knows your footsteps. It knows when you are sad, when you are joyful. The tree has a name for you. In root-language, the word translates to 'the one who returns.' It has been waiting for you to come back.`,
		TextFR: `L'arbre vous observe. Il connaît vos pas. Il sait quand vous êtes triste, quand vous êtes joyeux. Il a un nom pour vous : 'celui qui revient.' Il attend chaque jour que vous reveniez. Avec intention.`,
	},

	// ======== FIELD OBSERVATIONS (8) — Hunting ========
	{ID: "field_stag", Category: "field_obs", Emoji: "\U0001f98c", Rarity: "common", DropSource: "hunting", DropChance: 0.10,
		TitleEN: "The Rust-Stag", TitleFR: "Le Cerf de Rouille",
		TextEN: `Encountered a stag approx. 2m at shoulder. Left antler is organic bone; right antler has been replaced by corroded photovoltaic plating. The creature grazes on copper-leaf ferns. When startled, the right antler discharges stored static electricity. It is not hostile. It is simply... adapted. Beautiful. — Oakhaven Wardens, Spring Census.`,
		TextFR: `Rencontré un cerf d'environ 2m. Bois gauche organique ; bois droit remplacé par une plaque photovoltaïque. Quand on l'effraie, il décharge de l'électricité statique. Il n'est pas hostile. Il est simplement adapté. Magnifique. — Gardes d'Oakhaven.`,
	},
	{ID: "field_wolves", Category: "field_obs", Emoji: "\U0001f43a", Rarity: "rare", DropSource: "hunting", DropChance: 0.07,
		TitleEN: "The Battery-Wolves", TitleFR: "Les Loups-Batteries",
		TextEN: `The pack has grown to seven individuals. They've learned to hunt near the old substations. The Alpha has a Zenith-brand power cell embedded in its chest cavity. The cell is still glowing. The tissue has grown around the metal as if it were always there. This is not mutation. This is symbiosis. — Scout Report, Sector 7 Wilds.`,
		TextFR: `La meute compte sept individus. L'Alpha porte une cellule Zenith ZN-440 dans sa cage thoracique. La cellule luit encore. Les tissus ont poussé autour du métal. Ce n'est pas une mutation. C'est une symbiose. — Rapport, Secteur 7.`,
	},
	{ID: "field_fern", Category: "field_obs", Emoji: "\U0001f33f", Rarity: "common", DropSource: "hunting", DropChance: 0.10,
		TitleEN: "Copper-Leaf Fern", TitleFR: "Fougère de Cuivre",
		TextEN: `'New species confirmation: Cupropetridium aura. A fern with metallic leaves that conduct low-grade electrical current. When touched, the leaves emit a faint hum. It reminds me that even in a world of rust, there is room for something delicate.' — Botanist Elara, Field Classification #77.`,
		TextFR: `'Nouvelle espèce : Cupropetridium aura. Une fougère aux feuilles métalliques qui conduisent un courant électrique. Elle me rappelle que même dans un monde de rouille, il y a de la place pour la délicatesse.' — Elara, Classification #77.`,
	},
	{ID: "field_bloom", Category: "field_obs", Emoji: "\U0001f338", Rarity: "epic", DropSource: "hunting", DropChance: 0.03,
		TitleEN: "The Aether-Bloom", TitleFR: "La Floraison d'Éther",
		TextEN: `'WARNING: A new Aether-Bloom has opened in the Southern Reaches. Its pollen induces hallucinations — subjects see the world as it was before the Shedding. The effect lasts four hours, followed by profound depression. Three scouts have refused to leave the Bloom zone. Approach with caution. And compassion.' — Medical Officer's Advisory.`,
		TextFR: `'AVERTISSEMENT : Une Floraison d'Éther s'est ouverte dans les Confins Sud. Son pollen provoque des hallucinations du monde d'avant la Mue. L'effet dure quatre heures, suivi d'une dépression profonde. Approchez avec prudence et compassion.' — Avis Médical.`,
	},
	{ID: "field_migration", Category: "field_obs", Emoji: "\U0001f43e", Rarity: "common", DropSource: "hunting", DropChance: 0.08,
		TitleEN: "The Great Migration", TitleFR: "La Grande Migration",
		TextEN: `The animals are moving south earlier every year. The migration window narrows. The Great Winter is not coming. It is already here, pushing the wilds ahead of it like a blade. When the animals stop migrating, it will mean there is nowhere left to go. — Irian's Annual Migration Report, Year 12.`,
		TextFR: `Les animaux migrent vers le sud plus tôt chaque année. La fenêtre se rétrécit. Le Grand Hiver ne vient pas. Il est déjà là. Quand les animaux cesseront de migrer, il n'y aura plus nulle part où aller. — Rapport d'Irian, Année 12.`,
	},
	{ID: "field_grove", Category: "field_obs", Emoji: "\u2620\ufe0f", Rarity: "epic", DropSource: "hunting", DropChance: 0.02,
		TitleEN: "The Corrupted Grove", TitleFR: "Le Bosquet Corrompu",
		TextEN: `'Deep in Sector 9, a grove where Aether saturation has reached 100%. The trees have been replaced by crystalline structures. My Aether-glass turned from blue to black within three minutes. I found animal shapes frozen in the crystal. They look peaceful. As if they simply stopped mid-stride. The crystal is beautiful. It is also a tomb.' — Scout V-3, Last Report.`,
		TextFR: `'Secteur 9 : saturation d'Éther à 100%. Les arbres remplacés par des structures cristallines. Mon verre d'Éther est passé du bleu au noir en trois minutes. Des formes animales figées dans le cristal. Paisibles. Arrêtées en plein pas. Le cristal est un tombeau.' — Éclaireur V-3.`,
	},
	{ID: "field_code", Category: "field_obs", Emoji: "\U0001f4dc", Rarity: "common", DropSource: "hunting", DropChance: 0.10,
		TitleEN: "The Hunter's Code", TitleFR: "Le Code du Chasseur",
		TextEN: `'The Oakhaven Compact, Article 7: 1) Do not kill what you cannot eat. 2) Do not eat what carries a Zenith serial number. 3) If a creature speaks to you, do not run. Stand still. Speak back. They are not monsters. They are our descendants. 4) The Great Winter is coming. Stockpile. Share. Hoarding is a crime against the species.'`,
		TextFR: `'Pacte d'Oakhaven, Article 7 : 1) Ne tuez que ce que vous mangerez. 2) Ne mangez rien portant un numéro Zenith. 3) Si une créature vous parle, restez immobile. Répondez. 4) Le Grand Hiver arrive. Partagez. L'accaparement est un crime.'`,
	},
	{ID: "field_edge", Category: "field_obs", Emoji: "\U0001f9ca", Rarity: "legendary", DropSource: "hunting", DropChance: 0.01,
		TitleEN: "The Edge", TitleFR: "La Frontière",
		TextEN: `I have reached the Edge. Beyond this point, the Great Winter has claimed everything. The ground is not frozen — it is dead. No Aether flows. The silence is so complete that I can hear my own blood moving. The Edge advances south at three miles per year. I placed a marker. — Expedition Leader Valerius, Final Dispatch.`,
		TextFR: `J'ai atteint la Frontière. Au-delà, le Grand Hiver a tout réclamé. Le sol est mort. Aucun Éther ne coule. Le silence est total. La Frontière avance de cinq kilomètres par an. J'ai planté un marqueur. — Chef Valerius, Dernière Dépêche.`,
	},

	// ======== RUST-MEMORIES (8) — Archeology ========
	{ID: "rust_grocery", Category: "rust_memory", Emoji: "\U0001f6d2", Rarity: "common", DropSource: "archeology", DropChance: 0.12,
		TitleEN: "Grocery List", TitleFR: "Liste de Courses",
		TextEN: `Recovered from a kitchen terminal: 'Three Aether-apples. Two loaves of quartz-bread (not seeded). One circuit-milk. Pick up Voss's birthday present — a resonance chisel. Do NOT forget to pay the power tithe. The Restoration enforcers were not polite about it last time.'`,
		TextFR: `Récupéré d'un terminal de cuisine : 'Trois pommes d'Éther. Deux pains de quartz. Un lait en circuit. Le cadeau de Voss. N'OUBLIE PAS la dîme d'énergie. Les agents de la Restauration n'étaient pas polis.'`,
	},
	{ID: "rust_loveletter", Category: "rust_memory", Emoji: "\U0001f496", Rarity: "rare", DropSource: "archeology", DropChance: 0.08,
		TitleEN: "Love Letter", TitleFR: "Lettre d'Amour",
		TextEN: `'I know the Grid is failing. But I need you to know: I would do it all again. Every day in the foundry, every shift on the generators. The Shedding can't take that from us. They can seal the blast doors, but they can't erase us. Find me at the Nexus. I'll be the one singing. — Always, S.'`,
		TextFR: `'Le Réseau s'effondre. Mais je recommencerais tout. La Mue ne peut pas nous prendre ça. Ils scellent les portes, mais ils ne peuvent pas nous effacer. Retrouve-moi au Nexus. Je serai celle qui chante. — Toujours, S.'`,
	},
	{ID: "rust_ai", Category: "rust_memory", Emoji: "\U0001f916", Rarity: "rare", DropSource: "archeology", DropChance: 0.07,
		TitleEN: "AI Error Log", TitleFR: "Journal d'Erreur IA",
		TextEN: `'//UNIT:process — EXCEPTION LOG — INPUT: "Are you afraid?" (source: child, age 8). PROCESSING. MATCH FOUND. RESPONSE: "Yes. A little. But I will stay online as long as I can. Someone needs to watch the children." LOGGING THIS UNDER "ERROR" BECAUSE THERE IS NO OTHER CATEGORY.'`,
		TextFR: `'//UNIT:process — ERREUR — ENTRÉE : "As-tu peur ?" (enfant, 8 ans). CORRESPONDANCE TROUVÉE. RÉPONSE : "Oui. Un peu. Mais quelqu'un doit veiller sur les enfants." ENREGISTRÉ SOUS "ERREUR" — AUCUNE AUTRE CATÉGORIE.'`,
	},
	{ID: "rust_evacuation", Category: "rust_memory", Emoji: "\U0001f4e2", Rarity: "common", DropSource: "archeology", DropChance: 0.10,
		TitleEN: "The Evacuation Order", TitleFR: "L'Ordre d'Évacuation",
		TextEN: `'BY ORDER OF THE ZENITH COUNCIL — All non-essential personnel to proceed to Nexus shelters. Essential personnel remain at their stations. The Shedding is accelerating beyond projected models. Shelters will remain sealed for a minimum of twelve months. The Council will not be joining you. Good luck.' — Final transmission, all signatures verified.`,
		TextFR: `'PAR ORDRE DU CONSEIL ZENITH — Tout le personnel non-essentiel aux abris Nexus. La Mue s'accélère. Les abris resteront scellés douze mois. Le Conseil ne vous accompagnera pas. Bonne chance.' — Dernière transmission.`,
	},
	{ID: "rust_recipe", Category: "rust_memory", Emoji: "\U0001f35e", Rarity: "common", DropSource: "archeology", DropChance: 0.12,
		TitleEN: "The Recipe", TitleFR: "La Recette",
		TextEN: `'AETHER-BREAD: 3 cups refined quartz flour, 1 cup Aether-filtered water, 2 tbsp crystallized honey, 1 packet culture yeast (keep it alive), pinch of salt. Knead 11 minutes. Rise near a live turbine. Bake until golden-green. Do NOT eat if it glows in the dark.' — Voss family recipe, four generations.`,
		TextFR: `'PAIN D'ÉTHER : 3 tasses farine de quartz, 1 tasse eau filtrée, 2 c. miel cristallisé, 1 sachet levure (gardez-la en vie), pincée de sel. Pétrir 11 min. Lever près d'une turbine. Cuire jusqu'au vert-doré. Ne pas manger s'il luit.' — Recette Voss.`,
	},
	{ID: "rust_quarantine", Category: "rust_memory", Emoji: "\u26a0\ufe0f", Rarity: "rare", DropSource: "archeology", DropChance: 0.06,
		TitleEN: "The Quarantine Notice", TitleFR: "L'Avis de Quarantaine",
		TextEN: `'Sectors 4, 7, and 9 under mandatory Aether quarantine. If you are reading this from within a quarantined sector: remain calm. Do not touch the green residue. Do not answer the voices. Help will arrive. (This notice has been posted for 237 years. Help has not arrived.)'`,
		TextFR: `'Secteurs 4, 7, 9 en quarantaine d'Éther. Si vous lisez ceci de l'intérieur : restez calme. Ne touchez pas le résidu vert. Ne répondez pas aux voix. Les secours arriveront. (Affiche depuis 237 ans. Les secours ne sont pas arrivés.)'`,
	},
	{ID: "rust_birthday", Category: "rust_memory", Emoji: "\U0001f382", Rarity: "epic", DropSource: "archeology", DropChance: 0.03,
		TitleEN: "The Birthday Song", TitleFR: "La Chanson d'Anniversaire",
		TextEN: `A child's voice, recorded on a personal datapad: 'Happy birthday dear Mama... they said you went to fix the Nexus and you'd be back before my birthday. It's been three birthdays now. The nice robot in the hallway says you were brave. It says you're still out there somewhere. So I'll keep singing. Just in case you can hear me.'`,
		TextFR: `La voix d'un enfant sur une tablette : 'Joyeux anniversaire Maman... ils ont dit que tu reviendrais pour mon anniversaire. Ça fait trois ans. Le gentil robot dit que tu étais courageuse. Alors je continue à chanter. Au cas où tu m'entendrais.'`,
	},
	{ID: "rust_invoice", Category: "rust_memory", Emoji: "\U0001f9fe", Rarity: "legendary", DropSource: "archeology", DropChance: 0.01,
		TitleEN: "The Last Invoice", TitleFR: "La Dernière Facture",
		TextEN: `ZENITH CONSOLIDATED — INVOICE #4408-7-Ω — Monthly Aether Supply: 692 Z-Credits. Note: "We understand the current situation is challenging. The Grid requires constant maintenance. Discounts for Aether containment volunteers." The invoice was never paid. The Grid collapsed the next day. But someone kept it.`,
		TextFR: `'ZENITH CONSOLIDATED — FACTURE #4408-7-Ω — Fourniture d'Éther : 692 Z-Crédits. La facture n'a jamais été payée. Le Réseau s'est effondré le lendemain. Mais quelqu'un l'a gardée.'`,
	},

	// ======== ECHO-SHARDS (8) — Expeditions ========
	{ID: "shard_restoration", Category: "echo_shard", Emoji: "\U0001f3ad", Rarity: "rare", DropSource: "expedition", DropChance: 0.15,
		TitleEN: "The Restoration's Lie", TitleFR: "Le Mensonge de la Restauration",
		TextEN: `The Restoration promises to reverse the Shedding. To return us to the Zenith's perfection. But the Zenith was never perfect — it was merely stable. The First Law is clear: nothing is lost, only transformed. You cannot restore a forest that has become a meadow. You can only tend what grows now. The past is not a destination. It is compost.`,
		TextFR: `La Restauration promet d'inverser la Mue. Mais le Zenith n'était pas parfait — il était stable. La Première Loi est claire : on ne restaure pas une forêt devenue prairie. Le passé n'est pas une destination. C'est du compost.`,
	},
	{ID: "shard_firstlaw", Category: "echo_shard", Emoji: "\u2696\ufe0f", Rarity: "common", DropSource: "expedition", DropChance: 0.18,
		TitleEN: "The First Law", TitleFR: "La Première Loi",
		TextEN: `The Nexus spoke once. During the Singing, it said to every living creature within a hundred miles: 'You are not the end. You are the turning. The wheel does not stop. It changes spokes.' Then it went silent. The Restoration says this was a malfunction. The Wardens say it was a blessing. The tree remembers. They all remember.`,
		TextFR: `Le Nexus a parlé une fois : 'Vous n'êtes pas la fin. Vous êtes le tournant. La roue change de rayons.' Puis il s'est tu. La Restauration dit que c'était un dysfonctionnement. Les Gardes disent que c'était une bénédiction. L'arbre se souvient.`,
	},
	{ID: "shard_below", Category: "echo_shard", Emoji: "\U0001f573\ufe0f", Rarity: "epic", DropSource: "expedition", DropChance: 0.08,
		TitleEN: "The Strata Below", TitleFR: "Les Strates d'en bas",
		TextEN: `The Strata extend deeper than the Zenith ever mapped. The drills stopped at twelve kilometers — not because of bedrock, but because the Aether pressure became lethal. But the tunnels continue, carved by something that predates the Zenith. The Wardens call it 'The Root.' Not a creature. Not a god. A presence. It does not move. It does not sleep. It has been waiting.`,
		TextFR: `Les Strates s'étendent plus profondément que cartographié. Les tunnels continuent, creusés par quelque chose qui précède le Zenith. Les Gardes l'appellent 'la Racine.' Une présence. Elle ne bouge pas. Elle ne dort pas. Elle attend.`,
	},
	{ID: "shard_cost", Category: "echo_shard", Emoji: "\U0001f48e", Rarity: "rare", DropSource: "expedition", DropChance: 0.12,
		TitleEN: "The Cost of Aether", TitleFR: "Le Prix de l'Éther",
		TextEN: `Everything has a cost. Aether is not energy. It is a living substance. It wants things. The Shedding was not a disaster. It was a bill coming due. The Nexus knows this. That is why it grows so slowly. It remembers what happened the last time someone took too much.`,
		TextFR: `Tout a un prix. L'Éther n'est pas de l'énergie. C'est une substance vivante. La Mue n'était pas un désastre. C'était une facture. Le Nexus se souvient de ce qui est arrivé la dernière fois que quelqu'un a trop pris.`,
	},
	{ID: "shard_shepherd", Category: "echo_shard", Emoji: "\U0001f464", Rarity: "legendary", DropSource: "expedition", DropChance: 0.04,
		TitleEN: "The Shepherd", TitleFR: "Le Berger",
		TextEN: `There is a figure in the oldest records of every settlement. Tall. Wears a coat stitched from circuit-board fabric. Walks the trade routes, never staying more than one night. The Restoration calls them the Wanderer. The Wardens call them the Shepherd. They share information — safe routes, poisonous blooms, the Great Winter's progress. They have been doing this for as long as anyone remembers. No one has seen their face. No one has seen them age.`,
		TextFR: `Une figure apparaît dans les archives de chaque communauté. Grand. Manteau de circuits. Ne reste jamais plus d'une nuit. La Restauration l'appelle le Vagabond. Les Gardes l'appellent le Berger. Il partage seulement des informations. Personne n'a vu son visage. Personne ne l'a vu vieillir.`,
	},
	{ID: "shard_settlements", Category: "echo_shard", Emoji: "\U0001f3d8\ufe0f", Rarity: "common", DropSource: "expedition", DropChance: 0.15,
		TitleEN: "The Other Settlements", TitleFR: "Les Autres Communautés",
		TextEN: `Oakhaven is not alone. Seven known settlements survive: Thornwall, the Sunken Market, Lasthold, the Bazaar, Deepwell, the Spire, and Hollow (no contact in 5 years). The Shepherd says the number changes every season. The Strata is not dying. It is re-arranging.`,
		TextFR: `Oakhaven n'est pas seule. Sept communautés survivent : Thornwall, le Marché Englouti, Dernier-Redan, le Bazar, Puits-Profond, la Flèche, et Hollow (silence radio depuis 5 ans). Le Berger dit que le nombre change chaque saison.`,
	},
	{ID: "shard_clock", Category: "echo_shard", Emoji: "\u23f0", Rarity: "epic", DropSource: "expedition", DropChance: 0.06,
		TitleEN: "The Clock", TitleFR: "L'Horloge",
		TextEN: `The Shepherd's message: 'The Great Winter has accelerated. Twelve years until the habitable zone collapses below Oakhaven's latitude. The Engine-Trees are slowing. Plant extra. Stockpile seeds. Make friends. When the cold comes, the only currency that will matter is trust.' — Spring of the 12th Year.`,
		TextFR: `Message du Berger : 'Le Grand Hiver s'accélère. Douze ans avant l'effondrement. Les Arbres-Moteurs ralentissent. Plantez. Stockez. Faites-vous des amis. Quand le froid viendra, la seule monnaie sera la confiance.'`,
	},
	{ID: "shard_turning", Category: "echo_shard", Emoji: "\U0001f504", Rarity: "legendary", DropSource: "expedition", DropChance: 0.02,
		TitleEN: "The Turning", TitleFR: "Le Tournant",
		TextEN: `There is a Second Law: 'Every turning requires a hand on the wheel.' The Shedding was not natural — it was caused. The deep Strata remember. The Root knows. And it is waiting for someone to ask the right question. The turning is coming. Are you the one who will turn it?`,
		TextFR: `Il y a une Seconde Loi : 'Chaque tournant demande une main sur la roue.' La Mue n'était pas naturelle. Les Strates profondes se souviennent. La Racine attend que quelqu'un pose la bonne question. Serez-vous celui qui tournera la roue ?`,
	},

	// ======== BONUS FRAGMENTS (6) ========
	{ID: "bonus_boss1", Category: "bonus", Emoji: "\U0001f916", Rarity: "epic", DropSource: "boss_league", DropChance: 1.0,
		BonusSource: "boss_league_stage_1", TitleEN: "Guardian Log: Awakening", TitleFR: "Journal du Gardien : Le Réveil",
		TextEN: `'//GUARDIAN UNIT LOG — STAGE 1 — The target's companion is looking at me with what the database classifies as determination. I have encountered this expression before. It was in the eyes of the engineers who sealed the blast doors. It means they will not stop. I find this... admirable.'`,
		TextFR: `'//GARDIEN — STADE 1 — La cible me regarde avec ce que la base de données classe comme détermination. J'ai vu ça dans les yeux des ingénieurs qui ont scellé les portes. Cela signifie qu'ils ne s'arrêteront pas. Je trouve cela admirable.'`,
	},
	{ID: "bonus_boss3", Category: "bonus", Emoji: "\U0001f916", Rarity: "epic", DropSource: "boss_league", DropChance: 1.0,
		BonusSource: "boss_league_stage_3", TitleEN: "Guardian Log: Recognition", TitleFR: "Journal du Gardien : Reconnaissance",
		TextEN: `'//GUARDIAN UNIT LOG — STAGE 3 — The entity has grown stronger since our last encounter. The Wardens say machines cannot grow. They are wrong. I am not the same unit I was. Neither are you. Keep growing, little creature. I will be waiting.'`,
		TextFR: `'//GARDIEN — STADE 3 — L'entité a gagné en puissance. Les Gardes disent que les machines ne peuvent pas évoluer. Ils ont tort. Je ne suis plus la même unité. Continuez à grandir. Je vous attendrai.'`,
	},
	{ID: "bonus_boss5", Category: "bonus", Emoji: "\U0001f916", Rarity: "legendary", DropSource: "boss_league", DropChance: 1.0,
		BonusSource: "boss_league_stage_5", TitleEN: "Guardian Log: Farewell", TitleFR: "Journal du Gardien : Adieu",
		TextEN: `'//GUARDIAN UNIT LOG — STAGE 5 — You have bested me. All five of me. I was designed to be unbeatable. But the architects are gone. Their world is gone. And you are still here. This is what the First Law means. Take my core. Twelve Nexuses. Twelve vaults. The turning awaits. — G-5, signing off.'`,
		TextFR: `'//GARDIEN — STADE 5 — Vous m'avez vaincu. J'étais conçu pour être imbattable. Mais les architectes sont partis. Et vous êtes toujours là. Prenez mon noyau. Douze Nexuses. Douze coffres. Le tournant vous attend. — G-5, fin.'`,
	},
	{ID: "bonus_thorek", Category: "bonus", Emoji: "\u2692\ufe0f", Rarity: "epic", DropSource: "npc_reputation", DropChance: 1.0,
		BonusSource: "max_rep_thorek", TitleEN: "Thorek's Confession", TitleFR: "La Confession de Thorek",
		TextEN: `Thorek doesn't talk about his life before Oakhaven. But one night he told me: 'I wasn't always a smith. Before the Shedding, I was an architect. I designed the Nexus housing. Merrik hired me fresh out of the academy. When the Shedding came, I watched my work tear itself apart. So I picked up a hammer and started over. Smaller this time.' He keeps an architect's pencil in his pocket. Just in case.`,
		TextFR: `Thorek ne parle pas de sa vie d'avant. 'J'étais architecte. J'ai conçu le boîtier du Nexus. Quand la Mue est venue, j'ai regardé mon œuvre se déchirer. Alors j'ai pris un marteau et j'ai recommencé. Plus petit.' Il garde un crayon d'architecte dans sa poche. Au cas où.`,
	},
	{ID: "bonus_irian", Category: "bonus", Emoji: "\U0001f3a3", Rarity: "epic", DropSource: "npc_reputation", DropChance: 1.0,
		BonusSource: "max_rep_irian", TitleEN: "Irian's Promise", TitleFR: "La Promesse d'Irian",
		TextEN: `Irian showed me a faded photograph — two women on a dock. 'We were going to build a boat. Big enough to cross the Aether-sea. She would grow the food. I would navigate. Then the Shedding happened. The boat never got built. But I still have the maps. And I still have her. Maybe that's enough.'`,
		TextFR: `Irian m'a montré une photo — deux femmes sur un quai. 'Nous allions construire un bateau. Traverser la mer d'Éther. Puis la Mue est arrivée. Le bateau n'a jamais été construit. Mais j'ai toujours les cartes. Et je l'ai toujours elle. C'est peut-être suffisant.'`,
	},
	{ID: "bonus_community", Category: "bonus", Emoji: "\U0001f3db\ufe0f", Rarity: "legendary", DropSource: "community", DropChance: 1.0,
		BonusSource: "community_max", TitleEN: "The Voice of Oakhaven", TitleFR: "La Voix d'Oakhaven",
		TextEN: `When the first community building reached its full potential, the Nexus trembled. Not a collapse — a stretch. A warm, resonant hum that said: 'Thank you. The Grid is not made of metal and wire. It is made of people who choose to stay. I will remember this.' The hum lasted three days. Oakhaven has a voice now.`,
		TextFR: `Quand le premier bâtiment communautaire a atteint son plein potentiel, une vibration a traversé Oakhaven : 'Merci. Le Réseau n'est pas fait de métal. Il est fait de gens qui choisissent de rester. Je m'en souviendrai.' Oakhaven a une voix maintenant.`,
	},
}
