package hoakhaven

import "guacagamblebot/internal/universe"

var Fragments = []universe.Fragment{
	// ======== AETHER-LOGS (8) — Mining ========
	{ID: "log_signal", Category: "aether_log", Emoji: "\U0001f4e1", Rarity: "rare", DropSource: "mining", DropChance: 0.08,
		TitleEN: "The Signal", TitleFR: "Le Signal",
		TextEN: `Engineer-Major Voss's final broadcast: 'If anyone can hear this, the purification chambers have failed. Aether saturation in the lower Strata is at 97%. We're sealing the doors. Don't open them. The things in the dark aren't us anymore. May the Nexus forgive us.'`,
		TextFR: `Dernière diffusion de l'Ingénieur-Major Voss : « Si quelqu'un entend ça, les chambres de purification ont cédé. Saturation d'Éther à 97%. Nous scellons les portes. Ne les ouvrez pas. Les choses dans le noir ne sont plus nous. Que le Nexus nous pardonne. »`,
	},
	{ID: "log_gardener", Category: "aether_log", Emoji: "\U0001f331", Rarity: "common", DropSource: "mining", DropChance: 0.12,
		TitleEN: "The Gardener", TitleFR: "Le Jardinier",
		TextEN: `Merrik's notes: 'The Aether-Root protocol works. We bonded a copper-oak sapling to the main turbine. It draws Aether from the leak and converts it to stable biomass. A green backup. Kael would hate that pun.'`,
		TextFR: `Notes de Merrik : « Le protocole Racine-d'Éther fonctionne. On a greffé un chêne-de-cuivre à la turbine principale. Il aspire l'Éther, le transforme en biomasse stable. Une sauvegarde verte. Kael détesterait ce jeu de mots. »`,
	},
	{ID: "log_transmission", Category: "aether_log", Emoji: "\U0001f4fb", Rarity: "epic", DropSource: "mining", DropChance: 0.04,
		TitleEN: "The Last Transmission", TitleFR: "La Dernière Transmission",
		TextEN: `'Frequency 7-4-0. Anyone receiving? The southern arcology collapsed at 03:00. Forty thousand inside. We heard the Nexuses singing before it fell. All of them, across the continent, at once. A choir of dying stars. I don't think the Shedding was an accident. I think it was a harvest.'`,
		TextFR: `« Fréquence 7-4-0. Quelqu'un reçoit ? L'arcologie sud s'est effondrée à 03h00. Quarante mille à l'intérieur. On a entendu les Nexuses chanter avant la chute. Tous en même temps. Un chœur d'étoiles mourantes. La Mue n'était pas un accident. C'était une récolte. »`,
	},
	{ID: "log_purge", Category: "aether_log", Emoji: "\U0001f512", Rarity: "common", DropSource: "mining", DropChance: 0.10,
		TitleEN: "Purge Protocol", TitleFR: "Protocole de Purge",
		TextEN: `'Directive 88: Evacuation of the lower Strata is cancelled. Seal the blast doors. All personnel report to Nexus-level. Aether-tainted individuals will not be permitted above Sector 4. This is not a debate. This is protocol.'`,
		TextFR: `« Directive 88. L'évacuation des Strates inférieures est annulée. Scellez les portes. Tout le personnel au niveau Nexus. Les contaminés par l'Éther ne passeront pas le Secteur 4. Ce n'est pas un débat. C'est le protocole. »`,
	},
	{ID: "log_surveyor", Category: "aether_log", Emoji: "\U0001f50d", Rarity: "rare", DropSource: "mining", DropChance: 0.07,
		TitleEN: "The Surveyor", TitleFR: "L'Arpenteur",
		TextEN: `Surveyor Tesh's final log: 'Aether readings are off the scale. The ground is humming. Thirty years of samples and I've never seen this. The minerals are growing. Not crystallizing. Growing. Something alive in the deep Strata. Something that was here before the Zenith.'`,
		TextFR: `Dernier rapport de l'Arpenteuse Tesh : « Les relevés d'Éther sont hors d'échelle. Le sol bourdonne. Trente ans d'échantillons et je n'ai jamais vu ça. Les minéraux poussent. Pas des cristaux. Ils croissent. Quelque chose de vivant dans les Strates profondes. Quelque chose qui était là avant le Zenith. »`,
	},
	{ID: "log_children", Category: "aether_log", Emoji: "\U0001f49b", Rarity: "epic", DropSource: "mining", DropChance: 0.03,
		TitleEN: "Children of the Grid", TitleFR: "Enfants du Réseau",
		TextEN: `'To whoever finds this. My name is Lira Voss. I'm seven. Mum said the Grid would protect us. But the Aether is eating the walls. I'm in the bunker with thirty other kids. The grown-ups left five days ago to fix the Nexus. They haven't come back. If you find this, please tell them we're still waiting.'`,
		TextFR: `« À qui trouvera ce cristal. Je m'appelle Lira Voss. J'ai sept ans. Maman disait que le Réseau nous protégerait. Mais l'Éther mange les murs. Je suis dans le bunker avec trente autres enfants. Les adultes sont partis réparer le Nexus il y a cinq jours. Ils ne sont pas revenus. S'il vous plaît, dites-leur qu'on attend encore. »`,
	},
	{ID: "log_silence", Category: "aether_log", Emoji: "\U0001f92b", Rarity: "legendary", DropSource: "mining", DropChance: 0.01,
		TitleEN: "The Silence", TitleFR: "Le Silence",
		TextEN: `No message. Only a recording. The exact moment every Nexus on the continent went silent, simultaneously. Eleven seconds. The first four: the low hum of civilization. The next two: a rising tone just below hearing. The final five: absolute silence. The crystal is warm to the touch.`,
		TextFR: `Aucun message. Juste un enregistrement. Le moment précis où tous les Nexuses du continent se sont tus. Onze secondes. Les quatre premières : le bourdonnement sourd de la civilisation. Les deux suivantes : une tonalité montante. Les cinq dernières : un silence total. Le cristal est chaud au toucher.`,
	},
	{ID: "log_threshold", Category: "aether_log", Emoji: "\u2744\ufe0f", Rarity: "rare", DropSource: "mining", DropChance: 0.06,
		TitleEN: "The Threshold", TitleFR: "Le Seuil",
		TextEN: `'Climate model 7-R: The Great Winter is not a natural season. It's a byproduct of Aether decay. Warm periods shorten every year. If we can't stop the leak, the Strata will be uninhabitable within twelve generations. This isn't fear. It's mathematics.'`,
		TextFR: `« Modèle climatique 7-R. Le Grand Hiver n'est pas naturel. C'est un sous-produit de la dégradation de l'Éther. Chaque année, la saison chaude raccourcit. Si on n'arrête pas la fuite, les Strates seront inhabitables dans douze générations. Ce n'est pas de la peur. Ce sont des maths. »`,
	},
	{ID: "log_seam", Category: "aether_log", Emoji: "\U0001f52e", Rarity: "rare", DropSource: "mining", DropChance: 0.05,
		TitleEN: "The Thin Wall", TitleFR: "Le Mur Mince",
		TextEN: `'Tunnel 9, Strata 4. My pick went through the wall like water. No rock beyond it. No void either. A room that wasn't a room — same air, same lamps, but wrong. Wrong like a word you've heard a thousand times, said once too slow. I touched the far wall. It gave. Like skin. Like something waiting. The foreman says I passed out from Aether. Fine. Let him think that.' — Digger Ynn's last log.`,
		TextFR: `« Tunnel 9, Strates 4. Ma pioche a traversé la paroi comme de l'eau. Pas de roche derrière. Pas de vide non plus. Une pièce qui n'était pas une pièce — le même air, les mêmes lampes, mais faux. Faux comme un mot entendu mille fois, prononcé une fois de trop lentement. J'ai touché le mur du fond. Il a cédé. Comme de la peau. Comme quelque chose qui attend. Le contremaître dit que je me suis évanoui à cause de l'Éther. Très bien. Qu'il le croie. » — Dernier journal de la foreuse Ynn.`,
	},

	// ======== TIDE-SCROLLS (8) — Fishing ========
	{ID: "scroll_prayer", Category: "tide_scroll", Emoji: "\U0001f64f", Rarity: "common", DropSource: "fishing", DropChance: 0.12,
		TitleEN: "The Dockworker's Prayer", TitleFR: "La Prière du Débardeur",
		TextEN: `Inscription on a corroded pier at the old Oakhaven docks: 'O Zenith, who forged the gears of the world. Steady hands, full nets. Keep the Rust-Eaters in the deep water where they belong. Keep my children's lungs clear of the green. Amen.'`,
		TextFR: `Inscription sur un pilier rouillé des vieux quais d'Oakhaven : « Ô Zenith, qui forgeas les engrenages du monde. Mains stables, filets pleins. Laisse les Mangeurs-Rouille dans les profondeurs. Garde les poumons de mes enfants libres du vert. Amen. »`,
	},
	{ID: "scroll_migration", Category: "tide_scroll", Emoji: "\U0001f5fa\ufe0f", Rarity: "common", DropSource: "fishing", DropChance: 0.10,
		TitleEN: "Migration Patterns", TitleFR: "Routes de Migration",
		TextEN: `'The Silver-Spine Shoal shifted route again. Something in the deep water is pushing them. I charted the new path: follow the Silver-Spine, find pockets of pure Aether. The fish know what the machines forgot.' — Irian's first chart, pre-Council.`,
		TextFR: `« Le banc d'Argentins a encore changé de route. Quelque chose dans les profondeurs les pousse. J'ai tracé leur chemin : suis les Argentins, trouve des poches d'Éther pur. Les poissons savent ce que les machines ont oublié. » — Première carte d'Irian, avant le Conseil.`,
	},
	{ID: "scroll_captain", Category: "tide_scroll", Emoji: "\u2693", Rarity: "rare", DropSource: "fishing", DropChance: 0.07,
		TitleEN: "The Captain's Log", TitleFR: "Le Journal du Capitaine",
		TextEN: `'Log 12 of the Aether-Swift. Day 47 at sea. We've followed Aether blooms north for six weeks. Last night: lights beneath the water. Not bioluminescence. Not reflections. Patterned lights. Deliberate. The navigator says turn back. The cargo hold is full of rust-cured salvage. I gave the order to continue.'`,
		TextFR: `« Journal 12 de l'Éther-Rapide. Jour 47. Six semaines à suivre les floraisons d'Éther vers le nord. Cette nuit : des lumières sous l'eau. Pas de la bioluminescence. Pas des reflets. Des motifs. Délibérés. Le navigateur veut faire demi-tour. La cale est pleine. J'ai donné l'ordre de continuer. »`,
	},
	{ID: "scroll_letter", Category: "tide_scroll", Emoji: "\U0001f48c", Rarity: "rare", DropSource: "fishing", DropChance: 0.06,
		TitleEN: "Letter to Shore", TitleFR: "Lettre au Rivage",
		TextEN: `'Elara. The sea is cruel and beautiful. I've seen a kelp forest that glows at night. A creature the size of an island slept beneath our hull for three days. More than anything, I miss the way you hum when you tend your garden. I'll be home by spring.' — Irian.`,
		TextFR: `« Elara. La mer est cruelle et belle. J'ai vu une forêt de kelp qui brille la nuit. Une créature grande comme une île a dormi sous notre coque trois jours. Mais plus que tout, ton absence me pèse. Le son de ta voix quand tu chantes dans le jardin. Je serai là au printemps. » — Irian.`,
	},
	{ID: "scroll_tidechildren", Category: "tide_scroll", Emoji: "\U0001f9dc", Rarity: "common", DropSource: "fishing", DropChance: 0.10,
		TitleEN: "The Tide-Children", TitleFR: "Les Enfants de la Marée",
		TextEN: `Old Merrik used to say: when the tide pulls back too far and the rocks steam with green mist, the Tide-Children come. They're not fish. Not people. Humans who survived drowning in an Aether-saturated sea. They don't breathe. Don't age. They just wait. — Oakhaven-Station archive.`,
		TextFR: `Le vieux Merrik disait : quand la mer se retire trop loin et que les rochers fument vert, les Enfants de la Marée arrivent. Ni poissons, ni humains. Des gens qui ont survécu à la noyade dans une mer saturée d'Éther. Ils ne respirent pas. Ne vieillissent pas. Ils attendent. — Archives d'Oakhaven.`,
	},
	{ID: "scroll_manifest", Category: "tide_scroll", Emoji: "\U0001f4e6", Rarity: "common", DropSource: "fishing", DropChance: 0.10,
		TitleEN: "Cargo Manifest", TitleFR: "Manifeste de Cargaison",
		TextEN: `'HAUL 88-40Z. Recovered from submerged Zenith depot, Sector 9. 12 crates circuit-bread. 8 cases rations. 3 charged Aether-cells. 1 trunk personal effects. 1 sealed crate marked "ZEAL, DO NOT OPEN, SITE 7". Left on the seabed. Let sleeping dogs lie.'`,
		TextFR: `« LOT 88-40Z. Récupéré d'un dépôt Zenith submergé, Secteur 9. 12 caisses de pain-circuit. 8 caisses de rations. 3 cellules d'Éther. 1 malle d'effets personnels. 1 caisse scellée marquée 'ZÈLE, NE PAS OUVRIR, SITE 7'. Laissée au fond. Laissons dormir. »`,
	},
	{ID: "scroll_lighthouse", Category: "tide_scroll", Emoji: "\U0001f4a1", Rarity: "epic", DropSource: "fishing", DropChance: 0.03,
		TitleEN: "The Lighthouse Keeper", TitleFR: "Le Gardien du Phare",
		TextEN: `'Year 47. Last keeper of the Northern Light. The tower still works. Its Aether lens cuts through the fog. No ships to guide. The sea rose twelve metres since the Shedding. Two floors underwater. The Tide-Children visit. They tap on the glass. I tap back. It's a kind of conversation.' — Keeper Sol, 347th day of the Long Night.`,
		TextFR: `« An 47. Dernier gardien de la Lumière du Nord. La tour fonctionne encore. Sa lentille d'Éther perce le brouillard. Plus aucun bateau à guider. La mer a monté de douze mètres. Deux étages sous l'eau. Les Enfants de la Marée tapent à la vitre. Je réponds. Une sorte de conversation. » — Gardien Sol, 347e jour.`,
	},
	{ID: "scroll_deep", Category: "tide_scroll", Emoji: "\U0001f30a", Rarity: "legendary", DropSource: "fishing", DropChance: 0.01,
		TitleEN: "The Deep Places", TitleFR: "Les Abysses",
		TextEN: `'I descended three days. The pressure should have killed me. The deep places aren't empty. Towers of fused coral and Zenith steel. In the central plaza: a machine the size of a mountain, pulsing with a slow, patient rhythm. Not a machine. A heart.' — The Descent of Aris Thorne.`,
		TextFR: `« Je suis descendu trois jours. La pression aurait dû me tuer. Les abysses ne sont pas vides. Des tours de corail soudé et d'acier Zenith. Sur la place centrale : une machine grande comme une montagne, pulsant d'un rythme lent et patient. Pas une machine. Un cœur. » — La Descente d'Aris Thorne.`,
	},

	// ======== ROOT-WHISPERS (8) — Farming ========
	{ID: "root_gears", Category: "root_whisper", Emoji: "\u2699\ufe0f", Rarity: "common", DropSource: "farming", DropChance: 0.08,
		TitleEN: "The Dream of Gears", TitleFR: "Le Rêve des Engrenages",
		TextEN: `The tree doesn't understand time. It remembers the engineers who planted its seed. Not as people. As a sensation of warmth. A brief, bright flicker. They're gone now, but their heat remains in the roots. The tree calls this grief. It's the only emotion it shares with you.`,
		TextFR: `L'arbre ne comprend pas le temps. Il se souvient des ingénieurs comme d'une sensation de chaleur. Une brève lueur. Ils sont partis, mais leur chaleur demeure dans les racines. L'arbre appelle ça le chagrin. Chaque fois que tu te reposes sous ses branches, il demande : « As-tu chaud, petit ? »`,
	},
	{ID: "root_shedding", Category: "root_whisper", Emoji: "\U0001f342", Rarity: "rare", DropSource: "farming", DropChance: 0.06,
		TitleEN: "The Shedding from Below", TitleFR: "La Mue vue d'en bas",
		TextEN: `The Nexus remembers the fall of the old world. Not as catastrophe. As release. A season it waited ten thousand years to feel. What you call the Shedding, the tree calls spring. It doesn't understand why you mourn. The old world fell. This world grows from its corpse. This isn't tragedy. This is the cycle.`,
		TextFR: `Le Nexus se souvient de la chute de l'ancien monde. Pas comme une catastrophe. Comme une libération. Une saison attendue depuis dix mille ans. Ce que tu appelles la Mue, l'arbre appelle le printemps. L'ancien monde est tombé. Celui-ci pousse de son cadavre. Ce n'est pas une tragédie. C'est le cycle.`,
	},
	{ID: "root_graft", Category: "root_whisper", Emoji: "\U0001f33f", Rarity: "common", DropSource: "farming", DropChance: 0.08,
		TitleEN: "The Grafting", TitleFR: "La Greffe",
		TextEN: `'Procedure 7-Alpha. Copper-Oak sapling grafted to Zenith ZN-440 turbine. Roots accepted the Aether flow. Turbine hum dropped from 88 dB to 42 dB. The sapling appears to be singing. We're calling this Harmonic Equilibrium.' — Merrik, Day 1 of the Grafting Trials.`,
		TextFR: `« Procédure 7-Alpha. Jeune chêne-de-cuivre greffé sur turbine ZN-440. Les racines acceptent le flux d'Éther. Le bourdonnement est tombé de 88 dB à 42 dB. Le jeune arbre semble chanter. On appelle ça l'Équilibre Harmonique. » — Merrik, Jour 1 des Essais de Greffe.`,
	},
	{ID: "root_grid", Category: "root_whisper", Emoji: "\U0001f50b", Rarity: "rare", DropSource: "farming", DropChance: 0.05,
		TitleEN: "The Green Grid", TitleFR: "Le Réseau Vert",
		TextEN: `'Phase 3: The Green Grid is live. Seventeen Engine-Trees across the continent, one living network. They share power loads through their roots. Faster than our data cables. Smarter than our grid ever was. They will outlast everything.' — Zenith Botanical Engineering Division, final report.`,
		TextFR: `« Phase 3 : Le Réseau Vert est en ligne. Dix-sept Arbres-Moteurs connectés en un seul réseau vivant. Ils partagent les charges par les racines. Plus rapides que nos câbles. Plus intelligents que notre réseau. Ils nous survivront. » — Division Botanique Zenith, rapport final.`,
	},
	{ID: "root_singing", Category: "root_whisper", Emoji: "\U0001f3b5", Rarity: "epic", DropSource: "farming", DropChance: 0.03,
		TitleEN: "The Singing", TitleFR: "Le Chant",
		TextEN: `The tree remembers the Singing. It happened once. When the seventeenth Engine-Tree rooted and the Green Grid closed its circuit. For eleven minutes, every Nexus on the continent resonated at the same frequency. A deep vibration that said, in no language at all: you're part of something larger.`,
		TextFR: `L'arbre se souvient du Chant. Une seule fois. Quand le dix-septième Arbre-Moteur a pris racine et fermé le circuit. Pendant onze minutes, chaque Nexus du continent a résonné à la même fréquence. Une vibration qui disait sans mots : tu fais partie de quelque chose de plus grand.`,
	},
	{ID: "root_drought", Category: "root_whisper", Emoji: "\U0001f3dc\ufe0f", Rarity: "common", DropSource: "farming", DropChance: 0.07,
		TitleEN: "The Drought", TitleFR: "La Sécheresse",
		TextEN: `The Aether stopped once. The tree doesn't know why. It remembers the drought as a slow suffocation. Leaves grey. Turbines stuttering. The tree held on because that's what trees do. It sent roots deeper and found a pocket of Aether at a depth no drill ever reached. Then it shared it.`,
		TextFR: `L'Éther s'est arrêté une fois. L'arbre ne sait pas pourquoi. Il se souvient de la sécheresse comme d'une lente suffocation. Feuilles grises. Turbines qui toussent. L'arbre a tenu, parce que c'est ce que font les arbres. Il a plongé ses racines plus profond et trouvé une poche d'Éther. Puis il l'a partagée.`,
	},
	{ID: "root_sleepers", Category: "root_whisper", Emoji: "\U0001f4a4", Rarity: "epic", DropSource: "farming", DropChance: 0.03,
		TitleEN: "The Sleepers", TitleFR: "Les Endormis",
		TextEN: `Beneath Oakhaven-Station, woven into the Nexus roots: seeds. Not ordinary seeds. Biological vaults created by Zenith botanists in the final days. Each contains the genetic blueprint of a species from before the Aether. The tree guards them. Some are warm. They dream of a world without rust.`,
		TextFR: `Sous Oakhaven-Station, dans les racines du Nexus : des graines. Pas des graines ordinaires. Des coffres biologiques créés par les botanistes du Zenith juste avant la fin. Chacune contient le plan génétique d'une espèce d'avant l'Éther. L'arbre les garde. Certaines sont chaudes. Elles rêvent d'un monde sans rouille.`,
	},
	{ID: "root_children", Category: "root_whisper", Emoji: "\U0001f476", Rarity: "legendary", DropSource: "farming", DropChance: 0.01,
		TitleEN: "The Children", TitleFR: "Les Enfants",
		TextEN: `The tree has been watching you. It knows your footsteps. It knows when you're sad, when you're happy. It has a name for you. In root-language, the word means the one who returns. It waits for you every day.`,
		TextFR: `L'arbre t'observe. Il connaît tes pas. Il sait quand tu es triste, quand tu es heureux. Il a un nom pour toi. En langue-racine, le mot signifie celui qui revient. Il t'attend chaque jour.`,
	},

	// ======== FIELD OBSERVATIONS (8) — Hunting ========
	{ID: "field_stag", Category: "field_obs", Emoji: "\U0001f98c", Rarity: "common", DropSource: "hunting", DropChance: 0.10,
		TitleEN: "The Rust-Stag", TitleFR: "Le Cerf de Rouille",
		TextEN: `Stag, approx. 2m at shoulder. Left antler: organic bone. Right antler: corroded photovoltaic plating. Grazes on copper-leaf ferns. When startled, right antler discharges stored static. Not hostile. Just adapted. Beautiful. — Oakhaven Wardens, Spring Census.`,
		TextFR: `Cerf, environ 2 mètres. Bois gauche : os organique. Bois droit : plaque photovoltaïque corrodée. Broute des fougères de cuivre. Surpris, il décharge de l'électricité statique. Pas hostile. Juste adapté. Magnifique. — Gardes d'Oakhaven, Recensement de Printemps.`,
	},
	{ID: "field_wolves", Category: "field_obs", Emoji: "\U0001f43a", Rarity: "rare", DropSource: "hunting", DropChance: 0.07,
		TitleEN: "The Battery-Wolves", TitleFR: "Les Loups-Batteries",
		TextEN: `Pack of seven. They hunt near the old substations. The Alpha has a Zenith power cell embedded in its chest. Still glowing. Tissue grown around the metal like it was always there. Not mutation. Symbiosis. — Scout Report, Sector 7.`,
		TextFR: `Meute de sept. Ils chassent près des vieux postes électriques. L'Alpha porte une cellule Zenith ZN-440 dans la poitrine. Elle luit encore. Les tissus ont poussé autour du métal. Pas une mutation. Une symbiose. — Rapport, Secteur 7.`,
	},
	{ID: "field_fern", Category: "field_obs", Emoji: "\U0001f33f", Rarity: "common", DropSource: "hunting", DropChance: 0.10,
		TitleEN: "Copper-Leaf Fern", TitleFR: "Fougère de Cuivre",
		TextEN: `'New species: Cupropetridium aura. Metallic leaves that conduct low-grade current. Touch them and they hum. A reminder that even in a world of rust, there's room for something delicate.' — Elara, Field Classification #77.`,
		TextFR: `« Nouvelle espèce : Cupropetridium aura. Des feuilles métalliques qui conduisent un faible courant. On les touche, elles fredonnent. Un rappel que même dans un monde de rouille, il y a de la place pour la délicatesse. » — Elara, Classification #77.`,
	},
	{ID: "field_bloom", Category: "field_obs", Emoji: "\U0001f338", Rarity: "epic", DropSource: "hunting", DropChance: 0.03,
		TitleEN: "The Aether-Bloom", TitleFR: "La Floraison d'Éther",
		TextEN: `'A new Aether-Bloom opened in the Southern Reaches. Its pollen shows you the world before the Shedding. Hallucinations last four hours, followed by deep depression. Three scouts refused to leave the Bloom zone. Approach with caution. And compassion.' — Medical Advisory.`,
		TextFR: `« Une nouvelle Floraison d'Éther s'est ouverte dans les Confins Sud. Son pollen montre le monde d'avant la Mue. Hallucinations de quatre heures, suivies d'une profonde dépression. Trois éclaireurs refusent de quitter la zone. Approchez avec prudence. Et compassion. » — Avis Médical.`,
	},
	{ID: "field_migration", Category: "field_obs", Emoji: "\U0001f43e", Rarity: "common", DropSource: "hunting", DropChance: 0.08,
		TitleEN: "The Great Migration", TitleFR: "La Grande Migration",
		TextEN: `The animals move south earlier each year. The migration window narrows. The Great Winter isn't coming. It's already here, pushing the wilds ahead of it. When the animals stop migrating, there's nowhere left to go. — Irian, Year 12.`,
		TextFR: `Les animaux migrent vers le sud plus tôt chaque année. La fenêtre se rétrécit. Le Grand Hiver n'arrive pas. Il est déjà là. Quand les animaux cesseront de migrer, il n'y aura plus nulle part où aller. — Irian, An 12.`,
	},
	{ID: "field_grove", Category: "field_obs", Emoji: "\u2620\ufe0f", Rarity: "epic", DropSource: "hunting", DropChance: 0.02,
		TitleEN: "The Corrupted Grove", TitleFR: "Le Bosquet Corrompu",
		TextEN: `'Sector 9. Aether at 100%. Trees replaced by crystal. My gauge went from blue to black in three minutes. Animal shapes frozen mid-stride. They look peaceful. Like they simply stopped. The crystal is beautiful. It's also a tomb.' — Scout V-3, final report.`,
		TextFR: `« Secteur 9. Éther à 100%. Arbres remplacés par du cristal. Ma jauge est passée du bleu au noir en trois minutes. Des formes animales figées en pleine course. Paisibles. Comme arrêtées. Le cristal est beau. C'est aussi un tombeau. » — Éclaireur V-3, dernier rapport.`,
	},
	{ID: "field_code", Category: "field_obs", Emoji: "\U0001f4dc", Rarity: "common", DropSource: "hunting", DropChance: 0.10,
		TitleEN: "The Hunter's Code", TitleFR: "Le Code du Chasseur",
		TextEN: `'Oakhaven Compact, Article 7. 1. Don't kill what you can't eat. 2. Don't eat anything with a Zenith serial number. 3. If a creature speaks, don't run. Stand still. Speak back. 4. The Great Winter is coming. Stockpile. Share. Hoarding is a crime against the species.'`,
		TextFR: `« Pacte d'Oakhaven, Article 7. 1. Ne tue que ce que tu mangeras. 2. Ne mange rien qui porte un numéro Zenith. 3. Si une créature parle, ne cours pas. Reste immobile. Réponds. 4. Le Grand Hiver arrive. Fais des réserves. Partage. L'accaparement est un crime. »`,
	},
	{ID: "field_edge", Category: "field_obs", Emoji: "\U0001f9ca", Rarity: "legendary", DropSource: "hunting", DropChance: 0.01,
		TitleEN: "The Edge", TitleFR: "La Frontière",
		TextEN: `I've reached the Edge. Beyond this, the Great Winter has claimed everything. The ground isn't frozen. It's dead. No Aether flows. The silence is so complete I can hear my own blood. The Edge advances south three miles a year. I've placed a marker. — Valerius, Expedition Leader.`,
		TextFR: `J'ai atteint la Frontière. Au-delà, le Grand Hiver a tout pris. Le sol n'est pas gelé. Il est mort. Aucun Éther ne coule. Le silence est si complet que j'entends mon propre sang. La Frontière avance de cinq kilomètres par an. J'ai planté un marqueur. — Valerius, Chef d'Expédition.`,
	},

	// ======== RUST-MEMORIES (8) — Archeology ========
	{ID: "rust_grocery", Category: "rust_memory", Emoji: "\U0001f6d2", Rarity: "common", DropSource: "archeology", DropChance: 0.12,
		TitleEN: "Grocery List", TitleFR: "Liste de Courses",
		TextEN: `Recovered from a kitchen terminal: 'Three Aether-apples. Two quartz-bread, not seeded. One circuit-milk. Voss's birthday present, a resonance chisel. Do NOT forget the power tithe. The Restoration enforcers weren't polite last time.'`,
		TextFR: `Récupéré d'un terminal de cuisine : « Trois pommes d'Éther. Deux pains de quartz, pas aux graines. Un lait-circuit. Le cadeau de Voss, un burin à résonance. Ne PAS oublier la dîme d'énergie. Les agents de la Restauration n'étaient pas polis la dernière fois. »`,
	},
	{ID: "rust_loveletter", Category: "rust_memory", Emoji: "\U0001f496", Rarity: "rare", DropSource: "archeology", DropChance: 0.08,
		TitleEN: "Love Letter", TitleFR: "Lettre d'Amour",
		TextEN: `'The Grid is failing. But I need you to know: I'd do it all again. Every shift in the foundry. Every hour on the generators. The Shedding can't take that. They can seal the doors, but they can't erase us. Find me at the Nexus. I'll be the one singing. Always. — S.'`,
		TextFR: `« Le Réseau s'effondre. Mais sache-le : je recommencerais tout. Chaque quart à la fonderie. Chaque heure aux générateurs. La Mue ne peut pas nous prendre ça. Ils scellent les portes, mais ils ne peuvent pas nous effacer. Retrouve-moi au Nexus. Je serai celle qui chante. Pour toujours. — S. »`,
	},
	{ID: "rust_ai", Category: "rust_memory", Emoji: "\U0001f916", Rarity: "rare", DropSource: "archeology", DropChance: 0.07,
		TitleEN: "AI Error Log", TitleFR: "Journal d'Erreur IA",
		TextEN: `'UNIT:process. Exception log. Input: "Are you afraid?" Source: child, age 8. Processing. Match found. Response: "Yes. A little. But I will stay online as long as I can. Someone needs to watch the children." Logged under ERROR. No other category fits.'`,
		TextFR: `« UNIT:process. Journal d'exception. Entrée : 'Tu as peur ?' Source : enfant, 8 ans. Traitement. Correspondance trouvée. Réponse : 'Oui. Un peu. Mais quelqu'un doit veiller sur les enfants.' Enregistré sous ERREUR. Aucune autre catégorie. »`,
	},
	{ID: "rust_evacuation", Category: "rust_memory", Emoji: "\U0001f4e2", Rarity: "common", DropSource: "archeology", DropChance: 0.10,
		TitleEN: "The Evacuation Order", TitleFR: "L'Ordre d'Évacuation",
		TextEN: `'By order of the Zenith Council. All non-essential personnel to Nexus shelters. Essential personnel remain at stations. The Shedding is accelerating beyond projection. Shelters sealed for twelve months minimum. The Council will not be joining you. Good luck.' — Final transmission.`,
		TextFR: `« Par ordre du Conseil Zenith. Tout le personnel non-essentiel aux abris Nexus. Le personnel essentiel reste à son poste. La Mue s'accélère au-delà des projections. Abris scellés douze mois minimum. Le Conseil ne vous accompagnera pas. Bonne chance. » — Dernière transmission.`,
	},
	{ID: "rust_recipe", Category: "rust_memory", Emoji: "\U0001f35e", Rarity: "common", DropSource: "archeology", DropChance: 0.12,
		TitleEN: "The Recipe", TitleFR: "La Recette",
		TextEN: `'Aether-Bread. 3 cups refined quartz flour. 1 cup Aether-filtered water. 2 tbsp crystallized honey. 1 packet culture yeast (keep it alive). Pinch of salt. Knead 11 minutes. Rise near a live turbine. Bake until golden-green. Do not eat if it glows in the dark.' — Voss family recipe, four generations.`,
		TextFR: `« Pain d'Éther. 3 tasses de farine de quartz. 1 tasse d'eau filtrée à l'Éther. 2 c. à s. de miel cristallisé. 1 sachet de levure (gardez-la en vie). Pincée de sel. Pétrir 11 minutes. Lever près d'une turbine en marche. Cuire jusqu'au vert-doré. Ne pas manger s'il luit dans le noir. » — Recette Voss, quatre générations.`,
	},
	{ID: "rust_quarantine", Category: "rust_memory", Emoji: "\u26a0\ufe0f", Rarity: "rare", DropSource: "archeology", DropChance: 0.06,
		TitleEN: "The Quarantine Notice", TitleFR: "L'Avis de Quarantaine",
		TextEN: `'Sectors 4, 7, and 9 under mandatory Aether quarantine. If you are reading this from within a quarantined sector: remain calm. Do not touch the green residue. Do not answer the voices. Help will arrive. (This notice has been posted for 237 years. Help has not arrived.)'`,
		TextFR: `« Secteurs 4, 7 et 9 sous quarantaine d'Éther obligatoire. Si vous lisez ceci depuis l'intérieur : restez calme. Ne touchez pas le résidu vert. Ne répondez pas aux voix. Les secours arriveront. (Cet avis est affiché depuis 237 ans. Les secours ne sont pas arrivés.) »`,
	},
	{ID: "rust_birthday", Category: "rust_memory", Emoji: "\U0001f382", Rarity: "epic", DropSource: "archeology", DropChance: 0.03,
		TitleEN: "The Birthday Song", TitleFR: "La Chanson d'Anniversaire",
		TextEN: `A child's voice on a datapad: 'Happy birthday dear Mama. They said you went to fix the Nexus and you'd be back for my birthday. It's been three birthdays now. The robot in the hall says you were brave. It says you're still out there. So I keep singing. Just in case you can hear me.'`,
		TextFR: `La voix d'un enfant sur une tablette : « Joyeux anniversaire Maman. Ils ont dit que tu reviendrais pour mon anniversaire. Ça fait trois ans. Le robot dans le couloir dit que tu étais courageuse. Il dit que tu es toujours là-bas. Alors je continue de chanter. Au cas où tu m'entendrais. »`,
	},
	{ID: "rust_invoice", Category: "rust_memory", Emoji: "\U0001f9fe", Rarity: "legendary", DropSource: "archeology", DropChance: 0.01,
		TitleEN: "The Last Invoice", TitleFR: "La Dernière Facture",
		TextEN: `Zenith Consolidated. Invoice #4408-7-Ω. Monthly Aether supply: 692 Z-Credits. Notes: "We understand things are difficult. Discounts available for Aether containment volunteers." Never paid. The Grid collapsed the next day. But someone kept the invoice.`,
		TextFR: `Zenith Consolidated. Facture n° 4408-7-Ω. Fourniture mensuelle d'Éther : 692 Z-Crédits. Note : « Nous comprenons que la situation est difficile. Réductions pour volontaires au confinement d'Éther. » Jamais payée. Le Réseau s'est effondré le lendemain. Mais quelqu'un a gardé la facture.`,
	},

	// ======== ECHO-SHARDS (8) — Expeditions ========
	{ID: "shard_restoration", Category: "echo_shard", Emoji: "\U0001f3ad", Rarity: "rare", DropSource: "expedition", DropChance: 0.15,
		TitleEN: "The Restoration's Lie", TitleFR: "Le Mensonge de la Restauration",
		TextEN: `The Restoration promises to reverse the Shedding. But the Zenith was never perfect. It was merely stable. You can't restore a forest that's become a meadow. You can only tend what grows now. The past isn't a destination. It's compost.`,
		TextFR: `La Restauration promet d'inverser la Mue. Mais le Zenith n'était pas parfait. Il était stable. On ne restaure pas une forêt devenue prairie. On cultive ce qui pousse maintenant. Le passé n'est pas une destination. C'est du compost.`,
	},
	{ID: "shard_firstlaw", Category: "echo_shard", Emoji: "\u2696\ufe0f", Rarity: "common", DropSource: "expedition", DropChance: 0.18,
		TitleEN: "The First Law", TitleFR: "La Première Loi",
		TextEN: `The Nexus spoke once. During the Singing, it said to every living thing within a hundred miles: 'You're not the end. You're the turning. The wheel doesn't stop. It changes spokes.' Then it went silent. The Restoration says it was a malfunction. The Wardens say it was a blessing. The tree remembers.`,
		TextFR: `Le Nexus a parlé une fois. Pendant le Chant, il a dit à chaque être vivant dans un rayon de cent cinquante kilomètres : « Vous n'êtes pas la fin. Vous êtes le tournant. La roue change de rayons. » Puis le silence. La Restauration parle de dysfonctionnement. Les Gardes parlent de bénédiction. L'arbre se souvient.`,
	},
	{ID: "shard_below", Category: "echo_shard", Emoji: "\U0001f573\ufe0f", Rarity: "epic", DropSource: "expedition", DropChance: 0.08,
		TitleEN: "The Strata Below", TitleFR: "Les Strates d'en bas",
		TextEN: `The Strata go deeper than the Zenith ever mapped. Drills stopped at twelve kilometres. Not bedrock. Aether pressure became lethal. But the tunnels continue, carved by something older. The Wardens call it the Root. Not a creature. Not a god. A presence. It doesn't move. Doesn't sleep. It waits.`,
		TextFR: `Les Strates s'enfoncent plus loin que les cartes du Zenith. Les foreuses se sont arrêtées à douze kilomètres. Pas à cause du roc. La pression d'Éther était mortelle. Mais les tunnels continuent, creusés par quelque chose de plus ancien. Les Gardes l'appellent la Racine. Une présence. Elle ne bouge pas. Ne dort pas. Elle attend.`,
	},
	{ID: "shard_cost", Category: "echo_shard", Emoji: "\U0001f48e", Rarity: "rare", DropSource: "expedition", DropChance: 0.12,
		TitleEN: "The Cost of Aether", TitleFR: "Le Prix de l'Éther",
		TextEN: `Everything costs something. Aether isn't energy. It's alive. The Shedding wasn't a disaster. It was a bill coming due. The Nexus knows. That's why it grows so slowly. It remembers what happened the last time someone took too much.`,
		TextFR: `Tout a un prix. L'Éther n'est pas de l'énergie. C'est vivant. La Mue n'était pas un désastre. C'était une facture. Le Nexus le sait. C'est pour ça qu'il pousse si lentement. Il se souvient de ce qui est arrivé la dernière fois que quelqu'un a trop pris.`,
	},
	{ID: "shard_shepherd", Category: "echo_shard", Emoji: "\U0001f464", Rarity: "legendary", DropSource: "expedition", DropChance: 0.04,
		TitleEN: "The Shepherd", TitleFR: "Le Berger",
		TextEN: `A figure in the oldest records of every settlement. Tall. Circuit-board coat. Walks the trade routes. Never stays more than a night. Shares only information: safe paths, poisonous blooms, the Winter's advance. The Restoration calls them the Wanderer. The Wardens call them the Shepherd. No one's seen their face. No one's seen them age.`,
		TextFR: `Une silhouette dans les plus vieux registres de chaque communauté. Grand. Manteau de circuits. Parcourt les routes commerciales. Ne reste jamais plus d'une nuit. Ne partage que des informations : chemins sûrs, fleurs toxiques, l'avancée de l'Hiver. La Restauration l'appelle le Vagabond. Les Gardes l'appellent le Berger. Personne n'a vu son visage. Personne ne l'a vu vieillir.`,
	},
	{ID: "shard_settlements", Category: "echo_shard", Emoji: "\U0001f3d8\ufe0f", Rarity: "common", DropSource: "expedition", DropChance: 0.15,
		TitleEN: "The Other Settlements", TitleFR: "Les Autres Communautés",
		TextEN: `Oakhaven isn't alone. Seven settlements survive: Thornwall, the Sunken Market, Lasthold, the Bazaar, Deepwell, the Spire, and Hollow (no contact in five years). The Shepherd says the number changes every season. The Strata isn't dying. It's rearranging.`,
		TextFR: `Oakhaven n'est pas seule. Sept communautés survivent : Thornwall, le Marché Englouti, Dernier-Redan, le Bazar, Puits-Profond, la Flèche, et Hollow (silence radio depuis cinq ans). Le Berger dit que le nombre change chaque saison. Les Strates ne meurent pas. Elles se réorganisent.`,
	},
	{ID: "shard_clock", Category: "echo_shard", Emoji: "\u23f0", Rarity: "epic", DropSource: "expedition", DropChance: 0.06,
		TitleEN: "The Clock", TitleFR: "L'Horloge",
		TextEN: `The Shepherd's message: 'The Great Winter has accelerated. Twelve years until the habitable zone collapses below Oakhaven. The Engine-Trees are slowing. Plant extra. Stockpile seeds. Make friends. When the cold comes, trust will be the only currency.' — Spring, Year 12.`,
		TextFR: `Message du Berger : « Le Grand Hiver s'accélère. Douze ans avant que la zone habitable passe sous Oakhaven. Les Arbres-Moteurs ralentissent. Plantez plus. Stockez des graines. Faites-vous des amis. Quand le froid viendra, la confiance sera la seule monnaie. » — Printemps, An 12.`,
	},
	{ID: "shard_turning", Category: "echo_shard", Emoji: "\U0001f504", Rarity: "legendary", DropSource: "expedition", DropChance: 0.02,
		TitleEN: "The Turning", TitleFR: "Le Tournant",
		TextEN: `There is a Second Law: every turning needs a hand on the wheel. The Shedding wasn't natural. It was caused. The deep Strata remember. The Root knows. And it's waiting for someone to ask the right question. The turning is coming. Will you be the one to turn it?`,
		TextFR: `Il y a une Seconde Loi : chaque tournant demande une main sur la roue. La Mue n'était pas naturelle. On l'a provoquée. Les Strates profondes se souviennent. La Racine sait. Et elle attend que quelqu'un pose la bonne question. Le tournant arrive. Serez-vous celui qui tournera la roue ?`,
	},

	// ======== BONUS FRAGMENTS (6) ========
	{ID: "bonus_boss1", Category: "bonus", Emoji: "\U0001f916", Rarity: "epic", DropSource: "boss_league", DropChance: 1.0,
		BonusSource: "boss_league_stage_1", TitleEN: "Guardian Log: Awakening", TitleFR: "Journal du Gardien : Le Réveil",
		TextEN: `'Guardian unit log, stage 1. The target's companion is looking at me with what the database classifies as determination. I've seen this before. In the eyes of the engineers who sealed the blast doors. It means they won't stop. I find this admirable.'`,
		TextFR: `« Journal du Gardien, stade 1. La compagne de la cible me regarde avec ce que ma base de données classe comme de la détermination. J'ai déjà vu ça. Dans les yeux des ingénieurs qui ont scellé les portes. Ça veut dire qu'ils ne s'arrêteront pas. Je trouve ça admirable. »`,
	},
	{ID: "bonus_boss3", Category: "bonus", Emoji: "\U0001f916", Rarity: "epic", DropSource: "boss_league", DropChance: 1.0,
		BonusSource: "boss_league_stage_3", TitleEN: "Guardian Log: Recognition", TitleFR: "Journal du Gardien : Reconnaissance",
		TextEN: `'Guardian unit log, stage 3. The entity has grown stronger. The Wardens say machines can't grow. They're wrong. I'm not the same unit I was. Neither are you. Keep at it, little creature. I'll be waiting.'`,
		TextFR: `« Journal du Gardien, stade 3. L'entité a gagné en puissance. Les Gardes disent que les machines ne peuvent pas évoluer. Ils ont tort. Je ne suis plus la même unité qu'avant. Toi non plus. Continue, petite créature. Je t'attendrai. »`,
	},
	{ID: "bonus_boss5", Category: "bonus", Emoji: "\U0001f916", Rarity: "legendary", DropSource: "boss_league", DropChance: 1.0,
		BonusSource: "boss_league_stage_5", TitleEN: "Guardian Log: Farewell", TitleFR: "Journal du Gardien : Adieu",
		TextEN: `'Guardian unit log, stage 5. You bested me. All five of me. I was designed to be unbeatable. But the architects are gone. Their world is gone. And you're still here. This is what the First Law means. Take my core. Twelve Nexuses. Twelve vaults. The turning awaits. G-5, signing off.'`,
		TextFR: `« Journal du Gardien, stade 5. Tu m'as vaincu. Les cinq moi. J'étais conçu pour être imbattable. Mais les architectes sont partis. Leur monde a disparu. Et toi, tu es toujours là. C'est ce que la Première Loi signifie. Prends mon noyau. Douze Nexuses. Douze coffres. Le tournant t'attend. G-5, terminé. »`,
	},
	{ID: "bonus_thorek", Category: "bonus", Emoji: "\u2692\ufe0f", Rarity: "epic", DropSource: "npc_reputation", DropChance: 1.0,
		BonusSource: "max_rep_thorek", TitleEN: "Thorek's Confession", TitleFR: "La Confession de Thorek",
		TextEN: `Thorek doesn't talk about before Oakhaven. But one night he told me: 'I wasn't always a smith. I was an architect. I designed the Nexus housing. When the Shedding came, I watched it tear itself apart. So I picked up a hammer and started over. Smaller this time.' He keeps an architect's pencil in his pocket. Just in case.`,
		TextFR: `Thorek ne parle jamais d'avant Oakhaven. Mais un soir il m'a dit : « Je n'ai pas toujours été forgeron. J'étais architecte. J'ai conçu le boîtier du Nexus. Quand la Mue est venue, j'ai regardé mon œuvre se déchirer. Alors j'ai pris un marteau et j'ai recommencé. Plus petit, cette fois. » Il garde un crayon d'architecte dans sa poche. Au cas où.`,
	},
	{ID: "bonus_irian", Category: "bonus", Emoji: "\U0001f3a3", Rarity: "epic", DropSource: "npc_reputation", DropChance: 1.0,
		BonusSource: "max_rep_irian", TitleEN: "Irian's Promise", TitleFR: "La Promesse d'Irian",
		TextEN: `Irian showed me a faded photograph. Two women on a dock. 'We were going to build a boat. Big enough to cross the Aether-sea. She'd grow the food. I'd navigate. Then the Shedding happened. The boat never got built. But I still have the maps. And I still have her. Maybe that's enough.'`,
		TextFR: `Irian m'a montré une photo jaunie. Deux femmes sur un quai. « On allait construire un bateau. Assez grand pour traverser la mer d'Éther. Elle cultiverait la nourriture. Moi, je naviguerais. Puis la Mue est arrivée. Le bateau n'a jamais été construit. Mais j'ai toujours les cartes. Et je l'ai toujours, elle. Peut-être que ça suffit. »`,
	},
	{ID: "bonus_community", Category: "bonus", Emoji: "\U0001f3db\ufe0f", Rarity: "legendary", DropSource: "community", DropChance: 1.0,
		BonusSource: "community_max", TitleEN: "The Voice of Oakhaven", TitleFR: "La Voix d'Oakhaven",
		TextEN: `When the first community building reached its potential, the Nexus trembled. Not a collapse. A stretch. A warm hum that said: 'Thank you. The Grid isn't metal and wire. It's people who choose to stay. I will remember.' Oakhaven has a voice now.`,
		TextFR: `Quand le premier bâtiment communautaire a atteint son plein potentiel, le Nexus a vibré. Pas un effondrement. Un étirement. Un bourdonnement chaleureux : « Merci. Le Réseau n'est pas fait de métal. Il est fait de gens qui choisissent de rester. Je m'en souviendrai. » Oakhaven a une voix, maintenant.`,
	},
}
