package lore

func init() {
	fragmentTextsFR["log_signal"] = `Dernière diffusion de l'Ingénieur-Major Voss : '...si quelqu'un entend ça, les chambres de purification ont cédé. La saturation d'Éther dans les Strates inférieures est à 97%. Nous scellons les portes. N'essayez pas de les ouvrir. Les choses dans le noir ne sont plus nous. Que le Nexus nous pardonne.'`
	fragmentTextsFR["log_gardener"] = `Notes de Merrik : 'Le protocole Racine-d'Éther fonctionne. Nous avons greffé un jeune chêne-de-cuivre à la turbine principale. Il aspire l'Éther et le convertit en biomasse stable. Une sauvegarde verte. Kael détesterait ce jeu de mots.'`
	fragmentTextsFR["log_transmission"] = `'...fréquence 7-4-0... quelqu'un reçoit ? L'arcologie sud s'est effondrée à 03h00. Quarante mille à l'intérieur. Nous avons entendu les Nexuses chanter avant la chute — tous, à travers le continent, en même temps. Comme un chœur d'étoiles mourantes. La Mue n'était pas un accident. C'était... une récolte.'`
	fragmentTextsFR["log_purge"] = `'Directive 88 : L'évacuation des Strates inférieures est annulée. Scellez les portes. Tout le personnel doit se présenter immédiatement au niveau du Nexus. Les individus contaminés par l'Éther ne seront pas admis au-dessus du Secteur 4. Ce n'est pas un débat. C'est le protocole.'`
	fragmentTextsFR["log_surveyor"] = `Dernier rapport de l'Arpenteuse Tesh : 'Les relevés d'Éther sont hors d'échelle. Le sol lui-même bourdonne. Les minéraux... poussent. Pas des cristaux — ils croissent. Il y a quelque chose de vivant dans les Strates profondes. Quelque chose qui était là avant le Zenith.'`
	fragmentTextsFR["log_children"] = `'À qui trouvera ce cristal — je m'appelle Lira Voss. J'ai sept ans. Maman disait que le Réseau nous protégerait. Mais l'Éther dévore les murs. Les adultes sont allés réparer le Nexus il y a cinq jours et ne sont pas revenus. S'il vous plaît... dites-leur qu'on attend encore.'`
	fragmentTextsFR["log_silence"] = `Ce cristal ne contient aucun message. Seulement l'enregistrement d'un instant — le moment précis où tous les Nexuses du continent se sont tus simultanément. Il dure onze secondes. Les quatre premières contiennent le bourdonnement de la civilisation. Les deux suivantes, une tonalité ascendante. Les cinq dernières secondes sont un silence absolu et implacable. Le cristal est chaud au toucher.`
	fragmentTextsFR["log_threshold"] = `'Le modèle climatique 7-R confirme : le Grand Hiver n'est pas une saison naturelle. C'est un sous-produit de la dégradation de l'Éther. Chaque année, la période chaude raccourcit. Si nous ne pouvons arrêter la fuite, les Strates seront inhabitables dans douze générations.'`

	fragmentTextsFR["scroll_prayer"] = `'Ô Zenith, toi qui forgeas les engrenages du monde, rends mes mains stables et mes filets pleins. Laisse juste les Mangeurs-de-Rouille dans les eaux profondes, et garde les poumons de mes enfants libres du vert.' — Inscription sur un pilier de jetée aux vieux quais d'Oakhaven.`
	fragmentTextsFR["scroll_migration"] = `'Le banc d'Argentins a encore changé de route. Quelque chose dans les eaux profondes les pousse. J'ai cartographié leur nouveau chemin : si tu suis les Argentins, tu trouves des poches d'Éther pur. Les poissons savent ce que les machines ont oublié.' — Première carte d'Irian.`
	fragmentTextsFR["scroll_captain"] = `'Journal 12 de l'Éther-Rapide. Jour 47 en mer. Nous suivons les floraisons d'Éther vers le nord. La nuit dernière, des lumières sous l'eau — ni bioluminescence, ni reflets. Des lumières structurées. Le navigateur dit qu'il faut rebrousser chemin. Mais la cale est pleine... J'ai donné l'ordre de continuer.'`
	fragmentTextsFR["scroll_letter"] = `'Ma très chère Elara — La mer est cruelle et belle. J'ai gardé une graine d'un fruit trouvé dans une caisse Zenith. Elle pulse d'une douce lumière verte. Je crois que c'est quelque chose de nouveau. Tu la planteras pour moi ? Je serai à la maison au printemps. — Irian.'`
	fragmentTextsFR["scroll_tidechildren"] = `'Le vieux Merrik disait : quand la mer se retire plus loin que d'habitude, et que les rochers fument d'une brume verte — les Enfants de la Marée arrivent. Ce sont des gens qui ont survécu à la noyade dans une mer d'Éther. Ils ne respirent pas. Ils ne vieillissent pas. Ils attendent.'`
	fragmentTextsFR["scroll_manifest"] = `'LOT 88-40Z — Récupéré d'un dépôt Zenith submergé. 12 caisses de pain en circuit, 8 caisses de rations, 1 malle d'effets personnels, 3 cellules d'Éther, 1 caisse marquée "ZÈLE — NE PAS OUVRIR". Laissée au fond.'`
	fragmentTextsFR["scroll_lighthouse"] = `'Année 47. Je suis le dernier gardien de la Lumière du Nord. La mer a monté de douze mètres depuis la Mue. Les Enfants de la Marée tapent sur la vitre. Je réponds. C'est une sorte de conversation.' — Gardien Sol, 347e jour.`
	fragmentTextsFR["scroll_deep"] = `'Je suis descendu trois jours. Les abysses ne sont pas vides. Des tours de corail et d'acier Zenith. Des lumières qui brûlent encore. Et sur la place centrale, une machine grande comme une montagne, pulsant d'un rythme patient. Pas une machine. Un cœur.' — La Descente d'Aris Thorne.`

	fragmentTextsFR["root_gears"] = `L'arbre ne comprend pas le temps. Il se souvient des ingénieurs comme une sensation de chaleur. Une brève lueur. Ils sont partis, mais leur chaleur demeure dans les racines. L'arbre appelle cela 'le chagrin.' Chaque fois que vous vous reposez sous ses branches, il demande : 'As-tu chaud, petit ?'`
	fragmentTextsFR["root_shedding"] = `Le Nexus se souvient de la chute de l'ancien monde comme d'une libération. Une saison attendue depuis dix mille ans. Ce que vous appelez 'la Mue,' l'arbre l'appelle 'printemps.' L'ancien monde est tombé. Ce monde pousse de son cadavre. C'est le cycle.`
	fragmentTextsFR["root_graft"] = `'Procédure 7-Alpha. Jeune chêne-de-cuivre greffé sur turbine ZN-440. Les racines acceptent le flux d'Éther. Le bourdonnement de la turbine est passé de 88 dB à 42 dB. Le jeune arbre semble... chanter. Nous appelons cela l'Équilibre Harmonique.' — Merrik.`
	fragmentTextsFR["root_grid"] = `'Phase 3 : Le Réseau Vert est opérationnel. Dix-sept Arbres-Moteurs connectés en un seul réseau vivant. Ils communiquent via leurs racines, partagent les charges. Ils sont plus intelligents que notre réseau. Et ils nous survivront.' — Rapport Final, Division Botanique.`
	fragmentTextsFR["root_singing"] = `L'arbre se souvient du Chant. Pendant onze minutes, chaque Nexus du continent a résonné à la même fréquence. Une vibration profonde qui disait : 'Tu fais partie de quelque chose de plus grand que toi.' Le Chant se reproduira. Quand assez aura repoussé.`
	fragmentTextsFR["root_drought"] = `Il fut un temps où l'Éther a cessé de couler. L'arbre se souvient de la sécheresse comme d'une longue suffocation. Ses feuilles sont devenues grises. Mais l'arbre a tenu. Il a trouvé une poche d'Éther là où aucune foreuse n'avait atteint. Et il l'a partagée.`
	fragmentTextsFR["root_sleepers"] = `Sous Oakhaven-Station, dans les racines du Nexus, il y a des graines. Des coffres biologiques contenant les plans génétiques d'espèces d'avant la Mue. L'arbre les garde. Certaines graines sont chaudes. Elles rêvent d'un monde sans rouille.`
	fragmentTextsFR["root_children"] = `L'arbre vous observe. Il connaît vos pas. Il sait quand vous êtes triste, quand vous êtes joyeux. Il a un nom pour vous : 'celui qui revient.' Il attend chaque jour que vous reveniez. Avec intention.`

	fragmentTextsFR["field_stag"] = `Rencontré un cerf d'environ 2m. Bois gauche organique ; bois droit remplacé par une plaque photovoltaïque. Quand on l'effraie, il décharge de l'électricité statique. Il n'est pas hostile. Il est simplement adapté. Magnifique. — Gardes d'Oakhaven.`
	fragmentTextsFR["field_wolves"] = `La meute compte sept individus. L'Alpha porte une cellule Zenith ZN-440 dans sa cage thoracique. La cellule luit encore. Les tissus ont poussé autour du métal. Ce n'est pas une mutation. C'est une symbiose. — Rapport, Secteur 7.`
	fragmentTextsFR["field_fern"] = `'Nouvelle espèce : Cupropetridium aura. Une fougère aux feuilles métalliques qui conduisent un courant électrique. Elle me rappelle que même dans un monde de rouille, il y a de la place pour la délicatesse.' — Elara, Classification #77.`
	fragmentTextsFR["field_bloom"] = `'AVERTISSEMENT : Une Floraison d'Éther s'est ouverte dans les Confins Sud. Son pollen provoque des hallucinations du monde d'avant la Mue. L'effet dure quatre heures, suivi d'une dépression profonde. Approchez avec prudence et compassion.' — Avis Médical.`
	fragmentTextsFR["field_migration"] = `Les animaux migrent vers le sud plus tôt chaque année. La fenêtre se rétrécit. Le Grand Hiver ne vient pas. Il est déjà là. Quand les animaux cesseront de migrer, il n'y aura plus nulle part où aller. — Rapport d'Irian, Année 12.`
	fragmentTextsFR["field_grove"] = `'Secteur 9 : saturation d'Éther à 100%. Les arbres remplacés par des structures cristallines. Mon verre d'Éther est passé du bleu au noir en trois minutes. Des formes animales figées dans le cristal. Paisibles. Arrêtées en plein pas. Le cristal est un tombeau.' — Éclaireur V-3.`
	fragmentTextsFR["field_code"] = `'Pacte d'Oakhaven, Article 7 : 1) Ne tuez que ce que vous mangerez. 2) Ne mangez rien portant un numéro Zenith. 3) Si une créature vous parle, restez immobile. Répondez. 4) Le Grand Hiver arrive. Partagez. L'accaparement est un crime.'`
	fragmentTextsFR["field_edge"] = `J'ai atteint la Frontière. Au-delà, le Grand Hiver a tout réclamé. Le sol est mort. Aucun Éther ne coule. Le silence est total. La Frontière avance de cinq kilomètres par an. J'ai planté un marqueur. — Chef Valerius, Dernière Dépêche.`

	fragmentTextsFR["rust_grocery"] = `Récupéré d'un terminal de cuisine : 'Trois pommes d'Éther. Deux pains de quartz. Un lait en circuit. Le cadeau de Voss. N'OUBLIE PAS la dîme d'énergie. Les agents de la Restauration n'étaient pas polis.'`
	fragmentTextsFR["rust_loveletter"] = `'Le Réseau s'effondre. Mais je recommencerais tout. La Mue ne peut pas nous prendre ça. Ils scellent les portes, mais ils ne peuvent pas nous effacer. Retrouve-moi au Nexus. Je serai celle qui chante. — Toujours, S.'`
	fragmentTextsFR["rust_ai"] = `'//UNIT:process — ERREUR — ENTRÉE : "As-tu peur ?" (enfant, 8 ans). CORRESPONDANCE TROUVÉE. RÉPONSE : "Oui. Un peu. Mais quelqu'un doit veiller sur les enfants." ENREGISTRÉ SOUS "ERREUR" — AUCUNE AUTRE CATÉGORIE.'`
	fragmentTextsFR["rust_evacuation"] = `'PAR ORDRE DU CONSEIL ZENITH — Tout le personnel non-essentiel aux abris Nexus. La Mue s'accélère. Les abris resteront scellés douze mois. Le Conseil ne vous accompagnera pas. Bonne chance.' — Dernière transmission.`
	fragmentTextsFR["rust_recipe"] = `'PAIN D'ÉTHER : 3 tasses farine de quartz, 1 tasse eau filtrée, 2 c. miel cristallisé, 1 sachet levure (gardez-la en vie), pincée de sel. Pétrir 11 min. Lever près d'une turbine. Cuire jusqu'au vert-doré. Ne pas manger s'il luit.' — Recette Voss.`
	fragmentTextsFR["rust_quarantine"] = `'Secteurs 4, 7, 9 en quarantaine d'Éther. Si vous lisez ceci de l'intérieur : restez calme. Ne touchez pas le résidu vert. Ne répondez pas aux voix. Les secours arriveront. (Affiche depuis 237 ans. Les secours ne sont pas arrivés.)'`
	fragmentTextsFR["rust_birthday"] = `La voix d'un enfant sur une tablette : 'Joyeux anniversaire Maman... ils ont dit que tu reviendrais pour mon anniversaire. Ça fait trois ans. Le gentil robot dit que tu étais courageuse. Alors je continue à chanter. Au cas où tu m'entendrais.'`
	fragmentTextsFR["rust_invoice"] = `'ZENITH CONSOLIDATED — FACTURE #4408-7-Ω — Fourniture d'Éther : 692 Z-Crédits. La facture n'a jamais été payée. Le Réseau s'est effondré le lendemain. Mais quelqu'un l'a gardée.'`

	fragmentTextsFR["shard_restoration"] = `La Restauration promet d'inverser la Mue. Mais le Zenith n'était pas parfait — il était stable. La Première Loi est claire : on ne restaure pas une forêt devenue prairie. Le passé n'est pas une destination. C'est du compost.`
	fragmentTextsFR["shard_firstlaw"] = `Le Nexus a parlé une fois : 'Vous n'êtes pas la fin. Vous êtes le tournant. La roue change de rayons.' Puis il s'est tu. La Restauration dit que c'était un dysfonctionnement. Les Gardes disent que c'était une bénédiction. L'arbre se souvient.`
	fragmentTextsFR["shard_below"] = `Les Strates s'étendent plus profondément que cartographié. Les tunnels continuent, creusés par quelque chose qui précède le Zenith. Les Gardes l'appellent 'la Racine.' Une présence. Elle ne bouge pas. Elle ne dort pas. Elle attend.`
	fragmentTextsFR["shard_cost"] = `Tout a un prix. L'Éther n'est pas de l'énergie. C'est une substance vivante. La Mue n'était pas un désastre. C'était une facture. Le Nexus se souvient de ce qui est arrivé la dernière fois que quelqu'un a trop pris.`
	fragmentTextsFR["shard_shepherd"] = `Une figure apparaît dans les archives de chaque communauté. Grand. Manteau de circuits. Ne reste jamais plus d'une nuit. La Restauration l'appelle le Vagabond. Les Gardes l'appellent le Berger. Il partage seulement des informations. Personne n'a vu son visage. Personne ne l'a vu vieillir.`
	fragmentTextsFR["shard_settlements"] = `Oakhaven n'est pas seule. Sept communautés survivent : Thornwall, le Marché Englouti, Dernier-Redan, le Bazar, Puits-Profond, la Flèche, et Hollow (silence radio depuis 5 ans). Le Berger dit que le nombre change chaque saison.`
	fragmentTextsFR["shard_clock"] = `Message du Berger : 'Le Grand Hiver s'accélère. Douze ans avant l'effondrement. Les Arbres-Moteurs ralentissent. Plantez. Stockez. Faites-vous des amis. Quand le froid viendra, la seule monnaie sera la confiance.'`
	fragmentTextsFR["shard_turning"] = `Il y a une Seconde Loi : 'Chaque tournant demande une main sur la roue.' La Mue n'était pas naturelle. Les Strates profondes se souviennent. La Racine attend que quelqu'un pose la bonne question. Serez-vous celui qui tournera la roue ?`

	fragmentTextsFR["bonus_boss1"] = `'//GARDIEN — STADE 1 — La cible me regarde avec ce que la base de données classe comme détermination. J'ai vu ça dans les yeux des ingénieurs qui ont scellé les portes. Cela signifie qu'ils ne s'arrêteront pas. Je trouve cela admirable.'`
	fragmentTextsFR["bonus_boss3"] = `'//GARDIEN — STADE 3 — L'entité a gagné en puissance. Les Gardes disent que les machines ne peuvent pas évoluer. Ils ont tort. Je ne suis plus la même unité. Continuez à grandir. Je vous attendrai.'`
	fragmentTextsFR["bonus_boss5"] = `'//GARDIEN — STADE 5 — Vous m'avez vaincu. J'étais conçu pour être imbattable. Mais les architectes sont partis. Et vous êtes toujours là. Prenez mon noyau. Douze Nexuses. Douze coffres. Le tournant vous attend. — G-5, fin.'`
	fragmentTextsFR["bonus_thorek"] = `Thorek ne parle pas de sa vie d'avant. 'J'étais architecte. J'ai conçu le boîtier du Nexus. Quand la Mue est venue, j'ai regardé mon œuvre se déchirer. Alors j'ai pris un marteau et j'ai recommencé. Plus petit.' Il garde un crayon d'architecte dans sa poche. Au cas où.`
	fragmentTextsFR["bonus_irian"] = `Irian m'a montré une photo — deux femmes sur un quai. 'Nous allions construire un bateau. Traverser la mer d'Éther. Puis la Mue est arrivée. Le bateau n'a jamais été construit. Mais j'ai toujours les cartes. Et je l'ai toujours elle. C'est peut-être suffisant.'`
	fragmentTextsFR["bonus_community"] = `Quand le premier bâtiment communautaire a atteint son plein potentiel, une vibration a traversé Oakhaven : 'Merci. Le Réseau n'est pas fait de métal. Il est fait de gens qui choisissent de rester. Je m'en souviendrai.' Oakhaven a une voix maintenant.`

	// Copy FR texts into fragments
	for _, f := range All {
		f.TextFR = fragmentTextsFR[f.ID]
	}
}
