package items

// catalog.go is the single source of truth for every item and balance value
// in the game: the full item catalog, the delve procedural loot tables, the
// affix pool and the equipment sets. Everything else (delve, veil, shop,
// hunt, quests, ...) consumes these definitions by ID and must never redefine
// an item's stats here.
//
// Source marks where an item is primarily obtained. It is informational (used
// for balance review, e.g. `grep "Source:" catalog.go`), not enforced: most
// shop items also drop from hunts, and craftable gear is usually buyable too.

// Item acquisition sources.
const (
	// SourceShop marks items buyable from the daily shop or the vendor.
	SourceShop = "shop"
	// SourceCraft marks items whose primary path is the crafting system
	// (recipes + research unlocks).
	SourceCraft = "craft"
	// SourceQuest marks story / quest / event rewards.
	SourceQuest = "quest"
	// SourceBoss marks boss league rewards.
	SourceBoss = "boss"
	// SourceCriminality marks criminality, bounty-hunter and thieves' guild gear.
	SourceCriminality = "criminality"
	// SourceVeil marks veil raid gear and currency.
	SourceVeil = "veil"
)

// --- Delve procedural loot tables ------------------------------------------
//
// GenerateLoot (internal/service/delve) rolls one base and, above Common
// rarity, optionally a prefix and a suffix to build a named piece of gear.

// DelvePrefix is a quality prefix added to a delve gear base.
type DelvePrefix struct {
	ID      string
	Name    string
	Emoji   string
	StatSTR int
	StatDEX int
	StatINT int
	StatVIT int
	StatLUK int
	MinRar  Rarity
}

// DelveBase is a base piece of gear generated by delves.
type DelveBase struct {
	ID        string
	Name      string
	Emoji     string
	EquipSlot string
	StatSTR   int
	StatDEX   int
	StatINT   int
	StatVIT   int
	StatLUK   int
	MinRar    Rarity
}

// DelveSuffix is a lore-flavoured suffix appended to a delve gear name.
type DelveSuffix struct {
	ID          string
	Name        string
	Description string
	MinRar      Rarity
}

var DelvePrefixes = []DelvePrefix{
	{ID: "flaming", Name: "Flaming", Emoji: "🔥", StatSTR: 3, MinRar: RarityUncommon},
	{ID: "shadow", Name: "Shadow", Emoji: "🌑", StatDEX: 3, MinRar: RarityUncommon},
	{ID: "sturdy", Name: "Sturdy", Emoji: "🛡️", StatVIT: 4, MinRar: RarityCommon},
	{ID: "pristine", Name: "Pristine", Emoji: "✨", StatLUK: 2, StatDEX: 2, MinRar: RarityRare},
	{ID: "frozen", Name: "Frozen", Emoji: "❄️", StatINT: 3, MinRar: RarityUncommon},
	{ID: "stormforged", Name: "Stormforged", Emoji: "⚡", StatSTR: 2, StatDEX: 2, MinRar: RarityRare},
	{ID: "arcane", Name: "Arcane", Emoji: "🔮", StatINT: 5, MinRar: RarityRare},
	{ID: "vampiric", Name: "Vampiric", Emoji: "🩸", StatSTR: 2, StatVIT: 3, MinRar: RarityRare},
	{ID: "blessed", Name: "Blessed", Emoji: "✨", StatLUK: 4, StatVIT: 2, MinRar: RarityEpic},
	{ID: "cursed", Name: "Cursed", Emoji: "💀", StatSTR: 6, MinRar: RarityEpic, StatVIT: -2},
	{ID: "molten", Name: "Molten", Emoji: "🌋", StatSTR: 4, StatINT: 2, MinRar: RarityRare},
	{ID: "venomous", Name: "Venomous", Emoji: "🐍", StatDEX: 4, MinRar: RarityUncommon},
	{ID: "thunderous", Name: "Thunderous", Emoji: "🌩️", StatSTR: 3, StatDEX: 3, MinRar: RarityRare},
	{ID: "soulbound", Name: "Soulbound", Emoji: "💜", StatINT: 3, StatLUK: 3, MinRar: RarityEpic},
	{ID: "radiant", Name: "Radiant", Emoji: "☀️", StatVIT: 3, StatLUK: 3, MinRar: RarityEpic},
	{ID: "ancient", Name: "Ancient", Emoji: "📜", StatINT: 4, StatSTR: 2, MinRar: RarityEpic},
	{ID: "bone", Name: "Bone", Emoji: "🦴", StatSTR: 2, MinRar: RarityCommon},
	{ID: "iron", Name: "Iron", Emoji: "⛓️", StatVIT: 2, MinRar: RarityCommon},
	{ID: "crystal", Name: "Crystal", Emoji: "💎", StatINT: 3, StatLUK: 1, MinRar: RarityUncommon},
	{ID: "wardens", Name: "Warden's", Emoji: "⚜️", StatVIT: 3, StatSTR: 2, MinRar: RarityRare},
}

var DelveBases = []DelveBase{
	{ID: "longsword", Name: "Longsword", Emoji: "⚔️", EquipSlot: "weapon", StatSTR: 2, MinRar: RarityCommon},
	{ID: "dagger", Name: "Dagger", Emoji: "🗡️", EquipSlot: "weapon", StatDEX: 2, MinRar: RarityCommon},
	{ID: "staff", Name: "Staff", Emoji: "🪄", EquipSlot: "weapon", StatINT: 2, MinRar: RarityCommon},
	{ID: "battle_axe", Name: "Battle Axe", Emoji: "🪓", EquipSlot: "weapon", StatSTR: 4, MinRar: RarityUncommon},
	{ID: "wand", Name: "Wand", Emoji: "✨", EquipSlot: "weapon", StatINT: 3, MinRar: RarityUncommon},
	{ID: "shortbow", Name: "Shortbow", Emoji: "🏹", EquipSlot: "weapon", StatDEX: 3, MinRar: RarityUncommon},
	{ID: "leather_cap", Name: "Leather Cap", Emoji: "🧢", EquipSlot: "armor", StatVIT: 1, MinRar: RarityCommon},
	{ID: "chainmail", Name: "Chainmail", Emoji: "🛡️", EquipSlot: "armor", StatVIT: 3, MinRar: RarityUncommon},
	{ID: "robe", Name: "Robe", Emoji: "👘", EquipSlot: "armor", StatINT: 2, MinRar: RarityCommon},
	{ID: "plate_armor", Name: "Plate Armor", Emoji: "🪖", EquipSlot: "armor", StatVIT: 5, StatSTR: 1, MinRar: RarityRare},
	{ID: "amethyst_ring", Name: "Amethyst Ring", Emoji: "💍", EquipSlot: "jewelry", StatINT: 2, StatLUK: 1, MinRar: RarityCommon},
	{ID: "silver_pendant", Name: "Silver Pendant", Emoji: "📿", EquipSlot: "jewelry", StatLUK: 3, MinRar: RarityUncommon},
	{ID: "emerald_brooch", Name: "Emerald Brooch", Emoji: "💚", EquipSlot: "jewelry", StatDEX: 2, StatLUK: 2, MinRar: RarityRare},
	{ID: "ruby_band", Name: "Ruby Band", Emoji: "❤️", EquipSlot: "jewelry", StatSTR: 2, StatVIT: 2, MinRar: RarityRare},
	{ID: "shadow_cloak", Name: "Shadow Cloak", Emoji: "🌙", EquipSlot: "armor", StatDEX: 3, MinRar: RarityUncommon},
	{ID: "bone_amulet", Name: "Bone Amulet", Emoji: "🦷", EquipSlot: "jewelry", StatSTR: 2, StatLUK: 1, MinRar: RarityUncommon},
	{ID: "crystal_shield", Name: "Crystal Shield", Emoji: "💠", EquipSlot: "armor", StatVIT: 4, StatINT: 2, MinRar: RarityRare},
	{ID: "obsidian_dagger", Name: "Obsidian Dagger", Emoji: "🗡️", EquipSlot: "weapon", StatDEX: 4, StatSTR: 1, MinRar: RarityRare},
	{ID: "spirit_mask", Name: "Spirit Mask", Emoji: "🎭", EquipSlot: "armor", StatINT: 3, StatLUK: 2, MinRar: RarityEpic},
	{ID: "arcane_orb", Name: "Arcane Orb", Emoji: "🔮", EquipSlot: "trinket", StatINT: 4, MinRar: RarityEpic},
}

var DelveSuffixes = []DelveSuffix{
	{ID: "the_vengeful_warden", Name: "the Vengeful Warden", Description: "Forged in the tears of a betrayed guardian.", MinRar: RarityRare},
	{ID: "the_sunken_court", Name: "the Sunken Court", Description: "Retrieved from the depths of a drowned kingdom.", MinRar: RarityUncommon},
	{ID: "the_mad_jester", Name: "the Mad Jester", Description: "Cackles with chaotic energy.", MinRar: RarityRare},
	{ID: "the_forgotten_king", Name: "the Forgotten King", Description: "A relic of a ruler erased from history.", MinRar: RarityEpic},
	{ID: "the_silent_watcher", Name: "the Silent Watcher", Description: "Feels like it's always watching.", MinRar: RarityCommon},
	{ID: "the_hollow_priest", Name: "the Hollow Priest", Description: "Hums with a mournful prayer.", MinRar: RarityUncommon},
	{ID: "the_bone_collector", Name: "the Bone Collector", Description: "Craves the heat of battle.", MinRar: RarityCommon},
	{ID: "the_ashen_remnant", Name: "the Ashen Remnant", Description: "Still warm from the fire that consumed its home.", MinRar: RarityRare},
	{ID: "the_endless_depths", Name: "the Endless Depths", Description: "Seems to drink the light around it.", MinRar: RarityEpic},
	{ID: "the_shattered_oath", Name: "the Shattered Oath", Description: "Remembers a promise that was broken.", MinRar: RarityUncommon},
	{ID: "the_dying_star", Name: "the Dying Star", Description: "Pulsing with fading celestial light.", MinRar: RarityLegendary},
	{ID: "the_first_flame", Name: "the First Flame", Description: "The very first ember of creation.", MinRar: RarityLegendary},
	{ID: "the_iron_pact", Name: "the Iron Pact", Description: "Bound by an unbreakable contract.", MinRar: RarityRare},
	{ID: "deep_roots", Name: "Deep Roots", Description: "Grown in the darkest soil.", MinRar: RarityCommon},
	{ID: "the_frostbound_heart", Name: "the Frostbound Heart", Description: "Never thaws.", MinRar: RarityRare},
	{ID: "the_abyss_gazer", Name: "the Abyss Gazer", Description: "Looking into it, it looks back.", MinRar: RarityEpic},
	{ID: "the_lost_pages", Name: "the Lost Pages", Description: "A story cut short.", MinRar: RarityUncommon},
	{ID: "the_crimson_tide", Name: "the Crimson Tide", Description: "Still damp with the memory of battle.", MinRar: RarityUncommon},
	{ID: "thunders_call", Name: "Thunder's Call", Description: "Hums with static electricity.", MinRar: RarityRare},
	{ID: "the_golden_dawn", Name: "the Golden Dawn", Description: "Radiates hope and warmth.", MinRar: RarityEpic},
}

// --- Affix pool ------------------------------------------------------------
//
// RollAffixes (affixes.go) picks from this pool per rarity and equipment slot.

var AffixPool = []AffixDef{
	// --- Common affixes (all slots) ---
	{ID: "of_the_bear", Name: "of the Bear", Stat: "str", MinVal: 1, MaxVal: 3, MinRar: RarityCommon, Weight: 10},
	{ID: "of_the_cat", Name: "of the Cat", Stat: "dex", MinVal: 1, MaxVal: 3, MinRar: RarityCommon, Weight: 10},
	{ID: "of_the_owl", Name: "of the Owl", Stat: "int", MinVal: 1, MaxVal: 3, MinRar: RarityCommon, Weight: 10},
	{ID: "of_the_turtle", Name: "of the Turtle", Stat: "vit", MinVal: 1, MaxVal: 3, MinRar: RarityCommon, Weight: 10},
	{ID: "of_the_rabbit", Name: "of the Rabbit", Stat: "luk", MinVal: 1, MaxVal: 3, MinRar: RarityCommon, Weight: 10},

	// --- Uncommon affixes ---
	{ID: "of_power", Name: "of Power", Stat: "str", MinVal: 3, MaxVal: 6, MinRar: RarityUncommon, Weight: 8},
	{ID: "of_swiftness", Name: "of Swiftness", Stat: "dex", MinVal: 3, MaxVal: 6, MinRar: RarityUncommon, Weight: 8},
	{ID: "of_wisdom", Name: "of Wisdom", Stat: "int", MinVal: 3, MaxVal: 6, MinRar: RarityUncommon, Weight: 8},
	{ID: "of_endurance", Name: "of Endurance", Stat: "vit", MinVal: 3, MaxVal: 6, MinRar: RarityUncommon, Weight: 8},
	{ID: "of_fortune", Name: "of Fortune", Stat: "luk", MinVal: 3, MaxVal: 6, MinRar: RarityUncommon, Weight: 8},
	{ID: "of_accuracy", Name: "of Accuracy", Stat: "dex", MinVal: 2, MaxVal: 5, MinRar: RarityUncommon, Slots: []string{"weapon"}, Weight: 6},
	{ID: "of_protection", Name: "of Protection", Stat: "vit", MinVal: 2, MaxVal: 5, MinRar: RarityUncommon, Slots: []string{"armor"}, Weight: 6},
	{ID: "of_the_scholar", Name: "of the Scholar", Stat: "int", MinVal: 2, MaxVal: 5, MinRar: RarityUncommon, Slots: []string{"jewelry"}, Weight: 6},
	{ID: "of_gambling", Name: "of Gambling", Stat: "luk", MinVal: 2, MaxVal: 5, MinRar: RarityUncommon, Slots: []string{"jewelry", "trinket"}, Weight: 6},

	// --- Rare affixes ---
	{ID: "of_the_giant", Name: "of the Giant", Stat: "str", MinVal: 5, MaxVal: 10, MinRar: RarityRare, Weight: 5},
	{ID: "of_the_wind", Name: "of the Wind", Stat: "dex", MinVal: 5, MaxVal: 10, MinRar: RarityRare, Weight: 5},
	{ID: "of_the_archmage", Name: "of the Archmage", Stat: "int", MinVal: 5, MaxVal: 10, MinRar: RarityRare, Weight: 5},
	{ID: "of_the_mountain", Name: "of the Mountain", Stat: "vit", MinVal: 5, MaxVal: 10, MinRar: RarityRare, Weight: 5},
	{ID: "of_the_stars", Name: "of the Stars", Stat: "luk", MinVal: 5, MaxVal: 10, MinRar: RarityRare, Weight: 5},
	{ID: "of_the_dragon", Name: "of the Dragon", Stat: "str", MinVal: 3, MaxVal: 7, MinRar: RarityRare, Slots: []string{"weapon"}, Weight: 4},
	{ID: "of_the_warden", Name: "of the Warden", Stat: "vit", MinVal: 3, MaxVal: 7, MinRar: RarityRare, Slots: []string{"armor"}, Weight: 4},
	{ID: "of_the_seer", Name: "of the Seer", Stat: "int", MinVal: 3, MaxVal: 7, MinRar: RarityRare, Slots: []string{"jewelry", "trinket"}, Weight: 4},

	// --- Epic affixes ---
	{ID: "of_annihilation", Name: "of Annihilation", Stat: "str", MinVal: 8, MaxVal: 15, MinRar: RarityEpic, Slots: []string{"weapon"}, Weight: 3},
	{ID: "of_shadows", Name: "of Shadows", Stat: "dex", MinVal: 8, MaxVal: 15, MinRar: RarityEpic, Slots: []string{"armor", "trinket"}, Weight: 3},
	{ID: "of_the_void", Name: "of the Void", Stat: "int", MinVal: 8, MaxVal: 15, MinRar: RarityEpic, Slots: []string{"jewelry", "trinket"}, Weight: 3},
	{ID: "of_immortality", Name: "of Immortality", Stat: "vit", MinVal: 8, MaxVal: 15, MinRar: RarityEpic, Weight: 3},
	{ID: "of_miracles", Name: "of Miracles", Stat: "luk", MinVal: 8, MaxVal: 15, MinRar: RarityEpic, Weight: 3},

	// --- Legendary affixes ---
	{ID: "of_the_titan", Name: "of the Titan", Stat: "str", MinVal: 12, MaxVal: 20, MinRar: RarityLegendary, Weight: 1},
	{ID: "of_eternity", Name: "of Eternity", Stat: "vit", MinVal: 12, MaxVal: 20, MinRar: RarityLegendary, Weight: 1},
	{ID: "of_the_chosen", Name: "of the Chosen", Stat: "str", MinVal: 5, MaxVal: 10, MinRar: RarityLegendary, Slots: []string{"weapon", "armor"}, Weight: 1},
	{ID: "of_the_chosen_dex", Name: "of the Tempest", Stat: "dex", MinVal: 5, MaxVal: 10, MinRar: RarityLegendary, Slots: []string{"weapon", "armor"}, Weight: 1},
}

// --- Equipment sets --------------------------------------------------------
//
// Set pieces are tagged with SetID in the catalog below; CalculateSetBonuses
// (sets.go) aggregates equipped pieces by set.

var SetsByName = map[string]SetDef{
	"dragon_slayer": {
		ID:    "dragon_slayer",
		Name:  "Dragon Slayer",
		Emoji: "🐉",
		// The set has two jewelry pieces (ring + talisman), so only 3 pieces
		// can ever be equipped at once: the old 4-piece bonus now triggers at 3.
		Bonuses: []SetTier{
			{Pieces: 2, StatSTR: 5, StatVIT: 3, Desc: "2pc: +5 STR, +3 VIT"},
			{Pieces: 3, StatSTR: 10, StatVIT: 5, StatLUK: 3, Desc: "3pc: +10 STR, +5 VIT, +3 LUK"},
		},
	},
	"shadow_stalker": {
		ID:    "shadow_stalker",
		Name:  "Shadow Stalker",
		Emoji: "🌑",
		Bonuses: []SetTier{
			{Pieces: 2, StatDEX: 4, StatLUK: 3, Desc: "2pc: +4 DEX, +3 LUK"},
			{Pieces: 4, StatDEX: 8, StatLUK: 6, Desc: "4pc: +8 DEX, +6 LUK"},
		},
	},
	"arcane_weaver": {
		ID:    "arcane_weaver",
		Name:  "Arcane Weaver",
		Emoji: "🔮",
		Bonuses: []SetTier{
			{Pieces: 2, StatINT: 5, StatDEX: 3, Desc: "2pc: +5 INT, +3 DEX"},
			{Pieces: 4, StatINT: 10, StatDEX: 5, Desc: "4pc: +10 INT, +5 DEX"},
		},
	},
	"rift_walker": {
		ID:    "rift_walker",
		Name:  "Rift Walker",
		Emoji: "🔮",
		Bonuses: []SetTier{
			{Pieces: 2, StatSTR: 8, StatVIT: 8, StatLUK: 5, Desc: "2pc: +8 STR, +8 VIT, +5 LUK"},
			{Pieces: 4, StatSTR: 15, StatDEX: 15, StatINT: 15, StatVIT: 15, StatLUK: 10, Desc: "4pc: +15 ALL, +10 LUK"},
		},
	},
	// Delve zone sets: randomly-generated Rare/Epic pieces found in the
	// Undercroft (see AssignSetName in internal/service/delve). Mid-game gear —
	// the tiers sit below the Lv 20 legendary sets and above basic craftables.
	"crypt_lord_regalia": {
		ID: "crypt_lord_regalia", Name: "Crypt Lord's Regalia", Emoji: "👑",
		Procedural: true,
		Bonuses: []SetTier{
			{Pieces: 2, StatSTR: 4, StatVIT: 3, Desc: "2pc: +4 STR, +3 VIT"},
			{Pieces: 4, StatSTR: 8, StatVIT: 5, StatLUK: 2, Desc: "4pc: +8 STR, +5 VIT, +2 LUK"},
		},
	},
	"fungal_raiment": {
		ID: "fungal_raiment", Name: "Fungal Raiment", Emoji: "🍄",
		Procedural: true,
		Bonuses: []SetTier{
			{Pieces: 2, StatVIT: 4, StatINT: 2, Desc: "2pc: +4 VIT, +2 INT"},
			{Pieces: 4, StatVIT: 8, StatINT: 4, StatDEX: 2, Desc: "4pc: +8 VIT, +4 INT, +2 DEX"},
		},
	},
	"forge_master_arsenal": {
		ID: "forge_master_arsenal", Name: "Forge Master's Arsenal", Emoji: "⚒️",
		Procedural: true,
		Bonuses: []SetTier{
			{Pieces: 2, StatSTR: 3, StatINT: 3, Desc: "2pc: +3 STR, +3 INT"},
			{Pieces: 4, StatSTR: 6, StatINT: 6, StatDEX: 3, Desc: "4pc: +6 STR, +6 INT, +3 DEX"},
		},
	},
}

// --- Item catalog ----------------------------------------------------------

var all = []Item{
	// --- Mining ---
	{ID: "pebble", Source: SourceShop, Name: "Pebble", Emoji: "🪨", Price: 1, Description: "A useless little rock. Totally worthless.", EffectType: "resource", Droppable: true, Category: Mining},
	{ID: "coal", Source: SourceShop, Name: "Coal", Emoji: "🪨", Price: 5, Description: "Great for keeping warm.", EffectType: "resource", Droppable: true, Category: Mining},
	{ID: "iron_ore", Source: SourceShop, Name: "Iron Ore", Emoji: "⛏️", Price: 10, Description: "Useful for forging sturdy tools.", EffectType: "resource", Droppable: true, Category: Mining},
	{ID: "copper_ore", Source: SourceShop, Name: "Copper Ore", Emoji: "⛏️", Price: 15, Description: "Useful for forging sturdy tools.", EffectType: "resource", Droppable: true, Category: Mining},
	{ID: "silver_ore", Source: SourceShop, Name: "Silver Ore", Emoji: "⛏️", Price: 25, Description: "Useful for forging sturdy tools.", EffectType: "resource", Droppable: true, Category: Mining},
	{ID: "gold_nugget", Source: SourceShop, Name: "Gold Nugget", Emoji: "✨", Price: 50, Description: "Shiny! Merchants love this.", EffectType: "resource", Droppable: true, Category: Mining},
	{ID: "platinum", Source: SourceShop, Name: "Platinum", Emoji: "✨", Price: 75, Description: "Shiny! Merchants love this.", EffectType: "resource", Droppable: true, Category: Mining},
	{ID: "emerald", Source: SourceShop, Name: "Emerald", Emoji: "💚", Price: 100, Description: "AMAZING! Worth a fortune!", EffectType: "resource", Droppable: true, Category: Mining},
	{ID: "rough_diamond", Source: SourceShop, Name: "Rough Diamond", Emoji: "💎", Price: 300, Description: "AMAZING! Worth a fortune!", EffectType: "resource", Droppable: true, Category: Mining},

	// --- Fishing ---
	{ID: "old_boot", Source: SourceShop, Name: "Old Boot", Emoji: "🥾", Price: 1, Description: "An old boot. Worthless.", EffectType: "resource", Droppable: true, Category: Fishing},
	{ID: "trout", Source: SourceShop, Name: "Trout", Emoji: "🐟", Price: 10, Description: "Freshwater fish. Pet food: +1 SPD.", EffectType: "resource", Droppable: true, Category: Fishing},
	{ID: "salmon", Source: SourceShop, Name: "Salmon", Emoji: "🐟", Price: 10, Description: "Perfect for sushi. Pet food: +1 Max HP.", EffectType: "resource", Droppable: true, Category: Fishing},
	{ID: "sardine", Source: SourceShop, Name: "Sardine", Emoji: "🐟", Price: 15, Description: "A small saltwater fish. Pet food: +1 SPD.", EffectType: "resource", Droppable: true, Category: Fishing},
	{ID: "carp", Source: SourceShop, Name: "Carp", Emoji: "🐟", Price: 25, Description: "The best freshwater fish. Pet food: +1 SPD.", EffectType: "resource", Droppable: true, Category: Fishing},
	{ID: "pufferfish", Source: SourceShop, Name: "Pufferfish", Emoji: "🐡", Price: 50, Description: "Watch out, it stings!", EffectType: "resource", Droppable: true, Category: Fishing},
	{ID: "swordfish", Source: SourceShop, Name: "Swordfish", Emoji: "🐟", Price: 150, Description: "A majestic fighting fish.", EffectType: "resource", Droppable: true, Category: Fishing},
	{ID: "shark", Source: SourceShop, Name: "Shark", Emoji: "🦈", Price: 100, Description: "AMAZING! Worth a fortune!", EffectType: "resource", Droppable: true, Category: Fishing},
	{ID: "whale", Source: SourceShop, Name: "Whale", Emoji: "🐋", Price: 300, Description: "AMAZING! Worth a fortune!", EffectType: "resource", Droppable: true, Category: Fishing},
	{ID: "kraken_tentacle", Source: SourceShop, Name: "Kraken Tentacle", Emoji: "🦑", Price: 500, Description: "YOU CAUGHT A MONSTER?!", EffectType: "resource", Droppable: true, Category: Fishing},
	{ID: "magma_carp", Source: SourceShop, Name: "Magma Carp", Emoji: "🐟", Price: 200, Description: "A fiery fish from the depths.", EffectType: "resource", Droppable: true, Category: Fishing},
	{ID: "lava_serpent", Source: SourceShop, Name: "Lava Serpent", Emoji: "🐍", Price: 500, Description: "A legendary beast of molten rock.", EffectType: "resource", Droppable: true, Category: Fishing},
	{ID: "worm", Source: SourceShop, Name: "Worm", Emoji: "🪱", Price: 5, Description: "Common bait. Good for small catches.", EffectType: "bait", Droppable: true, Category: Fishing},
	{ID: "crayfish", Source: SourceShop, Name: "Crayfish", Emoji: "🦞", Price: 25, Description: "Rare bait. Attracts stronger fish.", EffectType: "bait", Droppable: true, Category: Fishing},
	{ID: "golden_lure", Source: SourceShop, Name: "Golden Lure", Emoji: "👑", Price: 100, Description: "Legendary bait. Draws the deadliest creatures.", EffectType: "bait", Droppable: true, Category: Fishing},
	{ID: "mutagen", Source: SourceShop, Name: "Mutagen", Emoji: "🧪", Price: 100, Description: "A glowing mutagenic substance from a mutated fish.", EffectType: "resource", Droppable: true, Category: Fishing},

	// --- Farming ---
	{ID: "rotten_plant", Source: SourceShop, Name: "Rotten Plant", Emoji: "🌿", Price: 0, Description: "You mismanaged your farm...", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "wheat", Source: SourceShop, Name: "Wheat", Emoji: "🌾", Price: 5, Description: "Essential for making bread. Pet food: +1 ACC.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "oat", Source: SourceShop, Name: "Oat", Emoji: "🌾", Price: 8, Description: "Perfect for breakfast. Pet food: +1 ACC.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "corn", Source: SourceShop, Name: "Corn", Emoji: "🌽", Price: 12, Description: "Also makes popcorn! Pet food: +1 ACC.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "potato", Source: SourceShop, Name: "Potato", Emoji: "🥔", Price: 20, Description: "You can make vodka from it… Pet food: +1 DEF.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "tomato", Source: SourceShop, Name: "Tomato", Emoji: "🍅", Price: 25, Description: "Fruit or vegetable? The debate continues. Pet food: +1 ATK.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "pumpkin", Source: SourceShop, Name: "Pumpkin", Emoji: "🎃", Price: 40, Description: "Perfect for Halloween. Pet food: +1 ATK.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "coffee_bean", Source: SourceShop, Name: "Coffee Bean", Emoji: "🫘", Price: 60, Description: "The black gold of the morning. Pet food: +1 ATK.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "cocoa_bean", Source: SourceShop, Name: "Cocoa Bean", Emoji: "🫘", Price: 75, Description: "The main ingredient for happiness (chocolate). Pet food: +1 ATK.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "strawberry", Source: SourceShop, Name: "Strawberry", Emoji: "🍓", Price: 90, Description: "Red, sweet and juicy. Pet food: +1 SPD.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "golden_apple", Source: SourceShop, Name: "Golden Apple", Emoji: "🍎", Price: 150, Description: "It shines with a magical glow. Pet food: +1 Max HP.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "star_fruit", Source: SourceShop, Name: "Star Fruit", Emoji: "⭐", Price: 250, Description: "A cosmic fruit from another dimension. Pet food: +1 SPD.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "carrot", Source: SourceShop, Name: "Carrot", Emoji: "🥕", Price: 15, Description: "A crunchy orange root. Pet food: +1 DEF.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "ghost_wheat", Source: SourceShop, Name: "Ghost Wheat", Emoji: "🌾", Price: 50, Description: "Translucent wheat that shimmers in moonlight. Pet food: +1 ACC.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "prismatic_corn", Source: SourceShop, Name: "Prismatic Corn", Emoji: "🌽", Price: 48, Description: "Kernels shift through impossible colors. Pet food: +1 ACC.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "golden_potato", Source: SourceShop, Name: "Golden Potato", Emoji: "🥔", Price: 160, Description: "A potato encased in solid gold! Pet food: +1 DEF.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "blood_tomato", Source: SourceShop, Name: "Blood Tomato", Emoji: "🍅", Price: 150, Description: "Deep crimson, pulsing with warmth... Pet food: +1 ATK.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "cursed_pumpkin", Source: SourceShop, Name: "Cursed Pumpkin", Emoji: "🎃", Price: 400, Description: "It whispers to you at night. Pet food: +1 ATK.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "golden_carrot", Source: SourceShop, Name: "Golden Carrot", Emoji: "🥕", Price: 1000, Description: "A carrot of pure gold. Legendary. Pet food: +1 DEF.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "nova_fruit", Source: SourceShop, Name: "Nova Fruit", Emoji: "⭐", Price: 5000, Description: "A miniature sun cradled in your hands. Pet food: +1 Max HP.", EffectType: "resource", Droppable: true, Category: Farming},
	{ID: "mysterious_seed", Source: SourceShop, Name: "Mysterious Seed", Emoji: "🔮", Price: 0, Description: "An unknown seed pulsing with energy.", EffectType: "resource", Droppable: false, Category: Farming},

	// --- Archeology ---
	{ID: "bone_dust", Source: SourceShop, Name: "Bone Dust", Emoji: "🦴", Price: 1, Description: "Bone dust from a completely destroyed fossil.", EffectType: "resource", Droppable: true, Category: Archeology},
	{ID: "damaged_fossil", Source: SourceShop, Name: "Damaged Fossil", Emoji: "🦴", Price: 50, Description: "A poorly extracted fossil that lost its value.", EffectType: "resource", Droppable: true, Category: Archeology},
	{ID: "common_fossil", Source: SourceShop, Name: "Common Fossil", Emoji: "🦴", Price: 150, Description: "An intact fossil of a common animal.", EffectType: "resource", Droppable: true, Category: Archeology},
	{ID: "rare_fossil", Source: SourceShop, Name: "Rare Fossil", Emoji: "🦴", Price: 300, Description: "An intact fossil of a rare animal.", EffectType: "resource", Droppable: true, Category: Archeology},
	{ID: "epic_fossil", Source: SourceShop, Name: "Epic Fossil", Emoji: "🦴", Price: 500, Description: "An intact fossil of an epic animal.", EffectType: "resource", Droppable: true, Category: Archeology},
	{ID: "legendary_fragment", Source: SourceShop, Name: "Legendary Fragment", Emoji: "🦖", Price: 1000, Description: "A legendary T-Rex fragment!", EffectType: "resource", Droppable: true, Category: Archeology},
	{ID: "pure_dna", Source: SourceShop, Name: "Pure DNA", Emoji: "🧬", Price: 3000, Description: "Perfectly preserved dinosaur DNA. Amazing!", EffectType: "resource", Droppable: true, Category: Archeology},
	{ID: "shadow_fossil", Source: SourceShop, Name: "Shadow Fossil", Emoji: "🖤", Price: 5000, Description: "A fossil of pure darkness. It seems to absorb light.", EffectType: "resource", Droppable: true, Category: Archeology},
	{ID: "cursed_artifact", Source: SourceShop, Name: "Cursed Artifact", Emoji: "🔮", Price: 800, Description: "An ancient relic pulsing with dark energy.", EffectType: "resource", Droppable: true, Category: Archeology},
	{ID: "purified_relic", Source: SourceShop, Name: "Purified Relic", Emoji: "✨", Price: 1500, Description: "A relic cleansed of its dark curse.", EffectType: "resource", Droppable: true, Category: Archeology},
	{ID: "fossilized_egg", Source: SourceShop, Name: "Fossilized Egg", Emoji: "🥚", Price: 500, Description: "A stone egg with ancient patterns. Who knows what's inside?", EffectType: "consumable", Droppable: false, Category: Special},
	{ID: "excavator_hat", Source: SourceQuest, Name: "Excavator's Hat", Emoji: "🎩", Price: 0, Description: "A worn expedition hat. It carries centuries of stories.", EffectType: "collectible", Droppable: false, Category: Special},
	{ID: "journal_page_1", Source: SourceQuest, Name: "Journal Page #1", Emoji: "📄", Price: 1, Description: "A torn page from an ancient excavator's journal.", EffectType: "resource", Droppable: false, Category: Archeology},
	{ID: "journal_page_2", Source: SourceQuest, Name: "Journal Page #2", Emoji: "📄", Price: 1, Description: "A torn page from an ancient excavator's journal.", EffectType: "resource", Droppable: false, Category: Archeology},
	{ID: "journal_page_3", Source: SourceQuest, Name: "Journal Page #3", Emoji: "📄", Price: 1, Description: "A torn page from an ancient excavator's journal.", EffectType: "resource", Droppable: false, Category: Archeology},
	{ID: "journal_page_4", Source: SourceQuest, Name: "Journal Page #4", Emoji: "📄", Price: 1, Description: "A torn page from an ancient excavator's journal.", EffectType: "resource", Droppable: false, Category: Archeology},
	{ID: "journal_page_5", Source: SourceQuest, Name: "Journal Page #5", Emoji: "📄", Price: 1, Description: "A torn page from an ancient excavator's journal.", EffectType: "resource", Droppable: false, Category: Archeology},
	{ID: "journal_page_6", Source: SourceQuest, Name: "Journal Page #6", Emoji: "📄", Price: 1, Description: "A torn page from an ancient excavator's journal.", EffectType: "resource", Droppable: false, Category: Archeology},
	{ID: "journal_page_7", Source: SourceQuest, Name: "Journal Page #7", Emoji: "📄", Price: 1, Description: "A torn page from an ancient excavator's journal.", EffectType: "resource", Droppable: false, Category: Archeology},
	{ID: "journal_page_8", Source: SourceQuest, Name: "Journal Page #8", Emoji: "📄", Price: 1, Description: "A torn page from an ancient excavator's journal.", EffectType: "resource", Droppable: false, Category: Archeology},

	// --- Seeds (Materials) ---
	{ID: "wheat_seed", Source: SourceShop, Name: "Wheat Seed", Emoji: "🌱", Price: 2, Description: "Plant to get wheat (5 min).", EffectType: "resource", Droppable: true, Category: Materials},
	{ID: "oat_seed", Source: SourceShop, Name: "Oat Seed", Emoji: "🌱", Price: 3, Description: "Plant to get oat (10 min).", EffectType: "resource", Droppable: true, Category: Materials},
	{ID: "corn_seed", Source: SourceShop, Name: "Corn Seed", Emoji: "🌱", Price: 5, Description: "Plant to get corn (30 min).", EffectType: "resource", Droppable: true, Category: Materials},
	{ID: "potato_seed", Source: SourceShop, Name: "Potato Seed", Emoji: "🌱", Price: 8, Description: "Plant to get potato (1h).", EffectType: "resource", Droppable: true, Category: Materials},
	{ID: "tomato_seed", Source: SourceShop, Name: "Tomato Seed", Emoji: "🌱", Price: 10, Description: "Plant to get tomato (2h).", EffectType: "resource", Droppable: true, Category: Materials},
	{ID: "pumpkin_seed", Source: SourceShop, Name: "Pumpkin Seed", Emoji: "🌱", Price: 15, Description: "Plant to get pumpkin (4h).", EffectType: "resource", Droppable: true, Category: Materials},
	{ID: "coffee_seed", Source: SourceShop, Name: "Coffee Seed", Emoji: "🌱", Price: 25, Description: "Plant to get coffee (8h).", EffectType: "resource", Droppable: true, Category: Materials},
	{ID: "cocoa_seed", Source: SourceShop, Name: "Cocoa Seed", Emoji: "🌱", Price: 30, Description: "Plant to get cocoa (12h).", EffectType: "resource", Droppable: true, Category: Materials},
	{ID: "strawberry_seed", Source: SourceShop, Name: "Strawberry Seed", Emoji: "🌱", Price: 40, Description: "Plant to get strawberry (18h).", EffectType: "resource", Droppable: true, Category: Materials},
	{ID: "golden_apple_seed", Source: SourceShop, Name: "Golden Apple Seed", Emoji: "🌱", Price: 75, Description: "Plant to get golden apple (24h).", EffectType: "resource", Droppable: true, Category: Materials},
	{ID: "star_fruit_seed", Source: SourceShop, Name: "Star Fruit Seed", Emoji: "🌱", Price: 125, Description: "Plant to get star fruit (48h).", EffectType: "resource", Droppable: true, Category: Materials},
	{ID: "carrot_seed", Source: SourceShop, Name: "Carrot Seed", Emoji: "🌱", Price: 7, Description: "Plant to get carrot (15 min).", EffectType: "resource", Droppable: true, Category: Materials},

	// --- Tools ---
	{ID: "beer", Source: SourceCraft, Name: "Beer", Emoji: "🍺", Price: 50, Description: "The miner's drink! Resets !mine cooldown.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "coffee", Source: SourceCraft, Name: "Coffee", Emoji: "☕", Price: 50, Description: "Wakes you up. Resets !daily cooldown. Pet food: +1 SPD.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "bow", Source: SourceCraft, Name: "Bow", Emoji: "🏹", Price: 300, Description: "Helps with hunting! Resets !hunt cooldown.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "fertilizer", Source: SourceCraft, Name: "Fertilizer", Emoji: "🧪", Price: 200, Description: "Accelerates crop growth! Reduces remaining grow time by 30%.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "growth_elixir", Source: SourceShop, Name: "Growth Elixir", Emoji: "⚡", Price: 250, Description: "Instantly matures a growing crop.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "hook", Source: SourceCraft, Name: "Hook", Emoji: "🪝", Price: 200, Description: "Attracts fish! Resets !fish cooldown.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "forget_potion", Source: SourceCraft, Name: "Forget Potion", Emoji: "🧪", Price: 2500, Description: "Resets your pet to level 10.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "skill_scroll", Source: SourceShop, Name: "Skill Scroll", Emoji: "📜", Price: 5000, Description: "Resets all your active pet's learned skills.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "bond_treat", Source: SourceShop, Name: "Bond Treat", Emoji: "🍬", Price: 150, Description: "Increases your active pet's bond level by 5.", EffectType: "consumable", Droppable: false, Category: Food},

	// --- Pet Food (crafted, +1 stat, +1 bond) ---
	{ID: "warrior_stew", Source: SourceCraft, Name: "Warrior's Stew", Emoji: "🍲", Price: 100, Description: "A hearty meat stew that fortifies your pet. +1 ATK.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "stonebread", Source: SourceCraft, Name: "Stonebread", Emoji: "🍞", Price: 100, Description: "A dense, mineral-rich loaf. +1 DEF.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "zephyr_berries", Source: SourceCraft, Name: "Zephyr Berries", Emoji: "🫐", Price: 120, Description: "Wild berries crackling with wind energy. +1 SPD.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "hunters_soup", Source: SourceCraft, Name: "Hunter's Eye Soup", Emoji: "🥘", Price: 120, Description: "A sharp-eyed hunter's secret recipe. +1 ACC.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "lucky_roast", Source: SourceCraft, Name: "Lucky Roast", Emoji: "🌶️", Price: 100, Description: "A fiery roast that sharpens fate. +1 Crit Chance.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "thunder_steak", Source: SourceCraft, Name: "Thunder Steak", Emoji: "🥩", Price: 100, Description: "A crackling cut that amplifies strikes. +0.1 Crit Damage.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "heart_stew", Source: SourceCraft, Name: "Heart Stew", Emoji: "🥣", Price: 120, Description: "A hearty broth that bulks the constitution. +2 Max HP.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "dragon_chili", Source: SourceCraft, Name: "Dragon Chili", Emoji: "🐉", Price: 100, Description: "A blistering chili that awakens raw power. +1 ATK.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "iron_loaf", Source: SourceCraft, Name: "Iron Loaf", Emoji: "🥖", Price: 100, Description: "A crusty loaf as dense as forged ore. +1 DEF.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "storm_porridge", Source: SourceCraft, Name: "Storm Porridge", Emoji: "🍵", Price: 120, Description: "A steaming porridge that tingles with haste. +1 SPD.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "falcon_pie", Source: SourceCraft, Name: "Falcon Pie", Emoji: "🥧", Price: 120, Description: "A savory pie that sharpens the eye. +1 ACC.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "clover_salad", Source: SourceCraft, Name: "Clover Salad", Emoji: "🍀", Price: 120, Description: "Crisp greens luckier than a four-leaf clover. +1 Crit Chance.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "volcano_ribs", Source: SourceCraft, Name: "Volcano Ribs", Emoji: "🌋", Price: 100, Description: "Ribs seared in subterranean heat. +0.1 Crit Damage.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "giant_noodles", Source: SourceCraft, Name: "Giant Noodles", Emoji: "🍜", Price: 120, Description: "An endless bowl of hearty noodles. +2 Max HP.", EffectType: "consumable", Droppable: false, Category: Food},

	// --- Pet Potions (crafted, +2 stat, +1 bond) ---
	{ID: "berserker_elixir", Source: SourceCraft, Name: "Berserker Elixir", Emoji: "⚗️", Price: 400, Description: "A volatile brew that awakens raw fury. +2 ATK.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "adamant_tonic", Source: SourceCraft, Name: "Adamant Tonic", Emoji: "🧪", Price: 400, Description: "Turns the drinker's hide to living stone. +2 DEF.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "gale_draught", Source: SourceCraft, Name: "Gale Draught", Emoji: "💨", Price: 450, Description: "Tastes like a storm on the tongue. +2 SPD.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "oracles_insight", Source: SourceCraft, Name: "Oracle's Insight", Emoji: "👁️", Price: 450, Description: "A single sip of foresight. +2 ACC.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "fatalist_elixir", Source: SourceCraft, Name: "Fatalist Elixir", Emoji: "⚗️", Price: 400, Description: "A brew that bends fortune toward doom. +2 Crit Chance.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "ruin_tonic", Source: SourceCraft, Name: "Ruin Tonic", Emoji: "🧪", Price: 400, Description: "Turns every strike into a cataclysm. +0.2 Crit Damage.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "vitality_elixir", Source: SourceCraft, Name: "Vitality Elixir", Emoji: "❤️", Price: 450, Description: "A living tonic that swells the heart. +4 Max HP.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "skull_elixir", Source: SourceCraft, Name: "Skull Elixir", Emoji: "💀", Price: 400, Description: "A brew of predatory ferocity. +2 ATK.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "bastion_tonic", Source: SourceCraft, Name: "Bastion Tonic", Emoji: "🛡️", Price: 400, Description: "Turns flesh into a fortress wall. +2 DEF.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "tempest_draught", Source: SourceCraft, Name: "Tempest Draught", Emoji: "🌪️", Price: 450, Description: "A storm bottled and swallowed. +2 SPD.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "seer_elixir", Source: SourceCraft, Name: "Seer Elixir", Emoji: "🔮", Price: 450, Description: "Foresight in a single gulp. +2 ACC.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "gamblers_tonic", Source: SourceCraft, Name: "Gambler's Tonic", Emoji: "🎲", Price: 400, Description: "Fate itself starts to hedge its bets. +2 Crit Chance.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "annihilator_elixir", Source: SourceCraft, Name: "Annihilator Elixir", Emoji: "☠️", Price: 400, Description: "Every blow ends in catastrophe. +0.2 Crit Damage.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "colossus_draught", Source: SourceCraft, Name: "Colossus Draught", Emoji: "🗿", Price: 450, Description: "Grants the endurance of a mountain. +4 Max HP.", EffectType: "consumable", Droppable: false, Category: Food},
	{ID: "personality_mirror", Source: SourceShop, Name: "Personality Mirror", Emoji: "🪞", Price: 7500, Description: "Mysteriously changes your pet's personality.", EffectType: "consumable", Droppable: false, Category: Special},
	{ID: "artifact_shard", Source: SourceShop, Name: "Artifact Shard", Emoji: "💠", Price: 7500, Description: "Resets your pet artifact, re-rolling all 3 stats.", EffectType: "consumable", Droppable: false, Category: Special},
	{ID: "fortune_cookie", Source: SourceCraft, Name: "Fortune Cookie", Emoji: "🥠", Price: 20, Description: "A delicious cookie with a premonitory message.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "rusty_magnet", Source: SourceCraft, Name: "Rusty Magnet", Emoji: "🧲", Price: 30, Description: "Pulls scrap ore from the ground. In the mine, farm or Undercroft it can unearth buried hoards.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "magnet", Source: SourceCraft, Name: "Magnet", Emoji: "🧲", Price: 100, Description: "Pulls precious ore from the ground. In the mine, farm or Undercroft it can unearth buried hoards.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "electric_magnet", Source: SourceCraft, Name: "Electric Magnet", Emoji: "🧲", Price: 600, Description: "Pulls valuable ore from deep underground. In the mine, farm or Undercroft it can unearth rich hoards.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "rigged_coin", Source: SourceCraft, Name: "Rigged Coin", Emoji: "🪙", Price: 200, Description: "Boosts your luck. Raises coinflip odds to 75%.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "casino_token", Source: SourceCraft, Name: "Casino Token", Emoji: "🎰", Price: 50, Description: "Gives you another chance at !casino.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "vip_ticket", Source: SourceCraft, Name: "VIP Ticket", Emoji: "🎟️", Price: 100, Description: "Resets your casino and coinflip limits.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "identity_scroll", Source: SourceCraft, Name: "Identity Scroll", Emoji: "📜", Price: 500, Description: "Randomly changes your server nickname.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "thieves_glove", Source: SourceShop, Name: "Thieve's Glove", Emoji: "🧤", Price: 20, Description: "Use !rob @target with these gloves.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "scratch_ticket", Source: SourceCraft, Name: "Scratch Ticket", Emoji: "🎰", Price: 100, Description: "Scratch to win up to $1000 instantly!", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "data_disk", Source: SourceShop, Name: "Data Disk", Emoji: "💾", Price: 50, Description: "A corrupted memory disk from a lost era.", EffectType: "consumable", Droppable: false, Category: Tools},
	{ID: "old_journal", Source: SourceShop, Name: "Old Journal", Emoji: "📖", Price: 30, Description: "A dusty notebook handwritten by an unknown author.", EffectType: "consumable", Droppable: false, Category: Tools},

	// --- Mining Tools & Artifacts ---
	{ID: "steel_pickaxe", Source: SourceShop, Name: "Steel Pickaxe", Emoji: "⛏️", Price: 1500, Description: "A sturdy steel pickaxe. Grants +1 loot tier and -5% collapse risk per descend. Breaks after 25 digs.", EffectType: "mining_tool", Droppable: false, Category: Tools, Durability: 25},
	{ID: "diamond_drill", Source: SourceShop, Name: "Diamond Drill", Emoji: "🔧", Price: 5000, Description: "A diamond-tipped drill. Grants +2 loot tiers and -10% collapse risk per descend. Breaks after 50 digs.", EffectType: "mining_tool", Droppable: false, Category: Tools, Durability: 50},
	{ID: "ancient_alloy", Source: SourceShop, Name: "Ancient Alloy", Emoji: "🔩", Price: 500, Description: "A fragment of metal from a forgotten forge. It hums with residual heat.", EffectType: "resource", Droppable: true, Category: Mining},
	{ID: "ancient_core_shard", Source: SourceQuest, Name: "Ancient Core Shard", Emoji: "💠", Price: 0, Description: "A crystalline shard from the Heart of the Mountain. It pulses with a faint light.", EffectType: "collectible", Droppable: false, Category: Special},
	{ID: "kethari_crystal", Source: SourceShop, Name: "Kethari Crystal", Emoji: "🔮", Price: 1000, Description: "A prismatic crystal forged by the Kethari. It hums with stored resonance.", EffectType: "resource", Droppable: true, Category: Mining},
	{ID: "primordial_geode", Source: SourceShop, Name: "Primordial Geode", Emoji: "🪨", Price: 2000, Description: "A geode from the dawn of the mountain. Who knows what lies within?", EffectType: "resource", Droppable: true, Category: Mining},
	{ID: "resonance_core", Source: SourceShop, Name: "Resonance Core", Emoji: "⚡", Price: 5000, Description: "A perfectly preserved Kethari power source. It radiates ancient energy.", EffectType: "resource", Droppable: true, Category: Mining},

	// --- Veil Raid ---
	{ID: "veil_key", Source: SourceVeil, Name: "Veil Key", Emoji: "🔮", Price: 5000, Description: "Opens a dimensional tear into the Veil Rift. Required to create or join a raid.", EffectType: "consumable", Droppable: false, Category: Special},
	{ID: "dimensional_shard", Source: SourceVeil, Name: "Dimensional Shard", Emoji: "💠", Price: 100, Description: "Fragments of broken reality. Used as raid currency for exclusive gear and cosmetics.", EffectType: "collectible", Droppable: false, Category: Special},

	// --- Eggs ---
	{ID: "forest_egg", Source: SourceShop, Name: "Forest Egg", Emoji: "🥚", Price: 4000, Description: "A forest-embraced egg. Type !hatch to open it!", EffectType: "consumable", Droppable: false, Category: Special},
	{ID: "cave_egg", Source: SourceShop, Name: "Cave Egg", Emoji: "🥚", Price: 6000, Description: "A cavern-dark egg. Type !hatch to open it!", EffectType: "consumable", Droppable: false, Category: Special},
	{ID: "desert_egg", Source: SourceShop, Name: "Desert Egg", Emoji: "🥚", Price: 8000, Description: "A sun-scorched egg. Type !hatch to open it!", EffectType: "consumable", Droppable: false, Category: Special},
	{ID: "mountain_egg", Source: SourceShop, Name: "Mountain Egg", Emoji: "🥚", Price: 10000, Description: "A peak-born egg. Type !hatch to open it!", EffectType: "consumable", Droppable: false, Category: Special},
	{ID: "ocean_egg", Source: SourceShop, Name: "Ocean Egg", Emoji: "🥚", Price: 12000, Description: "A deep-sea egg. Type !hatch to open it!", EffectType: "consumable", Droppable: false, Category: Special},
	{ID: "tundra_egg", Source: SourceShop, Name: "Tundra Egg", Emoji: "🥚", Price: 14000, Description: "An ice-wrapped egg. Type !hatch to open it!", EffectType: "consumable", Droppable: false, Category: Special},
	{ID: "volcano_egg", Source: SourceCraft, Name: "Volcano Egg", Emoji: "🥚", Price: 16000, Description: "A magma-infused egg. Type !hatch to open it!", EffectType: "consumable", Droppable: false, Category: Special},
	{ID: "boss_trophy", Source: SourceBoss, Name: "Boss Trophy", Emoji: "🏆", Price: 10000, Description: "A legendary trophy for defeating the boss.", EffectType: "collectible", Droppable: false, Category: Special},
	{ID: "mastery_medallion", Source: SourceQuest, Name: "Mastery Medallion", Emoji: "🏅", Price: 50000, Description: "Awarded only to those who master every journal path.", EffectType: "collectible", Droppable: false, Category: Special},
	{ID: "garden_plot", Source: SourceCraft, Name: "Garden Plot", Emoji: "🌿", Price: 500, Description: "A patch of fertile soil for growing vegetables.", EffectType: "permanent", Droppable: false, Category: Special},
	{ID: "tropical_greenhouse", Source: SourceCraft, Name: "Tropical Greenhouse", Emoji: "🌿", Price: 1000, Description: "A heated glass structure for coffee and cocoa.", EffectType: "permanent", Droppable: false, Category: Special},
	{ID: "enchanted_orchard", Source: SourceCraft, Name: "Enchanted Orchard", Emoji: "🌿", Price: 10000, Description: "A magical floating island. Only legendary fruits grow here.", EffectType: "permanent", Droppable: false, Category: Special},
	{ID: "scarecrow_charm", Source: SourceQuest, Name: "Scarecrow Charm", Emoji: "🧿", Price: 0, Description: "A small charm shaped like a winking scarecrow.", EffectType: "collectible", Droppable: false, Category: Special},

	// --- Equipment: Tier 1 (Lv 1, Common) ---
	{ID: "stick", Source: SourceCraft, Name: "Wooden Stick", Emoji: "🪵", Price: 50, Description: "A sturdy branch. Decent for a start. (+2 STR)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityCommon, MinLevel: 1, EquipSlot: "weapon", StatSTR: 2},
	{ID: "leather_armor", Source: SourceCraft, Name: "Leather Armor", Emoji: "🦺", Price: 300, Description: "Basic protection. (+2 VIT)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityCommon, MinLevel: 1, EquipSlot: "armor", StatVIT: 2},

	// --- Equipment: Tier 2 (Lv 5, Uncommon) ---
	{ID: "iron_mace", Source: SourceCraft, Name: "Iron Mace", Emoji: "🔨", Price: 500, Description: "A heavy iron mace. (+4 STR)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityUncommon, MinLevel: 5, EquipSlot: "weapon", StatSTR: 4},
	{ID: "fishing_rod", Source: SourceCraft, Name: "Fishing Rod", Emoji: "🎣", Price: 500, Description: "A quality rod. (+4 DEX)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityUncommon, MinLevel: 5, EquipSlot: "weapon", StatDEX: 4},
	{ID: "lucky_charm", Source: SourceCraft, Name: "Lucky Charm", Emoji: "🍀", Price: 400, Description: "A four-leaf clover. (+3 LUK)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityUncommon, MinLevel: 5, EquipSlot: "trinket", StatLUK: 3},
	{ID: "miner_helmet", Source: SourceCraft, Name: "Miner's Helmet", Emoji: "⛑️", Price: 800, Description: "Thick steel helmet. (+3 VIT, +1 STR)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityUncommon, MinLevel: 5, EquipSlot: "armor", StatVIT: 3, StatSTR: 1},
	// Tutorial finale reward — "The Signal" quest completion.
	{ID: "zenith_blade", Source: SourceQuest, Name: "Zenith Blade", Emoji: "⚔️", Price: 0, Description: "Forged from the Vault Guardian's core. It hums with the Generator's light. (+5 STR, +2 VIT)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityRare, MinLevel: 5, EquipSlot: "weapon", StatSTR: 5, StatVIT: 2, ShopExcluded: true},

	// --- Equipment: Tier 3 (Lv 10, Rare) ---
	{ID: "hunters_bow", Source: SourceCraft, Name: "Hunter's Bow", Emoji: "🏹", Price: 1200, Description: "A precise bow. (+6 STR)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityRare, MinLevel: 10, EquipSlot: "weapon", StatSTR: 6},
	{ID: "crystal_staff", Source: SourceCraft, Name: "Crystal Staff", Emoji: "🔮", Price: 2500, Description: "Pulsing with arcane energy. (+6 INT)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityRare, MinLevel: 10, EquipSlot: "weapon", StatINT: 6},
	{ID: "hunter_cloak", Source: SourceCraft, Name: "Hunter's Cloak", Emoji: "🧥", Price: 1500, Description: "Warm and agile. (+4 VIT, +3 DEX)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityRare, MinLevel: 10, EquipSlot: "armor", StatVIT: 4, StatDEX: 3},
	{ID: "golden_ring", Source: SourceCraft, Name: "Golden Ring", Emoji: "💍", Price: 2000, Description: "Glows with fortune. (+4 LUK, +1 STR)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityRare, MinLevel: 10, EquipSlot: "jewelry", StatLUK: 4, StatSTR: 1},

	// --- Equipment: Tier 4 (Lv 15, Epic) ---
	{ID: "enchanted_robe", Source: SourceCraft, Name: "Enchanted Robe", Emoji: "👘", Price: 3000, Description: "Woven with wisdom. (+6 INT, +3 VIT)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityEpic, MinLevel: 15, EquipSlot: "armor", StatINT: 6, StatVIT: 3},
	{ID: "ancient_amulet", Source: SourceCraft, Name: "Ancient Amulet", Emoji: "📿", Price: 3000, Description: "Humming with ancient magic. (+4 INT, +4 LUK)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityEpic, MinLevel: 15, EquipSlot: "jewelry", StatINT: 4, StatLUK: 4},

	// --- Dragon Slayer Set (Lv 20, Legendary) ---
	{ID: "dragon_slayer_sword", Source: SourceCraft, Name: "Dragon Slayer Sword", Emoji: "🗡️", Price: 0, Description: "A blade forged from a dragon's fang. Part of the Dragon Slayer set.", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityLegendary, MinLevel: 20, EquipSlot: "weapon", StatSTR: 12, StatVIT: 4, SetID: "dragon_slayer", SetName: "Dragon Slayer"},
	{ID: "dragon_slayer_armor", Source: SourceCraft, Name: "Dragon Slayer Armor", Emoji: "🛡️", Price: 0, Description: "Scale mail of an ancient wyrm. Part of the Dragon Slayer set.", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityLegendary, MinLevel: 20, EquipSlot: "armor", StatVIT: 8, StatSTR: 4, SetID: "dragon_slayer", SetName: "Dragon Slayer"},
	{ID: "dragon_slayer_ring", Source: SourceCraft, Name: "Dragon Slayer Ring", Emoji: "💍", Price: 0, Description: "A band of dragon bone and gold. Part of the Dragon Slayer set.", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityLegendary, MinLevel: 20, EquipSlot: "jewelry", StatLUK: 4, StatSTR: 6, SetID: "dragon_slayer", SetName: "Dragon Slayer"},
	{ID: "dragon_slayer_talisman", Source: SourceCraft, Name: "Dragon Slayer Talisman", Emoji: "📿", Price: 0, Description: "A tooth of the first dragon ever slain. Part of the Dragon Slayer set.", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityLegendary, MinLevel: 20, EquipSlot: "jewelry", StatSTR: 6, StatVIT: 5, StatLUK: 3, SetID: "dragon_slayer", SetName: "Dragon Slayer"},

	// --- Shadow Stalker Set (Lv 20, Legendary) ---
	{ID: "shadow_stalker_blade", Source: SourceCraft, Name: "Shadow Stalker Blade", Emoji: "🗡️", Price: 0, Description: "A dagger that drinks the light. Part of the Shadow Stalker set.", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityLegendary, MinLevel: 20, EquipSlot: "weapon", StatDEX: 12, StatLUK: 4, SetID: "shadow_stalker", SetName: "Shadow Stalker"},
	{ID: "shadow_stalker_cloak", Source: SourceCraft, Name: "Shadow Stalker Cloak", Emoji: "🧥", Price: 0, Description: "Woven from midnight silk. Part of the Shadow Stalker set.", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityLegendary, MinLevel: 20, EquipSlot: "armor", StatDEX: 6, StatVIT: 6, SetID: "shadow_stalker", SetName: "Shadow Stalker"},
	{ID: "shadow_stalker_amulet", Source: SourceCraft, Name: "Shadow Stalker Amulet", Emoji: "📿", Price: 0, Description: "A dark gem that whispers secrets. Part of the Shadow Stalker set.", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityLegendary, MinLevel: 20, EquipSlot: "jewelry", StatLUK: 8, StatDEX: 4, SetID: "shadow_stalker", SetName: "Shadow Stalker"},
	{ID: "shadow_stalker_charm", Source: SourceCraft, Name: "Shadow Stalker Charm", Emoji: "🍀", Price: 0, Description: "Luck woven from shadow itself. Part of the Shadow Stalker set.", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityLegendary, MinLevel: 20, EquipSlot: "trinket", StatDEX: 5, StatLUK: 6, SetID: "shadow_stalker", SetName: "Shadow Stalker"},

	// --- Arcane Weaver Set (Lv 20, Legendary) ---
	{ID: "arcane_weaver_staff", Source: SourceCraft, Name: "Arcane Weaver Staff", Emoji: "🪄", Price: 0, Description: "A conduit of raw magic. Part of the Arcane Weaver set.", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityLegendary, MinLevel: 20, EquipSlot: "weapon", StatINT: 12, StatDEX: 4, SetID: "arcane_weaver", SetName: "Arcane Weaver"},
	{ID: "arcane_weaver_robe", Source: SourceCraft, Name: "Arcane Weaver Robe", Emoji: "👘", Price: 0, Description: "Ethereal fabric humming with power. Part of the Arcane Weaver set.", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityLegendary, MinLevel: 20, EquipSlot: "armor", StatINT: 8, StatVIT: 4, SetID: "arcane_weaver", SetName: "Arcane Weaver"},
	{ID: "arcane_weaver_crown", Source: SourceCraft, Name: "Arcane Weaver Crown", Emoji: "👑", Price: 0, Description: "A circlet of crystallized thought. Part of the Arcane Weaver set.", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityLegendary, MinLevel: 20, EquipSlot: "jewelry", StatINT: 8, StatLUK: 4, SetID: "arcane_weaver", SetName: "Arcane Weaver"},
	{ID: "arcane_weaver_orb", Source: SourceCraft, Name: "Arcane Weaver Orb", Emoji: "🔮", Price: 0, Description: "A sphere of pure arcane energy. Part of the Arcane Weaver set.", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityLegendary, MinLevel: 20, EquipSlot: "trinket", StatINT: 8, StatDEX: 4, SetID: "arcane_weaver", SetName: "Arcane Weaver"},

	// --- Criminality items ---
	{ID: "mask_of_malveillance", Source: SourceCriminality, Name: "Mask of Malveillance", Emoji: "🎭", Price: 50000, Description: "An ancient mask that awakens the underworld. Those who wear it gain access to the shadows.", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityLegendary, MinLevel: 25, EquipSlot: "trinket", StatDEX: 5, StatLUK: 5, ShopExcluded: true},
	{ID: "hounds_cloak", Source: SourceCriminality, Name: "Hound's Cloak", Emoji: "🧥", Price: 1, Description: "The ceremonial cloak of the Iron Lodge. A symbol of the hunt. (+6 VIT, +2 STR)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityEpic, MinLevel: 15, EquipSlot: "armor", StatVIT: 6, StatSTR: 2, ShopExcluded: true},
	{ID: "shadow_cowl", Source: SourceCriminality, Name: "Shadow Cowl", Emoji: "🕶️", Price: 1, Description: "A dark hood worn by those who walk the Silent Path. (+4 DEX, +2 VIT)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityRare, MinLevel: 10, EquipSlot: "armor", StatDEX: 4, StatVIT: 2, ShopExcluded: true},

	// --- Bounty Hunter gear (Sheriff Vance) ---
	{ID: "iron_shackles", Source: SourceCriminality, Name: "Iron Shackles", Emoji: "⛓️", Price: 100, Description: "Rusty but reliable manacles. (+3 VIT, +1 STR)", EffectType: "equipment", Droppable: false, Category: Equipment, EquipSlot: "trinket", StatVIT: 3, StatSTR: 1, ShopExcluded: true},
	{ID: "wanted_poster", Source: SourceCriminality, Name: "Wanted Poster", Emoji: "📜", Price: 500, Description: "Every outlaw's face eventually ends up here. (+4 LUK)", EffectType: "equipment", Droppable: false, Category: Equipment, EquipSlot: "trinket", StatLUK: 4, ShopExcluded: true},
	{ID: "reinforced_badge", Source: SourceCriminality, Name: "Reinforced Badge", Emoji: "⭐", Price: 3000, Description: "A badge that has stopped a knife or two. (+6 VIT, +2 STR)", EffectType: "equipment", Droppable: false, Category: Equipment, EquipSlot: "trinket", StatVIT: 6, StatSTR: 2, ShopExcluded: true},
	{ID: "bounty_scope", Source: SourceCriminality, Name: "Bounty Scope", Emoji: "🔭", Price: 12000, Description: "It never loses a trail. (+6 DEX, +4 LUK)", EffectType: "equipment", Droppable: false, Category: Equipment, EquipSlot: "trinket", StatDEX: 6, StatLUK: 4, ShopExcluded: true},
	{ID: "lawbringer_seal", Source: SourceCriminality, Name: "Lawbringer's Seal", Emoji: "📯", Price: 40000, Description: "The authority of the Iron Lodge itself. (+8 VIT, +4 STR, +2 LUK)", EffectType: "equipment", Droppable: false, Category: Equipment, EquipSlot: "trinket", StatVIT: 8, StatSTR: 4, StatLUK: 2, ShopExcluded: true},

	// --- Thieves' Guild tools (The Whisper) ---
	{ID: "lockpick_set", Source: SourceCriminality, Name: "Lockpick Set", Emoji: "🔓", Price: 100, Description: "Every lock has a secret. This finds it. (+3 DEX, +1 LUK)", EffectType: "equipment", Droppable: false, Category: Equipment, EquipSlot: "trinket", StatDEX: 3, StatLUK: 1, ShopExcluded: true},
	{ID: "smoke_pellet", Source: SourceCriminality, Name: "Smoke Pellet", Emoji: "💨", Price: 500, Description: "A quick getaway in a tiny ball. (+4 DEX)", EffectType: "equipment", Droppable: false, Category: Equipment, EquipSlot: "trinket", StatDEX: 4, ShopExcluded: true},
	{ID: "shadow_cloak", Source: SourceCriminality, Name: "Shadow Cloak", Emoji: "🌑", Price: 3000, Description: "Woven from the night itself. (+6 VIT, +4 DEX)", EffectType: "equipment", Droppable: false, Category: Equipment, EquipSlot: "armor", StatVIT: 6, StatDEX: 4, ShopExcluded: true},
	{ID: "silent_steps", Source: SourceCriminality, Name: "Silenced Footsteps", Emoji: "👣", Price: 12000, Description: "Boots that never make a sound. (+6 DEX, +4 VIT)", EffectType: "equipment", Droppable: false, Category: Equipment, EquipSlot: "trinket", StatDEX: 6, StatVIT: 4, ShopExcluded: true},
	{ID: "master_key", Source: SourceCriminality, Name: "Master Key", Emoji: "🗝️", Price: 40000, Description: "It opens doors that don't exist. (+8 LUK, +4 DEX, +2 INT)", EffectType: "equipment", Droppable: false, Category: Equipment, EquipSlot: "trinket", StatLUK: 8, StatDEX: 4, StatINT: 2, ShopExcluded: true},

	// --- Trinkets (Boss League rewards, Lv 15 Epic) ---
	{ID: "spark_shard", Source: SourceBoss, Name: "Spark Shard", Emoji: "⚡", Price: 0, Description: "A crackling fragment of Vezir's lightning. (+5 STR, +2 VIT)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityEpic, MinLevel: 15, EquipSlot: "trinket", StatSTR: 5, StatVIT: 2, ShopExcluded: true},
	{ID: "stone_heart", Source: SourceBoss, Name: "Stone Heart", Emoji: "🪨", Price: 0, Description: "Tal'Rok's core, dense with resolve. (+4 DEX, +4 VIT)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityEpic, MinLevel: 15, EquipSlot: "trinket", StatDEX: 4, StatVIT: 4, ShopExcluded: true},
	{ID: "storm_core", Source: SourceBoss, Name: "Storm Core", Emoji: "🌪️", Price: 0, Description: "Kael's fury, captured in crystal. (+5 DEX, +3 LUK)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityEpic, MinLevel: 15, EquipSlot: "trinket", StatDEX: 5, StatLUK: 3, ShopExcluded: true},
	{ID: "abyss_pearl", Source: SourceBoss, Name: "Abyss Pearl", Emoji: "🫧", Price: 0, Description: "Vorgath's gift from the deep. (+6 INT, +3 LUK)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityEpic, MinLevel: 15, EquipSlot: "trinket", StatINT: 6, StatLUK: 3, ShopExcluded: true},
	{ID: "phoenix_crest", Source: SourceBoss, Name: "Phoenix Crest", Emoji: "🔥", Price: 0, Description: "Solaris' flame, now yours. (+5 STR, +4 INT, +3 VIT, +3 LUK)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityEpic, MinLevel: 15, EquipSlot: "trinket", StatSTR: 5, StatINT: 4, StatVIT: 3, StatLUK: 3, ShopExcluded: true},

	// --- Delve quest rewards ---
	// Lost Warden questline reward: a token of the Warden's trust (mid-game).
	{ID: "warden_badge", Source: SourceQuest, Name: "Warden's Badge", Emoji: "⚜️", Price: 0, Description: "The sigil of a guardian who lost everything. It still watches. (+4 STR, +3 VIT)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityRare, MinLevel: 10, EquipSlot: "trinket", StatSTR: 4, StatVIT: 3, ShopExcluded: true},
	// Chronicler "The Last Page" reward: the book that never runs out of pages.
	{ID: "chronicler_relic", Source: SourceQuest, Name: "Chronicler's Relic", Emoji: "📖", Price: 0, Description: "The book the Chronicler closed and left behind. Its pages fill with your name. (+8 INT, +5 VIT, +4 LUK)", EffectType: "equipment", Droppable: false, Category: Equipment, Rarity: RarityLegendary, MinLevel: 20, EquipSlot: "trinket", StatINT: 8, StatVIT: 5, StatLUK: 4, ShopExcluded: true},

	// --- Veil Rift Legendary Set (Lv 25) ---
	{ID: "rift_blade", Source: SourceVeil, Name: "Rift-Tempered Blade", Emoji: "⚔️", Price: 8000, Description: "A blade forged in the space between worlds. Part of the Rift Walker set.", EffectType: "equipment", Droppable: false, Category: Equipment, MinLevel: 25, EquipSlot: "weapon", StatSTR: 16, StatDEX: 10, SetID: "rift_walker", SetName: "Rift Walker"},
	{ID: "dechirure_scythe", Source: SourceVeil, Name: "Scythe of the Sundered Veil", Emoji: "🜁", Price: 8500, Description: "Forged from a shard of Déchirure's own form. Part of the Rift Walker set.", EffectType: "equipment", Droppable: false, Category: Equipment, MinLevel: 25, EquipSlot: "weapon", StatSTR: 14, StatINT: 14, SetID: "rift_walker", SetName: "Rift Walker"},
	{ID: "rift_cowl", Source: SourceVeil, Name: "Cowl of the Veil Walker", Emoji: "👑", Price: 7500, Description: "Woven from threads of fractured reality. Part of the Rift Walker set.", EffectType: "equipment", Droppable: false, Category: Equipment, MinLevel: 25, EquipSlot: "armor", StatVIT: 14, StatDEX: 6, SetID: "rift_walker", SetName: "Rift Walker"},
	{ID: "rift_warden_aegis", Source: SourceVeil, Name: "Aegis of the Rift Warden", Emoji: "🛡️", Price: 7800, Description: "Forged from crystallized dimensional tears. Part of the Rift Walker set.", EffectType: "equipment", Droppable: false, Category: Equipment, MinLevel: 25, EquipSlot: "armor", StatVIT: 14, StatSTR: 8, SetID: "rift_walker", SetName: "Rift Walker"},
	{ID: "rift_band", Source: SourceVeil, Name: "Band of Dimensional Passage", Emoji: "💍", Price: 7000, Description: "A ring that hums with a thousand planes. Part of the Rift Walker set.", EffectType: "equipment", Droppable: false, Category: Equipment, MinLevel: 25, EquipSlot: "jewelry", StatLUK: 10, StatSTR: 3, StatDEX: 3, StatINT: 3, StatVIT: 3, SetID: "rift_walker", SetName: "Rift Walker"},
	{ID: "rift_eye", Source: SourceVeil, Name: "Eye of the Rift", Emoji: "👁️", Price: 7200, Description: "It sees what should not be seen. Part of the Rift Walker set.", EffectType: "equipment", Droppable: false, Category: Equipment, MinLevel: 25, EquipSlot: "trinket", StatINT: 10, StatVIT: 8, SetID: "rift_walker", SetName: "Rift Walker"},
}
