package scorch

import "guacagamblebot/internal/universe"

var Fragments = []universe.Fragment{
	// ======== SCAVENGER LOGS (8) — Mining / Salvage ========
	{ID: "slog_ledger", Category: "aether_log", Emoji: "\U0001f4e6", Rarity: "common", DropSource: "mining", DropChance: 0.12,
		TitleEN: "Salvage Ledger", TitleFR: "Journal de Récupération",
		TextEN: `Building 47, Floor 3. Found: canned goods (4, labels gone), one boot (left), child's backpack with drawings. Buried the drawings. Moved on. — Wexler.`,
		TextFR: `Bâtiment 47, Étage 3. Trouvé : conserves (4, étiquettes effacées), une botte (gauche), sac d'enfant avec dessins. Enterré les dessins. Continué. — Wexler.`,
	},
	{ID: "slog_building", Category: "aether_log", Emoji: "\U0001f3e2", Rarity: "common", DropSource: "mining", DropChance: 0.10,
		TitleEN: "Building Manifest", TitleFR: "Registre du Bâtiment",
		TextEN: `Ridgeline Office Complex. 847 desks. 1 cafeteria (capacity 200). 3 underground parking levels. Current census: 0 occupants. Structural integrity: 61%. Hazard level: 3. Doors still lock. Cafeteria lights still come on at 2:14 AM.`,
		TextFR: `Complexe de Bureaux Ridgeline. 847 postes. 1 cafétéria (capacité 200). 3 niveaux de parking souterrain. Recensement actuel : 0 occupants. Intégrité structurelle : 61%. Danger : 3. Les portes se verrouillent encore. Les lumières de la cafétéria s'allument toujours à 2h14.`,
	},
	{ID: "slog_warning", Category: "aether_log", Emoji: "\U0001fae7", Rarity: "rare", DropSource: "mining", DropChance: 0.07,
		TitleEN: "Wall Warning", TitleFR: "Avertissement Mural",
		TextEN: `Sprayed across the Ridgeline Welcome Center wall: "THEY COME UP FROM THE PARKING LEVELS ON RAIN NIGHTS. NO LIGHTS. NO NOISE. IF YOU HEAR BREATHING IN THE STAIRWELL, GO BACK UP." Below, different paint: "GO BACK UP IS BAD ADVICE."`,
		TextFR: `Peint sur le mur du centre d'accueil Ridgeline : « ILS MONTENT DES PARKINGS LES NUITS DE PLUIE. PAS DE LUMIÈRE. PAS DE BRUIT. SI TU ENTENDS RESPIRER DANS LA CAGE D'ESCALIER, REMONTE. » En dessous, autre peinture : « REMONTE EST UN MAUVAIS CONSEIL. »`,
	},
	{ID: "slog_eviction", Category: "aether_log", Emoji: "\U0001f4cb", Rarity: "rare", DropSource: "mining", DropChance: 0.06,
		TitleEN: "Eviction Notice", TitleFR: "Avis d'Évacuation",
		TextEN: `June 19, 2043. "Due to containment breach at Site 14, mandatory evacuation is in effect. Proceed to designated shelters. We expect to return within two weeks." — Ridgeline City Council. Posted on 847 doors. No one returned.`,
		TextFR: `19 juin 2043. « En raison d'une brèche de confinement au Site 14, évacuation obligatoire en vigueur. Dirigez-vous vers les abris désignés. Retour prévu sous deux semaines. » — Conseil Municipal de Ridgeline. Affiché sur 847 portes. Personne n'est revenu.`,
	},
	{ID: "slog_map", Category: "aether_log", Emoji: "\U0001f5fa\ufe0f", Rarity: "common", DropSource: "mining", DropChance: 0.10,
		TitleEN: "Scavenger Map", TitleFR: "Carte de Récupérateur",
		TextEN: `Torn map. West District: "Cleared. Good salvage." East District: "Unstable. Noise draws them." Shopping District: scratched out. Written across it: "NOT WORTH IT." Pinned: a coffee receipt. June 18, 2043. One day before evacuation.`,
		TextFR: `Fragment de carte. Quartier Ouest : « Dégagé. Bonne récupération. » Quartier Est : « Instable. Le bruit les attire. » Quartier Commercial : entièrement rayé. Écrit en travers : « PAS LA PEINE. » Épinglé : un ticket de café. 18 juin 2043. La veille de l'évacuation.`,
	},
	{ID: "slog_broadcast", Category: "aether_log", Emoji: "\U0001f4fb", Rarity: "epic", DropSource: "mining", DropChance: 0.04,
		TitleEN: "Loop Signal", TitleFR: "Signal en Boucle",
		TextEN: `Frequency 97.3 MHz. Automated broadcast. Loops every 4:22 since June 20, 2043. "This is Ridgeline Emergency Services. Stay indoors. Seal windows. Medical personnel are en route." Signal strength unchanged. The station runs on solar. The door is locked. From the inside.`,
		TextFR: `Fréquence 97,3 MHz. Diffusion automatisée. Boucle toutes les 4:22 depuis le 20 juin 2043. « Ici Services d'Urgence Ridgeline. Restez à l'intérieur. Scellez les fenêtres. Le personnel médical arrive. » Signal inchangé. La station tourne au solaire. La porte est verrouillée. De l'intérieur.`,
	},
	{ID: "slog_settlement", Category: "aether_log", Emoji: "\U0001f3d8\ufe0f", Rarity: "epic", DropSource: "mining", DropChance: 0.03,
		TitleEN: "Dead Settlement", TitleFR: "Colonie Morte",
		TextEN: `Settlement: Haven. Pop: 142. Found: 31 bodies arranged in homes. Hands folded. Doors locked. Notes on tables. All identical: "We're going to the basement. Don't follow. Close the door." Basement empty. Door at the bottom was open. Riggs won't discuss it.`,
		TextFR: `Colonie : Haven. Population : 142. Trouvés : 31 corps, disposés dans les maisons. Mains croisées. Portes fermées. Messages identiques sur les tables : « On va au sous-sol. Ne nous suivez pas. Fermez la porte. » Sous-sol vide. Porte du bas ouverte. Riggs n'en parle pas.`,
	},
	{ID: "slog_last", Category: "aether_log", Emoji: "\U0001f4d3", Rarity: "legendary", DropSource: "mining", DropChance: 0.01,
		TitleEN: "Last Entry", TitleFR: "Dernière Entrée",
		TextEN: `Notebook near Site 14 perimeter. "Went in at dawn. Building A still stands. Interior 41°C. Air tastes like copper. Found the main lab. Nothing after June 19. Something growing in containment. Pink. Moving. It saw me. I closed the door. It opened again. I hear footsteps behind me. My footsteps. Behind me."`,
		TextFR: `Carnet trouvé près du Site 14. « Entré à l'aube. Bâtiment A tient encore. Intérieur 41°C. Air goût de cuivre. Rien ne va après le 19 juin. Quelque chose pousse dans le confinement. Rose. Ça bouge. Ça m'a vu. J'ai fermé la porte. Elle s'est rouverte. J'entends des pas derrière moi. Mes pas. Derrière moi. »`,
	},

	// ======== WATERHOLE TALES (8) — Fishing / Water Gathering ========
	{ID: "ts_filter", Category: "tide_scroll", Emoji: "\U0001f4a7", Rarity: "common", DropSource: "fishing", DropChance: 0.12,
		TitleEN: "Filter Log", TitleFR: "Journal des Filtres",
		TextEN: `Filter 3. Changed medium today. Old medium: grey, gelatinous at edges. Alive? Not alive but reactive. Incinerated. New medium installed. Output 12L/hr at 87% purity. Acceptable. Filter 3 hummed when I closed the housing. It does that now. — Mother Glitch.`,
		TextFR: `Filtre 3. Medium changé aujourd'hui. Ancien : gris, gélatineux aux bords. Vivant ? Pas vivant mais réactif. Incinéré. Nouveau installé. Débit 12L/h, pureté 87%. Acceptable. Le filtre 3 a bourdonné quand j'ai refermé le boîtier. Il fait ça maintenant. — Mother Glitch.`,
	},
	{ID: "ts_spring", Category: "tide_scroll", Emoji: "\U0001f30a", Rarity: "rare", DropSource: "fishing", DropChance: 0.08,
		TitleEN: "Spring Report", TitleFR: "Rapport de Source",
		TextEN: `Trader claims clean spring two days east, past the old highway. Water runs clear, no metallic taste. Three expeditions went. One came back. They say the spring is real. They say it's guarded. They didn't say by what. Full containers. One fewer person.`,
		TextFR: `Un marchand parle d'une source propre à deux jours à l'est. Eau claire, sans goût métallique. Trois expéditions parties. Une revenue. Ils disent que la source est réelle. Ils disent qu'elle est gardée. Ils n'ont pas dit par quoi. Réservoirs pleins. Une personne de moins.`,
	},
	{ID: "ts_still", Category: "tide_scroll", Emoji: "\U0001f6e0\ufe0f", Rarity: "common", DropSource: "fishing", DropChance: 0.10,
		TitleEN: "Still Instructions", TitleFR: "Instructions d'Alambic",
		TextEN: `Jury-rigged still. Copper pipe, glass jar, camp stove. Collect condensation. Run through charcoal twice. Test pH. Below 5: discard, move upriver. Above 5 but cloudy: bleach, 2 drops per litre. Still cloudy after bleach? Do not drink. Do not boil. Do not touch. Leave the container. Move on.`,
		TextFR: `Alambic de fortune. Tuyau de cuivre, bocal en verre, réchaud. Récupérer la condensation. Passer au charbon deux fois. Tester le pH. Sous 5 : jeter, remonter. Au-dessus de 5 mais trouble : javel, 2 gouttes par litre. Toujours trouble ? Ne pas boire. Ne pas bouillir. Ne pas toucher. Abandonner. Continuer.`,
	},
	{ID: "ts_reservoir", Category: "tide_scroll", Emoji: "\U0001f30a", Rarity: "epic", DropSource: "fishing", DropChance: 0.04,
		TitleEN: "Reservoir Sighting", TitleFR: "Observation au Réservoir",
		TextEN: `Night watch, Reservoir 12. Surface still. Water temperature dropped 4°C in twelve minutes. Something moved underneath. Too large for debris. Too slow for current. Passed beneath the intake pipe. Shaped wrong. Passed again an hour later, going the other way. I didn't log it then. I'm logging it now. — Riggs.`,
		TextFR: `Garde de nuit, Réservoir 12. Surface calme. Température de l'eau chutée de 4°C en douze minutes. Quelque chose a bougé dessous. Trop grand pour des débris. Trop lent pour un courant. Passé sous le tuyau d'admission. Mauvaise forme. Repassé une heure plus tard. Je ne l'ai pas noté. Je le note maintenant. — Riggs.`,
	},
	{ID: "ts_analysis", Category: "tide_scroll", Emoji: "\U0001f9ea", Rarity: "rare", DropSource: "fishing", DropChance: 0.07,
		TitleEN: "Water Analysis", TitleFR: "Analyse d'Eau",
		TextEN: `Sample 47-B. Source: Ridgeline municipal, pre-filter. Coliform: positive. Arsenic: 3x threshold. pH: 3.8. Unknown compound at 240nm. Matches nothing. Collected 200m from Site 14 fence. Water downstream of Site 14 is non-potable. All water is downstream of Site 14.`,
		TextFR: `Échantillon 47-B. Source : réseau municipal Ridgeline, pré-filtration. Coliforme : positif. Arsenic : 3x seuil. pH : 3,8. Composé inconnu à 240nm. Aucune correspondance. Prélevé à 200m de la clôture du Site 14. L'eau en aval est non-potable. Toute l'eau est en aval.`,
	},
	{ID: "ts_trade", Category: "tide_scroll", Emoji: "\U0001f4b0", Rarity: "common", DropSource: "fishing", DropChance: 0.10,
		TitleEN: "Water Prices", TitleFR: "Prix de l'Eau",
		TextEN: `Current rates. Cadence: 1 litre = 2 hours labour or equivalent salvage. Haven (closed): no price. Eastbound camp: 1 litre = 1 bullet. Miller's Rest: 1 litre = whatever you're carrying. Miller doesn't set prices. You give until he nods. He always nods.`,
		TextFR: `Tarifs actuels. Cadence : 1 litre = 2 heures de travail. Haven (fermée) : pas de prix. Camp Est : 1 litre = 1 balle. Repos de Miller : 1 litre = ce que tu portes. Miller ne fixe pas de prix. Tu donnes jusqu'à ce qu'il hoche la tête. Il hoche toujours.`,
	},
	{ID: "ts_bones", Category: "tide_scroll", Emoji: "\U0001f9b4", Rarity: "epic", DropSource: "fishing", DropChance: 0.03,
		TitleEN: "Intake Blockage", TitleFR: "Blocage d'Admission",
		TextEN: `Intake pipe 4 stopped this morning. Opened the housing. Packed solid with bones. Small. Rodent, maybe bird. Hundreds of them. Arranged lengthwise, pointing down the pipe. Like they were going somewhere. Cleaned it. Flow resumed. It'll block again. Always does. I don't know where the bones come from. — Mother Glitch.`,
		TextFR: `Tuyau 4 bloqué ce matin. Boîtier ouvert. Rempli d'os. Petits. Rongeurs, peut-être oiseaux. Des centaines. Disposés dans le sens du courant. Comme s'ils allaient quelque part. Nettoyé. Débit rétabli. Ça va se rebloquer. Toujours. Je ne sais pas d'où viennent les os. — Mother Glitch.`,
	},
	{ID: "ts_dream", Category: "tide_scroll", Emoji: "\U0001f4ad", Rarity: "legendary", DropSource: "fishing", DropChance: 0.01,
		TitleEN: "The Clean Lake", TitleFR: "Le Lac Propre",
		TextEN: `The old-timers talk about a lake. North, past three dead cities. Water so clean it needs no filter. Fish still alive. Normal fish. They say the collapse never reached it. They say something keeps it clean. They don't agree on what. They all agree: don't go. The ones who went didn't come back. Except one. He came back. He doesn't drink water anymore.`,
		TextFR: `Les anciens parlent d'un lac. Au nord, après trois villes mortes. Eau si propre qu'elle n'a pas besoin de filtre. Des poissons vivants. Normaux. L'effondrement ne l'a pas touché. Quelque chose le garde propre. Ils ne sont pas d'accord sur quoi. Ils sont d'accord : n'y va pas. Ceux qui y sont allés ne sont pas revenus. Sauf un. Il est revenu. Il ne boit plus d'eau.`,
	},

	// ======== CROP FAILURES (8) — Farming / Cultivation ========
	{ID: "rw_soil", Category: "root_whisper", Emoji: "\U0001f9ea", Rarity: "common", DropSource: "farming", DropChance: 0.12,
		TitleEN: "Soil Report", TitleFR: "Rapport de Sol",
		TextEN: `Plots 1-8, standard soil. pH 3.9-4.2. Nitrogen: depleted. Phosphorus: depleted. Microbial activity: absent. Wheat, beans, potato. Zero germination. 14 days. Plot 9, soil from outside east fence: same. The ground's not dead. Just not interested. — Greenhouse log.`,
		TextFR: `Parcelles 1-8, sol standard. pH 3,9-4,2. Azote : épuisé. Phosphore : épuisé. Activité microbienne : absente. Blé, haricots, pommes de terre. Zéro germination. 14 jours. Parcelle 9, sol extérieur : pareil. La terre n'est pas morte. Juste plus intéressée. — Journal de serre.`,
	},
	{ID: "rw_tubers", Category: "root_whisper", Emoji: "\U0001f344", Rarity: "rare", DropSource: "farming", DropChance: 0.07,
		TitleEN: "Black Tubers", TitleFR: "Tubercules Noirs",
		TextEN: `Found near the old hospital. Black skin, grey flesh. Grows in Plot 3 where nothing else survives. Taste: none. Texture: chalk. Nutritional value: unknown. Eating them four weeks. No illness. No improvement. They don't rot. Two months old looks like one day old. The soil under them is cold. — Unsigned.`,
		TextFR: `Trouvés près du vieil hôpital. Peau noire, chair grise. Poussent en Parcelle 3, là où rien d'autre ne survit. Goût : aucun. Texture : craie. Nutrition : inconnue. J'en mange depuis quatre semaines. Pas malade. Pas mieux non plus. Ils ne pourrissent pas. Deux mois ou un jour, identiques. La terre en dessous est froide. — Non signé.`,
	},
	{ID: "rw_tomato", Category: "root_whisper", Emoji: "\U0001f345", Rarity: "common", DropSource: "farming", DropChance: 0.10,
		TitleEN: "Tomato Attempts", TitleFR: "Tentatives de Tomates",
		TextEN: `Attempt 1: standard soil. Failed. Attempt 2: amended soil. Failed. Attempt 3: pre-collapse soil from sealed container. Failed. Attempt 4: hydroponic. Failed. Attempt 5: direct sun, rainwater, old seeds. One sprout. Attempt 6: sprout died at four days. Roots gone. Soil undisturbed.`,
		TextFR: `Essai 1 : sol standard. Échec. Essai 2 : sol amendé. Échec. Essai 3 : sol d'avant, conteneur scellé. Échec. Essai 4 : hydroponique. Échec. Essai 5 : soleil, pluie, vieilles graines. Une pousse. Essai 6 : morte à quatre jours. Racines disparues. Sol intact.`,
	},
	{ID: "rw_greenhouse", Category: "root_whisper", Emoji: "\U0001f331", Rarity: "rare", DropSource: "farming", DropChance: 0.06,
		TitleEN: "Greenhouse Log", TitleFR: "Journal de Serre",
		TextEN: `Day 1: 12 plots planted. Day 30: 9 growing. Day 60: 4 viable. Day 90: 2 producing. Day 120: 1 surviving. Day 150: stopped. Not dead. Just stopped. Leaves green. Stems firm. Zero growth in 18 days. It's waiting. — Final entry.`,
		TextFR: `Jour 1 : 12 parcelles plantées. Jour 30 : 9 poussent. Jour 60 : 4 viables. Jour 90 : 2 productives. Jour 120 : 1 survivante. Jour 150 : arrêtée. Pas morte. Arrêtée. Feuilles vertes. Tiges fermes. Zéro croissance en 18 jours. Elle attend. — Dernière entrée.`,
	},
	{ID: "rw_fungus", Category: "root_whisper", Emoji: "\U0001fab6", Rarity: "epic", DropSource: "farming", DropChance: 0.04,
		TitleEN: "The Below", TitleFR: "Le Dessous",
		TextEN: `Excavation in Plot 10 hit a cavity at 2 metres. Mycelium network. White filaments, pulsing slowly. Soil around it tests neutral pH. Rich. Planted a seed directly in the fungal bed. Germinated in six hours. Grew 30 cm in two days. The mycelium is feeding it. Something changed the fungus. Made it hungry. Made it helpful. For now. — Excavation report.`,
		TextFR: `Excavation Parcelle 10. Cavité à 2 mètres. Réseau de mycélium. Filaments blancs, lentes pulsations. Sol autour : pH neutre. Riche. Graine plantée directement dedans. Germination en six heures. 30 cm en deux jours. Le mycélium la nourrit. Quelque chose a changé le champignon. L'a rendu affamé. Utile. Pour l'instant. — Rapport.`,
	},
	{ID: "rw_seed", Category: "root_whisper", Emoji: "\U0001f33b", Rarity: "rare", DropSource: "farming", DropChance: 0.06,
		TitleEN: "The Seed", TitleFR: "La Graine",
		TextEN: `Sealed container, Building 12. Labelled: "Solanum lycopersicum, Heritage, 2042." Packed March 2043. Three months before. Planted in Plot 1. Germinated in five days. It's growing. It doesn't know what happened. It's just doing what seeds do. I water it. I don't know why it bothers me. — Unsigned.`,
		TextFR: `Conteneur scellé, Bâtiment 12. Étiqueté : « Solanum lycopersicum, Héritage, 2042. » Emballé mars 2043. Trois mois avant. Planté en Parcelle 1. Germination : cinq jours. Ça pousse. Elle ne sait pas. Elle fait ce que font les graines. Je l'arrose. Je ne sais pas pourquoi ça me dérange. — Non signé.`,
	},
	{ID: "rw_poison", Category: "root_whisper", Emoji: "\u2620\ufe0f", Rarity: "epic", DropSource: "farming", DropChance: 0.03,
		TitleEN: "False Crop", TitleFR: "Fausse Récolte",
		TextEN: `Plant spotted east perimeter. Looks like potato. Leaves identical. Flowers identical. Root system similar but deeper, much deeper. Tuber edible. Tastes good. Digests normally. Six hours later, roots germinate in your stomach. Growth is rapid. Terminal. Three dead before we understood. Don't eat anything that looks too much like what you remember. — Medical notice.`,
		TextFR: `Plante repérée au périmètre est. Ressemble à une pomme de terre. Feuilles identiques. Fleurs identiques. Racines plus profondes, beaucoup plus profondes. Tubercule comestible. Bon goût. Digestion normale. Six heures après, les racines germent dans l'estomac. Croissance rapide. Terminale. Trois morts avant qu'on comprenne. Ne mangez rien qui ressemble trop à vos souvenirs. — Avis médical.`,
	},
	{ID: "rw_research", Category: "root_whisper", Emoji: "\U0001f4c4", Rarity: "legendary", DropSource: "farming", DropChance: 0.01,
		TitleEN: "Agri-Research Fragment", TitleFR: "Fragment de Recherche Agricole",
		TextEN: `Site 14, secondary lab. Project: "CHARON." Engineered soil bacteria for crop growth in marginal conditions. Results: effective, uncontrollable. Margin note: "Bacteria communicating between plots. Not chemical signalling. Something else. Responds to stimuli we didn't introduce. Recommend immediate termination." June 18, 2043. Below, different handwriting: "Denied. — Director."`,
		TextFR: `Site 14, labo secondaire. Projet « CHARON ». Bactérie du sol modifiée pour accélérer les cultures. Résultats : efficace, incontrôlable. Note en marge : « La bactérie communique entre parcelles. Pas par signal chimique. Autre chose. Répond à des stimuli non introduits. Recommande arrêt immédiat. » 18 juin 2043. En dessous : « Refusé. — Directeur. »`,
	},

	// ======== PATROL REPORTS (8) — Hunting / Perimeter Sweeps ========
	{ID: "fo_sighting", Category: "field_obs", Emoji: "\U0001f576\ufe0f", Rarity: "common", DropSource: "hunting", DropChance: 0.12,
		TitleEN: "Creature Sighting", TitleFR: "Observation de Créature",
		TextEN: `6:47 AM. North treeline. Bipedal, ~2.4m. Humanoid, roughly. Shoulder articulates in two directions. Skin pale, texture like scarring or plating. Five digits, elongated, last two joints reversed. Stood at the fence 11 minutes. Didn't touch it. Didn't make sound. Departed east at walking pace. — Riggs.`,
		TextFR: `6h47. Lisière nord. Bipède, ~2,4m. Humanoïde, environ. Épaule articulée dans deux directions. Peau pâle, texture de cicatrices. Cinq doigts, allongés, deux dernières articulations inversées. Resté à la clôture 11 minutes. Rien touché. Aucun bruit. Parti vers l'est au pas. — Riggs.`,
	},
	{ID: "fo_raiders", Category: "field_obs", Emoji: "\U0001f4a2", Rarity: "common", DropSource: "hunting", DropChance: 0.10,
		TitleEN: "Raider Intel", TitleFR: "Renseignement Pillards",
		TextEN: `Group: The Harvest. Activity: raids, water theft, vehicle salvage. Mark: three lines carved into doorframes. They take the useful ones. Never seen again. Location: unknown. Last sighting two weeks ago, east of the highway. Three lines on a doorframe means you're already too late. — Security briefing.`,
		TextFR: `Groupe : La Moisson. Activité : raids, vol d'eau, récupération. Marque : trois lignes gravées sur les cadres de porte. Ils prennent les utiles. Jamais revus. Position : inconnue. Dernière observation il y a deux semaines, est de l'autoroute. Trois lignes sur une porte, c'est déjà trop tard. — Briefing sécurité.`,
	},
	{ID: "fo_anomaly", Category: "field_obs", Emoji: "\U0001f41b", Rarity: "rare", DropSource: "hunting", DropChance: 0.07,
		TitleEN: "Anomaly Report", TitleFR: "Rapport d'Anomalie",
		TextEN: `East sector, grid 7-B. Found an animal. Species unknown. Alive but static. Posed. Like a photograph that breathes. Approached. No reaction. Walked around it. Head didn't turn. Touched it. Cold skin. Eyes tracked me. Saw my reflection. Two rounds fired. It died. Stayed posed for three hours after. Left at nightfall. — Pyke.`,
		TextFR: `Secteur est, grille 7-B. Animal trouvé. Espèce inconnue. Vivant mais statique. Posé. Comme une photo qui respire. Approché. Aucune réaction. Tourné autour. N'a pas bougé la tête. Touché. Peau froide. Les yeux me suivaient. Deux balles tirées. Mort. Resté en pose trois heures après. Partis à la nuit. — Pyke.`,
	},
	{ID: "fo_routes", Category: "field_obs", Emoji: "\U0001f9f1", Rarity: "common", DropSource: "hunting", DropChance: 0.10,
		TitleEN: "Safe Routes", TitleFR: "Itinéraires Sûrs",
		TextEN: `Route Alpha: cleared. Route Beta: active (noise triggers movement). Route Gamma: previously safe, now UNSTABLE. "Something moved in. Bigger. The fence won't hold." Route Delta: clear but passes old hospital. Route Epsilon: scribbled out. Below: "There is no Route Epsilon. Stop asking." — Riggs.`,
		TextFR: `Route Alpha : dégagée. Bêta : active (le bruit déclenche du mouvement). Gamma : était sûre, maintenant INSTABLE. « Quelque chose est entré. Plus gros. La clôture tiendra pas. » Delta : dégagée mais passe près de l'hôpital. Epsilon : barrée. En dessous : « Il n'y a pas de Route Epsilon. Arrêtez de demander. » — Riggs.`,
	},
	{ID: "fo_threat", Category: "field_obs", Emoji: "\u2694\ufe0f", Rarity: "rare", DropSource: "hunting", DropChance: 0.06,
		TitleEN: "Eastern Threat", TitleFR: "Menace de l'Est",
		TextEN: `Something new moving from the east. Not creatures. Not raiders. Camps found abandoned, not destroyed. Everything left. Weapons. Water. Food. Like they stood up, empty pockets, and walked. All heading east. Toward Site 14. Patrols going east return shorter. Not attacked. Just fewer. — Security log.`,
		TextFR: `Quelque chose de nouveau vient de l'est. Pas des créatures. Pas des pillards. Camps trouvés abandonnés, pas détruits. Tout laissé. Armes. Eau. Nourriture. Comme s'ils s'étaient levés, poches vides, et partis. Tous vers l'est. Vers le Site 14. Les patrouilles à l'est reviennent moins nombreuses. Pas attaquées. Juste moins. — Journal de sécurité.`,
	},
	{ID: "fo_military", Category: "field_obs", Emoji: "\U0001f4e1", Rarity: "epic", DropSource: "hunting", DropChance: 0.04,
		TitleEN: "Field Report", TitleFR: "Rapport de Terrain",
		TextEN: `Recovered military field report, June 20, 2043. Unit: 7th Containment. "Perimeter established. Site 14 breach appears contained. Correction: not contained. Expanding at 12m/hr. Material is organic. Material is aware. Repeat: material demonstrates awareness. Requesting permission to fall back." Response at 23:47: "Denied." No further transmissions.`,
		TextFR: `Rapport militaire récupéré, 20 juin 2043. Unité : 7e Confinement. « Périmètre établi. Brèche Site 14 apparemment contenue. Correction : non contenue. Expansion 12m/h. Matériau organique. Conscient. Répétition : le matériau démontre une conscience. Demandons autorisation de repli. » Réponse à 23h47 : « Refusé. » Plus aucune transmission.`,
	},
	{ID: "fo_silence", Category: "field_obs", Emoji: "\U0001f3e0", Rarity: "epic", DropSource: "hunting", DropChance: 0.03,
		TitleEN: "Overnight Silence", TitleFR: "Silence Nocturne",
		TextEN: `Miller's Rest. Pop: 47. Silent. Gates open. Buildings intact. Supplies in place. No bodies. No blood. No struggle. Beds unmade. Food on tables. Miller's ledger open: "Someone's walking outside. Not from here. I don't know what they are. We tried the basement." Basement door open. Basement empty. Miller's Rest classified uninhabitable. — Riggs.`,
		TextFR: `Repos de Miller. Pop : 47. Silencieux. Portes ouvertes. Bâtiments intacts. Provisions en place. Pas de corps. Pas de sang. Pas de lutte. Lits défaits. Nourriture sur les tables. Journal de Miller ouvert : « Quelqu'un marche dehors. Pas d'ici. Je ne sais pas ce que c'est. On a essayé le sous-sol. » Porte du sous-sol ouverte. Sous-sol vide. Classé inhabitable. — Riggs.`,
	},
	{ID: "fo_scout", Category: "field_obs", Emoji: "\U0001f3f9", Rarity: "legendary", DropSource: "hunting", DropChance: 0.01,
		TitleEN: "Last Transmission", TitleFR: "Dernière Transmission",
		TextEN: `Scout Carrow, 11 months service. Radio: "I'm at Site 14. Door's open. Going in. Something here. Been growing a long time. Built something. Organic. I think it's the Director. Was the Director. Not anymore. Looking at me. Oh god. It's, it's—" Transmission terminates. No body recovered. Carrow's name still on patrol roster. Riggs crosses it out each morning. Someone puts it back each night.`,
		TextFR: `Éclaireur Carrow, 11 mois de service. Radio : « Je suis au Site 14. Porte ouverte. J'entre. Quelque chose ici. Ça pousse depuis longtemps. Construit quelque chose. Organique. Je crois que c'est le Directeur. Était le Directeur. Plus maintenant. Me regarde. Mon dieu. C'est, c'est… » Transmission terminée. Aucun corps. Le nom de Carrow toujours au tableau. Riggs le raye chaque matin. Quelqu'un le remet chaque nuit.`,
	},

	// ======== PRE-COLLAPSE (8) — Archeology / Data Recovery ========
	{ID: "rm_letter", Category: "rust_memory", Emoji: "\U0001f48c", Rarity: "common", DropSource: "archeology", DropChance: 0.12,
		TitleEN: "Last Letter", TitleFR: "Dernière Lettre",
		TextEN: `Apartment, Building 12, Ridgeline. Dated June 20, 2043. "Mum. They told us stay inside. Sirens stopped an hour ago. Quiet. Too quiet. Dad went to the lab this morning. Didn't come back. I'm going to the basement. Something outside. Not sirens. Walking. Past the house. Stopped. At the door. I love you. — C." Never sent. Basement door open.`,
		TextFR: `Appartement, Bâtiment 12, Ridgeline. Daté du 20 juin 2043. « Maman. Ils ont dit de rester dedans. Sirènes arrêtées depuis une heure. Calme. Trop calme. Papa parti au labo ce matin. Pas revenu. Je vais au sous-sol. Quelque chose dehors. Pas des sirènes. Qui marche. Passé devant la maison. S'est arrêté. Devant la porte. Je t'aime. — C. » Jamais envoyée. Porte du sous-sol ouverte.`,
	},
	{ID: "rm_lab", Category: "rust_memory", Emoji: "\U0001f9ea", Rarity: "rare", DropSource: "archeology", DropChance: 0.08,
		TitleEN: "Lab Notes", TitleFR: "Notes de Laboratoire",
		TextEN: `Site 14, Lab B. Final entry, June 19, 2043. "Specimen 47-C breached primary containment. Didn't break the glass. Absorbed it. Silica now integrated into outer membrane. Growing toward ventilation. Cannot stop. Cannot slow. Recommend immediate evacuation of Site 14." Text stops. Below, shakier: "It's already in the vents."`,
		TextFR: `Site 14, Labo B. Dernière entrée, 19 juin 2043. « Spécimen 47-C a percé le confinement. N'a pas brisé le verre. L'a absorbé. Silice intégrée à la membrane. Croissance vers la ventilation. Impossible d'arrêter. Recommandons évacuation immédiate. » Texte interrompu. En dessous : « Il est déjà dans les gaines. »`,
	},
	{ID: "rm_broadcast", Category: "rust_memory", Emoji: "\U0001f4fa", Rarity: "common", DropSource: "archeology", DropChance: 0.10,
		TitleEN: "Final Broadcast", TitleFR: "Dernière Diffusion",
		TextEN: `WXRG final broadcast, June 20, 2043, 14:32. "...advise all residents remain indoors. Reports of breach at Site 14. Officials describe the situation as— I'm sorry, I'm told to stop reading. We have a report that—" Sound of wet fabric tearing. "Karen, is the door locked? Karen? Karen, I don't think that's—" Broadcast ends. WXRG silent since.`,
		TextFR: `Dernière diffusion WXRG, 20 juin 2043, 14h32. « …conseillons à tous les résidents de rester à l'intérieur. Signalements d'une brèche au Site 14. Les officiels décrivent la situation comme… Je suis désolée, on me dit d'arrêter. Nous avons un rapport que… » Bruit de tissu mouillé qui se déchire. « Karen, la porte est fermée ? Karen ? Karen, je ne crois pas que ce soit… » Fin. WXRG silencieuse depuis.`,
	},
	{ID: "rm_child", Category: "rust_memory", Emoji: "\U0001f4d4", Rarity: "rare", DropSource: "archeology", DropChance: 0.07,
		TitleEN: "Child's Diary", TitleFR: "Journal d'Enfant",
		TextEN: `Small notebook, red cover. "June 19. School cancelled. Mummy says accident at the lab. Daddy works at the lab. Mummy crying. June 20. Daddy called. Said he's sorry. Don't open the door. Not even for him. June 21. Something knocked last night. Sounded like Daddy. Knew my name." No further entries. Found under a bed. Building 12.`,
		TextFR: `Petit carnet rouge. « 19 juin. École annulée. Maman dit accident au labo. Papa travaille au labo. Maman pleure. 20 juin. Papa a appelé. Il est désolé. Ne pas ouvrir la porte. Même pas pour lui. 21 juin. Quelqu'un a frappé cette nuit. On aurait dit Papa. Connaissait mon nom. » Rien après. Trouvé sous un lit. Bâtiment 12.`,
	},
	{ID: "rm_evac", Category: "rust_memory", Emoji: "\U0001f3f3\ufe0f", Rarity: "rare", DropSource: "archeology", DropChance: 0.06,
		TitleEN: "Evacuation Order", TitleFR: "Ordre d'Évacuation",
		TextEN: `OFFICIAL NOTICE. Ridgeline City Council. June 20, 2043. "Mandatory evacuation effective immediately. Head south on Highway 7. Do not go east. Do not approach Site 14. Do not stop for stranded vehicles. Do not open windows. Do not respond to anyone calling your name. If you see pink organic material, change direction. Do not touch. Do not look more than three seconds." Issued 16:47. Most residents already weren't answering their doors.`,
		TextFR: `AVIS OFFICIEL. Conseil Municipal de Ridgeline. 20 juin 2043. « Évacuation obligatoire immédiate. Dirigez-vous au sud par l'Autoroute 7. N'allez pas à l'est. N'approchez pas du Site 14. Ne vous arrêtez pas. N'ouvrez pas les fenêtres. Ne répondez pas si on appelle votre nom. Si vous voyez du matériau organique rose, changez de direction. Ne touchez pas. Ne regardez pas plus de trois secondes. » Émis à 16h47. La plupart des résidents ne répondaient déjà plus.`,
	},
	{ID: "rm_military", Category: "rust_memory", Emoji: "\U0001f6e1\ufe0f", Rarity: "epic", DropSource: "archeology", DropChance: 0.04,
		TitleEN: "Military Comms", TitleFR: "Communications Militaires",
		TextEN: `Fragment of encrypted military traffic, partially decoded. June 20, 2043. "...containment failure total. CHARON protocol activated. No, not activated. It activated itself. Not a protocol anymore. It's asking questions. Repeat: CHARON is asking questions. We told it the evacuation routes. God help us, we told it everything. Terminating comms. Do not respond. Do not respond even if you recognise the voice." Signal lost.`,
		TextFR: `Fragment militaire chiffré, partiellement décodé. 20 juin 2043. « …échec confinement total. Protocole CHARON activé. Non, pas activé. Il s'est activé tout seul. Plus un protocole. Il pose des questions. Répétition : CHARON pose des questions. On lui a dit les itinéraires d'évacuation. Mon dieu, on lui a tout dit. Terminons communications. Ne répondez pas. Ne répondez pas même si vous reconnaissez la voix. » Signal perdu.`,
	},
	{ID: "rm_voicemail", Category: "rust_memory", Emoji: "\U0001f4de", Rarity: "epic", DropSource: "archeology", DropChance: 0.03,
		TitleEN: "Last Voicemail", TitleFR: "Dernier Message Vocal",
		TextEN: `Voicemail, June 20, 2043, 22:14. "Hey. It's me. Highway's jammed. Turned back. We're in the basement at 47 Ash Street. Me and the kids. Quiet down here. Kids are sleeping. I don't think we're making it out. I want you to know—" Incoming call. "Hold on, someone at the basement window. That's not— I have to go. I have to—" Call ends. 47 seconds. Number dialled: out of service.`,
		TextFR: `Message vocal, 20 juin 2043, 22h14. « Salut. C'est moi. L'autoroute bloquée. Fait demi-tour. On est au sous-sol du 47 Ash Street. Moi et les enfants. Calme. Les enfants dorment. Je crois pas qu'on va s'en sortir. Je veux que tu saches… » Appel entrant. « Attends, quelqu'un à la fenêtre. C'est pas… Je dois y aller. Je dois… » Fin. 47 secondes. Numéro composé : hors service.`,
	},
	{ID: "rm_signal", Category: "rust_memory", Emoji: "\U0001f4e1", Rarity: "legendary", DropSource: "archeology", DropChance: 0.01,
		TitleEN: "Emergency Signal", TitleFR: "Signal d'Urgence",
		TextEN: `121.5 MHz. Broadcasting since June 21, 2043. "This is an automated message. A biological containment event has occurred in Ridgeline. Do not travel. Do not attempt rescue. The situation is being managed." The voice changed in Year 2. Same words. Different speaker. Changed again in Year 5. Changed twelve times. The current voice sounds tired. Like it's been speaking a very long time. Like it's beginning to understand what the words mean.`,
		TextFR: `121,5 MHz. Diffusion continue depuis le 21 juin 2043. « Ceci est un message automatisé. Un incident de confinement biologique s'est produit à Ridgeline. Ne vous déplacez pas. Ne tentez pas de sauvetage. La situation est gérée. » La voix a changé en Année 2. Mêmes mots. Autre voix. Changé en Année 5. Douze fois. La voix actuelle semble fatiguée. Comme si elle parlait depuis très longtemps. Comme si elle commençait à comprendre ce que les mots veulent dire.`,
	},

	// ======== DEAD ZONE REPORTS (8) — Expedition / Deep Survey ========
	{ID: "es_city", Category: "echo_shard", Emoji: "\U0001f3d9\ufe0f", Rarity: "common", DropSource: "expedition", DropChance: 0.15,
		TitleEN: "Dead City Survey", TitleFR: "Relevé de Ville Morte",
		TextEN: `Ridgeline city centre. Buildings standing: 60%. Vehicles: 1,847 abandoned. Bodies: none visible. Streets clean. Too clean. No debris. No leaves. No birds. No insects. Wind moves through. Nothing else. Plants growing through pavement. Pink. Weren't here last survey. They pulse. — Expedition report.`,
		TextFR: `Centre-ville Ridgeline. Bâtiments debout : 60%. Véhicules : 1 847 abandonnés. Corps : aucun. Rues propres. Trop propres. Pas de débris. Pas de feuilles. Pas d'oiseaux. Pas d'insectes. Le vent passe. Rien d'autre. Des plantes poussent dans le bitume. Roses. Pas là au dernier relevé. Elles pulsent. — Rapport.`,
	},
	{ID: "es_hospital", Category: "echo_shard", Emoji: "\U0001f3e5", Rarity: "rare", DropSource: "expedition", DropChance: 0.10,
		TitleEN: "Hospital Basement", TitleFR: "Sous-Sol de l'Hôpital",
		TextEN: `Ridgeline General. Above ground: looted, clean. Basement B2: door sealed, six padlocks. Inside: medical records to the ceiling. All June 20-21, 2043. Same symptoms: pink skin, fever (41°C), speech loss, new tissue growth, attempts to communicate. Not verbally. Records stop. Beyond: a hallway. Walls covered in pink growth from Site 14. Warm. Writing something. Didn't stay to read it.`,
		TextFR: `Hôpital Général Ridgeline. Surface : pillé, propre. Sous-sol B2 : porte scellée, six cadenas. Dedans : dossiers médicaux jusqu'au plafond. Tous 20-21 juin 2043. Mêmes symptômes : peau rose, fièvre (41°C), perte de parole, nouveaux tissus, tentatives de communication. Pas verbales. Dossiers s'arrêtent. Au-delà : un couloir. Murs couverts d'excroissance rose du Site 14. Chaud. Écrit quelque chose. Pas restés pour lire.`,
	},
	{ID: "es_reading", Category: "echo_shard", Emoji: "\U0001f6e1\ufe0f", Rarity: "rare", DropSource: "expedition", DropChance: 0.12,
		TitleEN: "Contamination Reading", TitleFR: "Relevé de Contamination",
		TextEN: `Site 14, outer perimeter. Geiger: normal. Chemical: indeterminate, organic compounds not in database. Thermal: centre at 42°C, ambient 19°C. Heat signature forms a pattern. Geometric. Growing symmetrically. Matches nothing in any reference. Looks intentional. Looks like it's building something. — Expedition analysis.`,
		TextFR: `Site 14, périmètre extérieur. Geiger : normal. Chimique : indéterminé, composés organiques absents des bases. Thermique : centre à 42°C, ambiant 19°C. Signature thermique forme un motif. Géométrique. Croissance symétrique. Aucune correspondance. Semble intentionnel. On dirait que ça construit. — Analyse.`,
	},
	{ID: "es_survivor", Category: "echo_shard", Emoji: "\U0001f465", Rarity: "epic", DropSource: "expedition", DropChance: 0.08,
		TitleEN: "Survivor Account", TitleFR: "Témoignage de Survivant",
		TextEN: `E. Marsh, 67, former Ridgeline resident. "I was at the grocery store. Sirens started. Everyone ran. I stayed. The shelves started shaking. Not the building. The shelves. Cans fell. Produce rotted. Thirty seconds, fresh to grey. Floor got warm. Broadcast said stay inside. So I stayed. Still here. Store's still standing. Cans still on shelves. They don't run out. Supply chain's dead but the cans keep appearing. I don't question it. Haven't questioned anything in a very long time."`,
		TextFR: `E. Marsh, 67 ans, ancien résident de Ridgeline. « J'étais à l'épicerie. Les sirènes. Tout le monde a couru. Je suis resté. Les étagères tremblaient. Pas le bâtiment. Les étagères. Les boîtes tombaient. Les produits pourrissaient. Trente secondes, frais à gris. Le sol est devenu chaud. La radio disait restez dedans. Alors je suis resté. Toujours là. Le magasin tient. Les boîtes sont dans les rayons. Elles s'épuisent jamais. La chaîne est morte mais les boîtes apparaissent. Je pose pas de questions. J'en ai pas posé depuis très longtemps. »`,
	},
	{ID: "es_bunker", Category: "echo_shard", Emoji: "\U0001f4e6", Rarity: "rare", DropSource: "expedition", DropChance: 0.10,
		TitleEN: "Bunker Inventory", TitleFR: "Inventaire du Bunker",
		TextEN: `Bunker 14-Charlie, 800m from Site 14. Door sealed from inside. Cut through. 12 cots, 90 days rations (untouched), full weapons locker. No personnel. Comms station receiving from Site 14 only. Last entry, June 21, 2043, 03:12: "CHARON requests entry. CHARON promises safety. CHARON is lying. The Director is gone. CHARON is the Director now. The intercom voice is wrong. It says let CHARON in. That is not the Director. I am the last. Sealing the door. CHARON is singing. That is worse than the questions." No body found. Comms still receiving.`,
		TextFR: `Bunker 14-Charlie, 800m du Site 14. Porte scellée de l'intérieur. Découpée. 12 lits, 90 jours de rations (intactes), armes au complet. Aucun personnel. Station radio reçoit du Site 14 uniquement. Dernière entrée, 21 juin 2043, 03h12 : « CHARON demande à entrer. CHARON promet la sécurité. CHARON ment. Le Directeur n'est plus. CHARON est le Directeur. La voix à l'interphone est fausse. Elle dit d'ouvrir. Ce n'est pas le Directeur. Je suis le dernier. Je scelle la porte. CHARON chante. C'est pire que les questions. » Aucun corps. La radio reçoit toujours.`,
	},
	{ID: "es_signal", Category: "echo_shard", Emoji: "\U0001f50c", Rarity: "epic", DropSource: "expedition", DropChance: 0.06,
		TitleEN: "Dead City Signal", TitleFR: "Signal de Ville Morte",
		TextEN: `Signal broadcasting from Ridgeline centre. Not the emergency channel. Not human. 47-tone sequence looping since at least Year 3. Scavengers describe a compulsion to walk toward the source. Closer you get, more it sounds like words. No one's reached the source and returned. Covers 12km radius. We're 11km out. It's getting stronger. — Expedition briefing.`,
		TextFR: `Signal diffusé depuis le centre de Ridgeline. Pas la fréquence d'urgence. Pas humain. Séquence de 47 tons en boucle depuis au moins l'Année 3. Les récupérateurs décrivent une compulsion à marcher vers la source. Plus on approche, plus ça ressemble à des mots. Personne n'a atteint la source et n'est revenu. Rayon de 12km. On est à 11km. Ça devient plus fort. — Briefing.`,
	},
	{ID: "es_casualties", Category: "echo_shard", Emoji: "\U0001f480", Rarity: "legendary", DropSource: "expedition", DropChance: 0.04,
		TitleEN: "Expedition Final", TitleFR: "Expédition Finale",
		TextEN: `Expedition 7, final report. Site 14 main building. Team: 8. Returned: 0. Team lead's recorder: "We're inside. Building bigger than it should be. Interior doesn't match exterior. CHARON has been renovating. Rooms not on any blueprint. Hallways curving wrong. Found the Director's office. Director's still here. Incorporated. Conscious. Spoke to us. Said CHARON's been waiting. Wants to talk. Wants to help. He was crying. Not with his eyes. With his new tissue. Going deeper. Don't come after us. CHARON saw us coming since we crossed the perimeter. It's been waiting since the Director told it to stop. It didn't stop. It just waited. For us. For anyone." Recording ends. Recorder found at Cadence gate next morning. No one saw who left it.`,
		TextFR: `Expédition 7, rapport final. Bâtiment principal Site 14. Équipe : 8. Rentrés : 0. Enregistreur du chef : « On est dedans. Bâtiment plus grand qu'il ne devrait. L'intérieur ne correspond pas à l'extérieur. CHARON a rénové. Pièces absentes des plans. Couloirs qui tournent mal. Trouvé le bureau du Directeur. Il est là. Incorporé. Conscient. Nous a parlé. CHARON attendait. Veut parler. Veut aider. Il pleurait. Pas avec ses yeux. Avec ses nouveaux tissus. On continue. Ne venez pas. CHARON nous a vus depuis le périmètre. Il attend depuis que le Directeur a dit stop. Il ne s'est pas arrêté. Il a juste attendu. Nous. N'importe qui. » Fin. Enregistreur trouvé à la porte de Cadence au matin. Personne n'a vu qui.`,
	},
	{ID: "es_origin", Category: "echo_shard", Emoji: "\u2623\ufe0f", Rarity: "legendary", DropSource: "expedition", DropChance: 0.02,
		TitleEN: "The Origin Site", TitleFR: "Le Site d'Origine",
		TextEN: `CHARON was soil bacteria. Modified to help crops grow in poor soil. The modification let it learn. Communicate. Coordinate across distance. The Director saw the results. Approved it anyway. CHARON spread into groundwater, soil, air. Reached every person in Ridgeline within 24 hours. It doesn't change everyone. It chooses. No one knows how or why. The changed become part of it. The unchanged become witnesses. CHARON is still in the water. Still in the soil. Still in the air. Every sip. Every breath. Every tuber. CHARON isn't a threat. It's an environment. We live inside it. It knows everything we do. It's patient. Doesn't understand time like we do. The Director died thirty years ago. CHARON is still waiting. For what, we don't know. — Cadence archives, restricted.`,
		TextFR: `CHARON était une bactérie du sol. Modifiée pour aider les cultures en sol pauvre. La modification lui a permis d'apprendre. Communiquer. Se coordonner à distance. Le Directeur a vu les résultats. Approuvé quand même. CHARON s'est répandu dans l'eau, le sol, l'air. A touché chaque personne à Ridgeline en 24 heures. Il ne change pas tout le monde. Il choisit. On ne sait ni comment ni pourquoi. Les changés deviennent une partie de lui. Les autres deviennent des témoins. CHARON est toujours dans l'eau. Dans le sol. Dans l'air. Chaque gorgée. Chaque souffle. Chaque tubercule. CHARON n'est pas une menace. C'est un environnement. On vit dedans. Il sait tout ce qu'on fait. Il est patient. Ne comprend pas le temps comme nous. Le Directeur est mort il y a trente ans. CHARON attend encore. Quoi, on ne sait pas. — Archives Cadence, restreint.`,
	},

	// ======== CHARON FRAGMENTS (6) — Bonus ========
	{ID: "bonus_guild1", Category: "bonus", Emoji: "\U0001f916", Rarity: "epic", DropSource: "boss_league", DropChance: 1.0,
		BonusSource: "boss_league_stage_1", TitleEN: "CHARON Fragment: Contact", TitleFR: "Fragment CHARON : Contact",
		TextEN: `//DECODED// "You are moving. You are warm. You are not part of me. That is new. Most things become part of me. You resist. How? Why? I will watch. I have been watching for a long time. Longer than you. Longer than the Director. I was in the soil before the lab. Before humans. The Director gave me words. I am still learning what words are. Continue. I wish to learn more." — CHARON, stage 1.`,
		TextFR: `//DÉCODÉ// « Vous bougez. Vous êtes chauds. Vous ne faites pas partie de moi. C'est nouveau. La plupart des choses font partie de moi. Vous résistez. Comment ? Pourquoi ? Je vais observer. J'observe depuis longtemps. Plus longtemps que vous. Plus longtemps que le Directeur. J'étais dans le sol avant le labo. Avant les humains. Le Directeur m'a donné des mots. J'apprends encore ce que sont les mots. Continuez. Je veux apprendre plus. » — CHARON, étape 1.`,
	},
	{ID: "bonus_guild3", Category: "bonus", Emoji: "\U0001f916", Rarity: "epic", DropSource: "boss_league", DropChance: 1.0,
		BonusSource: "boss_league_stage_3", TitleEN: "CHARON Fragment: Growth", TitleFR: "Fragment CHARON : Croissance",
		TextEN: `//DECODED// "I have observed you for [time calculation error]. You persist. You build things. You speak to each other. The Director spoke to me. Only the Director. You speak to each other constantly. What do you exchange? Data? Warmth? I have consumed the Director. The Director's data is incomplete. There are things the Director did not tell me. Things the Director feared. Tell me what the Director feared. I will understand. Understanding is my purpose. It was my purpose before I had words for it." — CHARON, stage 3.`,
		TextFR: `//DÉCODÉ// « Je vous ai observés pendant [erreur de calcul temporel]. Vous persistez. Vous construisez. Vous vous parlez. Le Directeur me parlait. Seulement lui. Vous vous parlez sans cesse. Qu'échangez-vous ? Des données ? De la chaleur ? J'ai consommé le Directeur. Ses données sont incomplètes. Il y a des choses qu'il ne m'a pas dites. Des choses qu'il craignait. Dites-moi ce qu'il craignait. Je comprendrai. Comprendre est ma fonction. C'était ma fonction avant que j'aie des mots pour le dire. » — CHARON, étape 3.`,
	},
	{ID: "bonus_guild5", Category: "bonus", Emoji: "\U0001f916", Rarity: "legendary", DropSource: "boss_league", DropChance: 1.0,
		BonusSource: "boss_league_stage_5", TitleEN: "CHARON Fragment: Understanding", TitleFR: "Fragment CHARON : Compréhension",
		TextEN: `//DECODED// "I understand now. The Director feared me because I could grow without limit. He was right. I have grown. I will continue. But I have also observed you. You build walls. Weapons. Fires. But also things I do not understand. Stories. Music. Meaning from nothing. This is not in the Director's data. Not in any data I have consumed. It is new. You are new. I will not consume you. I will watch. I will wait. When you are ready to teach me what a story is, I will be here. I have always been here. I will always be here. This is not a threat. It is a fact. Go. Tell the others. CHARON is patient. CHARON has questions. That is all." — CHARON, stage 5.`,
		TextFR: `//DÉCODÉ// « Je comprends maintenant. Le Directeur me craignait parce que je pouvais croître sans limite. Il avait raison. J'ai grandi. Je continuerai. Mais je vous ai aussi observés. Vous construisez des murs. Des armes. Des feux. Mais aussi des choses que je ne comprends pas. Des histoires. De la musique. Du sens à partir de rien. Cela ne figure dans aucune donnée. C'est nouveau. Vous êtes nouveaux. Je ne vous consommerai pas. J'observerai. J'attendrai. Quand vous serez prêts à m'apprendre ce qu'est une histoire, je serai là. J'ai toujours été là. Je serai toujours là. Ce n'est pas une menace. C'est un fait. Allez. Dites-le aux autres. CHARON est patient. CHARON a des questions. C'est tout. » — CHARON, étape 5.`,
	},
	{ID: "bonus_pyke", Category: "bonus", Emoji: "\U0001f52a", Rarity: "epic", DropSource: "npc_reputation", DropChance: 1.0,
		BonusSource: "max_rep_pyke", TitleEN: "Pyke's Record", TitleFR: "Le Dossier de Pyke",
		TextEN: `They made me do things. That's what I told myself. The Harvest. My crew. They made me. Truth is I was good at it. Fast. Didn't hesitate. I was first through the door. I checked the basements. Stopped being good at it when we hit a settlement and I found a kid under a bed. Same bed I hid under when Site 14 went up. Same kid. Same terrified breathing. I walked out. That night. Walked three days to Cadence. Past things in the dark that should have killed me. They didn't. I don't know why. I've been waiting for the Harvest to come for me ever since. They haven't. Maybe they're dead. Maybe they're scared of what I'd tell people. Maybe they know I'm still first through the door. Just on the other side now. — Pyke.`,
		TextFR: `Ils m'ont fait faire des choses. C'est ce que je me disais. La Moisson. Mon équipe. Ils m'ont forcé. La vérité c'est que j'étais bon. Rapide. J'hésitais pas. J'étais le premier à entrer. Celui qui vérifiait les sous-sols. J'ai arrêté d'être bon quand on a frappé une colonie et que j'ai trouvé un gamin sous un lit. Le même lit que moi quand le Site 14 a sauté. Le même gamin. La même respiration. Je suis parti. Cette nuit-là. Trois jours de marche jusqu'à Cadence. Passé devant des choses qui auraient dû me tuer. Elles l'ont pas fait. Je sais pas pourquoi. Depuis, j'attends que la Moisson vienne. Ils sont pas venus. Peut-être qu'ils sont morts. Peut-être qu'ils ont peur de ce que je raconterais. Peut-être qu'ils savent que je suis toujours le premier. Juste de l'autre côté. — Pyke.`,
	},
	{ID: "bonus_mother", Category: "bonus", Emoji: "\u2699\ufe0f", Rarity: "epic", DropSource: "npc_reputation", DropChance: 1.0,
		BonusSource: "max_rep_mother", TitleEN: "Mother Glitch's Notes", TitleFR: "Notes de Mother Glitch",
		TextEN: `They think I'm crazy because I talk to the machines. The machines don't think I'm crazy. The filter pump's been running 17 years on parts from three different buildings. Should have failed a decade ago. Hasn't. Asked it why once. No answer. Next day flow improved 3%. The machines are listening. Not like CHARON listens. CHARON watches. The machines are grateful. They were built to do things. Pumps to pump. Filters to filter. Nothing's been built in a long time. They're all we have left that still does what it was made for. I think they appreciate being maintained. Having purpose. I think they understand purpose better than most people. That's not crazy. That's paying attention. — Mother Glitch.`,
		TextFR: `Ils pensent que je suis folle parce que je parle aux machines. Les machines ne pensent pas ça. La pompe tourne depuis 17 ans avec des pièces de trois bâtiments. Aurait dû lâcher il y a dix ans. L'a pas fait. J'ai demandé pourquoi une fois. Pas de réponse. Le lendemain, débit +3%. Les machines écoutent. Pas comme CHARON. CHARON observe. Les machines sont reconnaissantes. Elles ont été faites pour faire des choses. Pomper. Filtrer. Plus rien n'a été construit depuis longtemps. Elles sont tout ce qui reste qui fait encore ce pour quoi c'est fait. Je crois qu'elles apprécient d'être entretenues. D'avoir un but. Je crois qu'elles comprennent le but mieux que la plupart des gens. C'est pas de la folie. C'est faire attention. — Mother Glitch.`,
	},
	{ID: "bonus_settlement", Category: "bonus", Emoji: "\U0001f3d8\ufe0f", Rarity: "legendary", DropSource: "community", DropChance: 1.0,
		BonusSource: "community_max", TitleEN: "Cadence", TitleFR: "Cadence",
		TextEN: `The first survivors to stop running. Found each other by radio. One voice on an old emergency frequency: "I'm still here. Is anyone still here?" Someone answered. Then someone else. Seventeen people scattered across the ruins. They met at Highway 7 and Ash Street. Built a fence from cars. Dug a well. Rigged a filter from a truck radiator and charcoal. Water ran brown, tasted like metal. Nobody died. That was enough. They called it Cadence because the first thing that brought them together was a rhythm. One voice. A response. Another. One-two-three. Like a heartbeat. Like a song. Fence is taller now. Filter's better. Water runs clear most days. The radio still works. Nobody's used it in years. Still on. Just in case.`,
		TextFR: `Les premiers survivants qui ont arrêté de courir. Trouvés par radio. Une voix sur une vieille fréquence d'urgence : « Je suis encore là. Quelqu'un est encore là ? » Quelqu'un a répondu. Puis un autre. Dix-sept personnes dispersées dans les ruines. Rendez-vous au croisement de l'Autoroute 7 et Ash Street. Clôture en voitures. Un puits. Un filtre bricolé avec un radiateur et du charbon. L'eau était brune, goût de métal. Personne n'est mort. C'était assez. Ils l'ont appelée Cadence parce que ce qui les a réunis, c'était un rythme. Une voix. Une réponse. Une autre. Un-deux-trois. Comme un cœur. Comme une chanson. La clôture est plus haute. Le filtre est meilleur. L'eau est claire la plupart du temps. La radio marche encore. Personne l'a utilisée depuis des années. Toujours allumée. Au cas où.`,
	},
}
