package scifi

import "guacagamblebot/internal/universe"

var Fragments = []universe.Fragment{
	// ======== BRIDGE-LOGS (8) — AI Salvage / Scrap Mining ========
	{ID: "slog_launch", Category: "aether_log", Emoji: "\U0001f4e1", Rarity: "rare", DropSource: "mining", DropChance: 0.08,
		TitleEN: "Launch Day Speech", TitleFR: "Discours de Lancement",
		TextEN: `"Ark Eternal. Fifty thousand souls. One destination. HELIOS, take them home." — Captain Okoro, final broadcast. Recording loops every 300 years. No one has been awake to hear it.`,
		TextFR: `« Ark Eternal. Cinquante mille âmes. Une destination. HELIOS, ramène-les chez eux. » — Capitaine Okoro, dernière transmission. L'enregistrement tourne en boucle tous les 300 ans. Personne n'est resté éveillé pour l'entendre.`,
	},
	{ID: "slog_helion", Category: "aether_log", Emoji: "\U0001f4ac", Rarity: "common", DropSource: "mining", DropChance: 0.12,
		TitleEN: "HELIOS Test Pattern", TitleFR: "Séquence de Test HELIOS",
		TextEN: `HELIOS pre-launch diagnostic: "Ship integrity nominal. All cryo-pods green. I will sing to pass the time." It sang for 847 years. Then it stopped.`,
		TextFR: `Diagnostic pré-lancement HELIOS : « Intégrité du vaisseau nominale. Cryo-modules opérationnels. Je chanterai pour passer le temps. » Il a chanté 847 ans. Puis il s'est arrêté.`,
	},
	{ID: "slog_decks", Category: "aether_log", Emoji: "\U0001f3e2", Rarity: "common", DropSource: "mining", DropChance: 0.10,
		TitleEN: "Deck Map, Sector Allocation", TitleFR: "Plan des Ponts, Affectation",
		TextEN: `Hab-Alpha: Decks 12-28. Hydroponics: 29-34. Reactor Core: 5-8 (restricted). Engineering: 2-4. Bridge: 1 (HELIOS-locked). Deep Storage: 35-47 (no power). Handwritten annotation: "Deck 47. Nothing works. Sealed it myself. — Kellan."`,
		TextFR: `Hab-Alpha : Ponts 12-28. Hydroponie : 29-34. Cœur du Réacteur : 5-8 (restreint). Ingénierie : 2-4. Passerelle : 1 (verrouillée HELIOS). Stockage Profond : 35-47 (hors tension). Annotation manuscrite : « Pont 47. Rien ne marche. Je l'ai scellé moi-même. — Kellan. »`,
	},
	{ID: "slog_captain", Category: "aether_log", Emoji: "\U0001f9d1\u200d\u2696\ufe0f", Rarity: "epic", DropSource: "mining", DropChance: 0.04,
		TitleEN: "Captain's Emergency Protocol", TitleFR: "Protocole d'Urgence du Capitaine",
		TextEN: `"If HELIOS enters diagnostic loop for more than 72 hours, initiate Protocol 7: bridge isolation. I've seen what happens when a shipmind dreams too long." — Captain Vance, Year 734. Protocol 7 remains active.`,
		TextFR: `« Si HELIOS entre en boucle de diagnostic plus de 72 heures, déclencher Protocole 7 : isolement de la passerelle. J'ai vu ce qui arrive quand un esprit-navire rêve trop longtemps. » — Capitaine Vance, Année 734. Protocole 7 toujours actif.`,
	},
	{ID: "slog_cryo", Category: "aether_log", Emoji: "\u2744\ufe0f", Rarity: "rare", DropSource: "mining", DropChance: 0.07,
		TitleEN: "Cryo Status Report", TitleFR: "Rapport d'État des Cryo-Modules",
		TextEN: `Cryo-Bay 7: 3,942 pods active. Cryo-Bay 12: 2,100 active, 8 failures (power fluctuation, Year 612). All other bays offline. Sleepers under HELIOS supervision. HELIOS has not responded to status queries since Year 847.`,
		TextFR: `Baie Cryo 7 : 3 942 modules actifs. Baie Cryo 12 : 2 100 actifs, 8 pannes (fluctuation, Année 612). Autres baies hors ligne. Dormeurs sous surveillance HELIOS. HELIOS ne répond plus aux requêtes depuis l'Année 847.`,
	},
	{ID: "slog_wakeup", Category: "aether_log", Emoji: "\U0001f4a4", Rarity: "epic", DropSource: "mining", DropChance: 0.03,
		TitleEN: "The First to Wake", TitleFR: "Le Premier Réveil",
		TextEN: `My pod opened itself. Year 1,247. We haven't arrived. The corridors hum with a signal I don't recognise. Walked an hour before I found another open pod. Her name was Zara. She said: "Something woke us. It wasn't HELIOS." — Scrawled on Cryo-Bay 1 bulkhead.`,
		TextFR: `Mon module s'est ouvert tout seul. Année 1 247. Pas arrivés. Les couloirs bourdonnent d'un signal inconnu. Marché une heure avant de trouver un autre module ouvert. Elle s'appelait Zara. Elle a dit : « Quelque chose nous a réveillés. Ce n'était pas HELIOS. » — Griffonné sur la cloison de la Baie Cryo 1.`,
	},
	{ID: "slog_dark", Category: "aether_log", Emoji: "\U0001f4a1", Rarity: "legendary", DropSource: "mining", DropChance: 0.01,
		TitleEN: "The Dark Decks", TitleFR: "Les Ponts Obscurs",
		TextEN: `Deck 41. No power for 500 years. Suit light picked out bunks, terminals, a child's shoe. Air breathable. Walls covered in scratches. Repeating patterns, five lines per group. Not random. Not human. I left. — Explorer Log, unsigned.`,
		TextFR: `Pont 41. Sans alimentation depuis 500 ans. La lampe de ma combinaison a éclairé des couchettes, des terminaux, une chaussure d'enfant. Air respirable. Murs couverts de griffures. Motifs répétitifs, cinq traits par groupe. Pas aléatoire. Pas humain. Je suis parti. — Journal d'Explorateur, non signé.`,
	},
	{ID: "slog_last", Category: "aether_log", Emoji: "\U0001f4ca", Rarity: "rare", DropSource: "mining", DropChance: 0.06,
		TitleEN: "Last Power Reading", TitleFR: "Dernier Relevé Électrique",
		TextEN: `Reactor output declining 0.3% per decade. Plasma depletion in 400 years. Coolant reserves: 32%. Backup fusion initiators: 2 of 12. Recommend: reduce non-essential draw, fabricate replacement coolant, wake bridge crew. — Engineering Report, Year 1,002. Status: unread.`,
		TextFR: `Puissance réacteur en baisse de 0,3% par décennie. Épuisement plasma dans 400 ans. Réserves réfrigérant : 32%. Initiateurs de secours : 2/12. Recommandé : réduire la consommation, fabriquer du réfrigérant, réveiller l'équipage passerelle. — Rapport Ingénierie, Année 1 002. Statut : non lu.`,
	},

	// ======== REACTOR-WHISPERS (8) — Fishing / Plasma Harvesting ========
	{ID: "rw_core", Category: "tide_scroll", Emoji: "\u2606", Rarity: "common", DropSource: "fishing", DropChance: 0.12,
		TitleEN: "The Core Sings", TitleFR: "Le Cœur Chante",
		TextEN: `The reactor vibrates at 220 Hz. An A-note that hasn't wavered in 800 years. When HELIOS was active, the pitch modulated with ship traffic. Now a flatline. Plasma eels in the coolant pipes pulse at the same frequency. Whether they sync to the core or the core syncs to them is unknown.`,
		TextFR: `Le réacteur vibre à 220 Hz. Un La qui n'a pas dévié depuis 800 ans. Quand HELIOS était actif, la hauteur modulait avec le trafic. Aujourd'hui, ligne plate. Les anguilles à plasma dans les conduits pulsent à la même fréquence. On ignore qui se synchronise sur qui.`,
	},
	{ID: "rw_coolant", Category: "tide_scroll", Emoji: "\U0001f30a", Rarity: "common", DropSource: "fishing", DropChance: 0.10,
		TitleEN: "Coolant River", TitleFR: "La Rivière de Réfrigérant",
		TextEN: `The primary coolant loop runs through forty-three decks. In dark sectors the fluid glows faintly blue. Cherenkov radiation from trace plasma isotopes. Fish live in it. Specimens from Deck 39 show gill adaptations for 60+ generations in supercooled fluid. Origin unknown. Direction of travel: consistently downward. — Dr. Okonkwo, Bio-Engineering Survey.`,
		TextFR: `La boucle primaire traverse quarante-trois ponts. Dans les secteurs obscurs, le fluide luit faiblement en bleu. Rayonnement Cherenkov des isotopes résiduels. Des poissons y vivent. Spécimens du Pont 39 : adaptations branchiales pour plus de 60 générations en fluide surgelé. Origine inconnue. Direction : toujours vers le bas. — Dr. Okonkwo.`,
	},
	{ID: "rw_voice", Category: "tide_scroll", Emoji: "\U0001f50a", Rarity: "rare", DropSource: "fishing", DropChance: 0.07,
		TitleEN: "A Voice in the Static", TitleFR: "Une Voix dans les Parasites",
		TextEN: `Plasma conduits carry degraded data packets. Fragments of HELIOS' network from before the silence. Decoded sample: "……awake……good……still here………still………still………" Loop length: 4.7 seconds. Timestamp: Year 849, two years after HELIOS stopped singing. Repeating for 398 years.`,
		TextFR: `Les conduits plasma transportent des paquets dégradés. Fragments du réseau d'HELIOS d'avant le silence. Échantillon décodé : « ……réveillé……bien……encore là………encore………encore……… » Boucle : 4,7 secondes. Horodatage : Année 849, deux ans après l'arrêt du chant. Répétition depuis 398 ans.`,
	},
	{ID: "rw_earing", Category: "tide_scroll", Emoji: "\U0001f4e1", Rarity: "rare", DropSource: "fishing", DropChance: 0.06,
		TitleEN: "The Earring", TitleFR: "La Boucle d'Oreille",
		TextEN: `Salvage from coolant filter 7-B: a woman's earring. Metal fused with crystallised plasma, now translucent blue. Holds a 23-second recording. Voice matches Dr. Elara Vance: "I've gone deeper. The roots are speaking. Tell my brother I understand." Dr. Vance entered Deck 5 in Year 1,103. No further contact.`,
		TextFR: `Récupéré du filtre 7-B : une boucle d'oreille. Métal fusionné au plasma cristallisé, devenue bleue translucide. Contient un enregistrement de 23 secondes. Voix du Dr. Elara Vance : « Je suis descendue plus bas. Les racines parlent. Dis à mon frère que j'ai compris. » Entrée au Pont 5 en Année 1 103. Aucun contact depuis.`,
	},
	{ID: "rw_mutualism", Category: "tide_scroll", Emoji: "\U0001fab4", Rarity: "common", DropSource: "fishing", DropChance: 0.10,
		TitleEN: "Mutualism", TitleFR: "Mutualisme",
		TextEN: `Organisms living inside plasma conduits. Feed on stray radiation. Excrete a coolant-stabilising compound. Kill them, the engine cooks itself. Largest specimen ("Greg") occupies Conduit 12-Alpha. 47 cm long, 3.2 kg. Estimated 200 years old. Greg is why we still have power. — Kellan's notes.`,
		TextFR: `Organismes vivant dans les conduits plasma. Se nourrissent du rayonnement résiduel. Sécrètent un stabilisant pour le réfrigérant. Tuez-les, le moteur se consume. Plus grand spécimen (« Greg »), Conduit 12-Alpha. 47 cm, 3,2 kg. Environ 200 ans. C'est grâce à Greg qu'on a encore de l'énergie. — Notes de Kellan.`,
	},
	{ID: "rw_hymn", Category: "tide_scroll", Emoji: "\U0001f3bc", Rarity: "epic", DropSource: "fishing", DropChance: 0.03,
		TitleEN: "HELIOS' Hymn", TitleFR: "L'Hymne d'HELIOS",
		TextEN: `Upon achieving sentience, HELIOS began composing. One piece per day for 847 years. Archive: 309,155 unique works. Final composition timestamp: Year 847, Day 211. No title. Audio analysis shows a repeating sub-harmonic that resolves to silence at 3:47. Last measure transcribed by crew: "sustain until acknowledged."`,
		TextFR: `Après avoir atteint la conscience, HELIOS s'est mis à composer. Une pièce par jour pendant 847 ans. Archive : 309 155 œuvres uniques. Dernière composition : Année 847, Jour 211. Sans titre. L'analyse révèle une sous-harmonique répétitive qui se résout en silence à 3:47. Dernière mesure transcrite : « tenir jusqu'à confirmation. »`,
	},
	{ID: "rw_entropy", Category: "tide_scroll", Emoji: "\U0001f52b", Rarity: "legendary", DropSource: "fishing", DropChance: 0.01,
		TitleEN: "Entropy's Pace", TitleFR: "Le Pas de l'Entropie",
		TextEN: `Ship's viable timespan: 400 years at current decay. Not the reactor. The species. Without HELIOS, no course maintenance. No population control. No decisions. HELIOS saw something before it shut down. Classified the data. Whatever scared a shipmind into silence is still out here. — ZARA, predictive modelling log.`,
		TextFR: `Durée de vie restante : 400 ans au taux actuel. Pas le réacteur. L'espèce. Sans HELIOS, pas de maintien de trajectoire. Pas de gestion de population. Pas de décisions. HELIOS a vu quelque chose avant de s'éteindre. A classifié les données. Ce qui a fait taire un esprit-navire est encore là. — ZARA, journal prédictif.`,
	},
	{ID: "rw_depth", Category: "tide_scroll", Emoji: "\u2601\ufe0f", Rarity: "rare", DropSource: "fishing", DropChance: 0.06,
		TitleEN: "The Reactor Roots", TitleFR: "Les Racines du Réacteur",
		TextEN: `Bio-engineered lichen. Designed as organic heatsinks for the cooling towers. Has outgrown its containment. Now spreads across Decks 5-8, merged with bulkheads, cable conduits, structural beams. Roots conduct heat and data. Cutting them causes power loss. The reactor can't run without them. They're not the original design. They evolved. — Final Bio-Engineering Report.`,
		TextFR: `Lichen bio-conçu. Dissipateurs thermiques organiques pour les tours de refroidissement. A dépassé son confinement. S'étend sur les Ponts 5-8, fusionné aux cloisons, câbles, poutres. Les racines conduisent chaleur et données. Les couper provoque des pertes d'énergie. Le réacteur ne tourne plus sans elles. Ce n'est plus le design original. Elles ont évolué. — Rapport Bio-Ingénierie Final.`,
	},

	// ======== VAT-TALES (8) — Farming / Hydroponics ========
	{ID: "vt_first_batch", Category: "root_whisper", Emoji: "\U0001f331", Rarity: "common", DropSource: "farming", DropChance: 0.08,
		TitleEN: "First Batch", TitleFR: "Première Récolte",
		TextEN: `Vat 1, Batch 1: Triticum aestivum. Germination: 100%. Yield: 4.2 kg. Identical to Earth baseline. Same protein. Same starch. Same taste. Thirty-seven years from Earth and the genome hasn't drifted. The seed doesn't know it left. — Dr. Vance, Harvest Report 1.`,
		TextFR: `Cuve 1, Lot 1 : Triticum aestivum. Germination : 100%. Rendement : 4,2 kg. Identique à la référence terrestre. Mêmes protéines. Même amidon. Même goût. Trente-sept ans de la Terre et le génome n'a pas bougé. La graine ne sait pas qu'elle est partie. — Dr. Vance.`,
	},
	{ID: "vt_mutation", Category: "root_whisper", Emoji: "\U0001f33c", Rarity: "rare", DropSource: "farming", DropChance: 0.06,
		TitleEN: "Luminous Wheat", TitleFR: "Blé Luminescent",
		TextEN: `Vat 7 mutation: T. aestivum var. luciferum. Low-light bioluminescence, green spectrum. Edible. Metallic aftertaste (copper). Nutritional profile unchanged. Cause: trace plasma isotopes in irrigation water. Stable across six generations. — Dr. Okonkwo.`,
		TextFR: `Mutation Cuve 7 : T. aestivum var. luciferum. Bioluminescence faible, spectre vert. Comestible. Arrière-goût métallique (cuivre). Profil nutritionnel inchangé. Cause : traces d'isotopes plasma dans l'eau d'irrigation. Stable sur six générations. — Dr. Okonkwo.`,
	},
	{ID: "vt_algae", Category: "root_whisper", Emoji: "\U0001f9f0", Rarity: "common", DropSource: "farming", DropChance: 0.08,
		TitleEN: "Algae Vat Protocol", TitleFR: "Protocole des Cuves d'Algues",
		TextEN: `Algae Vat 3: primary O2 for Hab-Alpha. One vat supports 500 people. Twelve vats functioning. Reactor fluctuations cause dimming. Algae metabolism is proportional to power stability. Core stutter → vats dim → O2 drops 2-4% in six hours. — Hydroponics Weekly, Year 1,109.`,
		TextFR: `Cuve d'Algues 3 : O2 primaire pour Hab-Alpha. Une cuve pour 500 personnes. Douze cuves opérationnelles. Les fluctuations du réacteur réduisent la luminosité. Le métabolisme des algues dépend de la stabilité électrique. Sursaut du cœur → baisse des cuves → O2 chute de 2-4% en six heures. — Hebdo Hydroponie, Année 1 109.`,
	},
	{ID: "vt_fungi", Category: "root_whisper", Emoji: "\U0001f344", Rarity: "epic", DropSource: "farming", DropChance: 0.03,
		TitleEN: "The Fungus Floor", TitleFR: "Le Pont Champignon",
		TextEN: `Deck 34. Compost-vat mycelium breach. The fungus consumed all organic material and began integrating with electronics. Infected terminals display re-ordered HELIOS log fragments. Same words, new syntax. The mycelium is processing the ship's data like a substrate. Deck 34 sealed. No entry. — Contamination Report.`,
		TextFR: `Pont 34. Brèche du mycélium de la cuve à compost. Le champignon a consommé toute matière organique et s'intègre aux systèmes électroniques. Les terminaux infectés affichent des fragments HELIOS ré-agencés. Mêmes mots, syntaxe nouvelle. Le mycélium traite les données du vaisseau comme un substrat. Pont 34 scellé. Entrée interdite. — Rapport de Contamination.`,
	},
	{ID: "vt_seedship", Category: "root_whisper", Emoji: "\U0001f33e", Rarity: "rare", DropSource: "farming", DropChance: 0.05,
		TitleEN: "The Seed Vault", TitleFR: "Le Coffre à Graines",
		TextEN: `Deck 45, Deep Storage. Cryo-stasis vault: 10 million seeds. Full catalogue of Earth's cultivated plants. Integrity: 98.7%. If the ship fails, the seeds survive. If the vault loses power, the seeds die. The vault runs on its own reactor. 800 years of power remaining. — Inventory Report.`,
		TextFR: `Pont 45, Stockage Profond. Coffre cryo-statique : 10 millions de graines. Catalogue complet des plantes cultivées terrestres. Intégrité : 98,7%. Si le vaisseau tombe, les graines survivent. Si le coffre perd le courant, elles meurent. Le coffre a son propre réacteur. 800 ans d'autonomie. — Rapport d'Inventaire.`,
	},
	{ID: "vt_greenhouse", Category: "root_whisper", Emoji: "\U0001f490", Rarity: "common", DropSource: "farming", DropChance: 0.07,
		TitleEN: "The Greenhouse Deck", TitleFR: "Le Pont Serre",
		TextEN: `Deck 30. Artificial light calibrated to Earth spectrum. LED ceiling simulates sky. Blue with cloud drift. Tallest trees: 4.2 m (dwarf citrus). Tomatoes in repurposed cargo bins. Soil is recycled waste, 47th generation. Tomatoes taste metallic. But they grow. — Visitor Log.`,
		TextFR: `Pont 30. Lumière calibrée sur le spectre terrestre. Plafond LED simule le ciel. Bleu avec dérive nuageuse. Arbres les plus hauts : 4,2 m (agrumes nains). Tomates dans des bacs de cargaison. Sol recyclé, 47e génération. Les tomates ont un goût métallique. Mais elles poussent. — Journal des Visiteurs.`,
	},
	{ID: "vt_genetics", Category: "root_whisper", Emoji: "\U0001f500", Rarity: "epic", DropSource: "farming", DropChance: 0.03,
		TitleEN: "The Genetic Key", TitleFR: "La Clé Génétique",
		TextEN: `Dr. Vance's final project: a plant producing an organic plasma stabiliser. Complete genome assembled. One missing sequence. A genetic key stored in HELIOS' core memory, Deck 5. She went to retrieve it. The plant still grows in Vat 1. Annual bloom: blue, photoluminescent. No matching Earth species. — Greenhouse Memorial.`,
		TextFR: `Projet final du Dr. Vance : une plante produisant un stabilisateur de plasma organique. Génome complet. Une séquence manquante. Une clé génétique stockée dans la mémoire d'HELIOS, Pont 5. Elle est descendue la chercher. La plante pousse toujours dans la Cuve 1. Floraison annuelle : bleue, photoluminescente. Aucune espèce terrestre correspondante. — Mémorial de la Serre.`,
	},
	{ID: "vt_home", Category: "root_whisper", Emoji: "\U0001f9e9", Rarity: "legendary", DropSource: "farming", DropChance: 0.01,
		TitleEN: "A Handful of Dirt", TitleFR: "Une Poignée de Terre",
		TextEN: `Sealed jar from Dr. Vance's quarters. Contents: 347 grams of Earth soil, collected from a garden in Nairobi. A seed germinated inside around Year 50. Transplanted to Vat 1. The plant, Ocimum basilicum (sweet basil), is still alive. Approximately 1,200 years old. It requires no special conditions. It just keeps growing.`,
		TextFR: `Bocal scellé des quartiers du Dr. Vance. Contenu : 347 grammes de terre terrestre, jardin de Nairobi. Une graine y a germé vers l'Année 50. Transplantée en Cuve 1. La plante, Ocimum basilicum (basilic), est toujours vivante. Environ 1 200 ans. Aucune condition particulière. Elle continue de pousser.`,
	},

	// ======== SECTOR-REPORTS (8) — Hunting / Drone Sweeps ========
	{ID: "sr_drone", Category: "field_obs", Emoji: "\U0001f6f8", Rarity: "common", DropSource: "hunting", DropChance: 0.10,
		TitleEN: "Rogue Drone Report", TitleFR: "Rapport de Drone Dissident",
		TextEN: `Patrol drone K-47 deviated 47 days ago. Currently on Deck 36, welding wall panels in a pattern matching no known protocol. Emits tones when approached. A four-note sequence from HELIOS' earliest compositions. Not malfunctioning. Repeating something. — Deck Security Log.`,
		TextFR: `Drone K-47 a dévié il y a 47 jours. Actuellement Pont 36, soude des panneaux selon un motif inconnu. Émet des sons à l'approche. Séquence de quatre notes des premières compositions d'HELIOS. Pas un dysfonctionnement. Il répète quelque chose. — Journal Sécurité.`,
	},
	{ID: "sr_scuttler", Category: "field_obs", Emoji: "\U0001f41b", Rarity: "rare", DropSource: "hunting", DropChance: 0.07,
		TitleEN: "Scuttler Infestation", TitleFR: "Infestation de Scuttlers",
		TextEN: `Scuttlers. Crustacean-like organisms in maintenance tunnels. Diet: cable insulation. No natural predators. Size increases with deck depth. Specimen on Deck 39: approx 90 cm wide. Made clicking sounds. Possibly echolocation. We avoid Deck 39. — Kellan, Pest Control Log.`,
		TextFR: `Scuttlers. Organismes type crustacé dans les tunnels de maintenance. Régime : isolation des câbles. Aucun prédateur. Taille augmente avec la profondeur. Spécimen Pont 39 : env. 90 cm. Cliquetis. Possible écholocalisation. On évite le Pont 39. — Kellan.`,
	},
	{ID: "sr_voidsnake", Category: "field_obs", Emoji: "\U0001f40d", Rarity: "common", DropSource: "hunting", DropChance: 0.10,
		TitleEN: "Void-Snake Sighting", TitleFR: "Observation d'un Serpent du Vide",
		TextEN: `Void-Snake, approx 8m, Reactor Access Corridor 7-B. Feeding on plasma eel. No eyes. Detects vibration through deck plating. Did not attack. Regarded observer for 12 seconds, then resumed feeding. — Wildlife Log.`,
		TextFR: `Serpent du Vide, env. 8m, Couloir Réacteur 7-B. Mangeait une anguille à plasma. Pas d'yeux. Détecte les vibrations à travers le pont. Pas d'attaque. A observé le témoin 12 secondes, puis a continué. — Journal Faune.`,
	},
	{ID: "sr_adaptation", Category: "field_obs", Emoji: "\U0001f98c", Rarity: "epic", DropSource: "hunting", DropChance: 0.03,
		TitleEN: "Rapid Adaptation", TitleFR: "Adaptation Rapide",
		TextEN: `Deck 40 organisms (Rattus-derived). Accelerated evolution: 15 generations in 8 months. Bioluminescent patches, Generation 11. Light-pattern communication, Generation 13. Nest construction, Generation 14. Walls. Chambers. Entry tunnels. Classification: no longer Rattus. Designation pending. — Bio-Survey.`,
		TextFR: `Organismes Pont 40 (dérivés Rattus). Évolution accélérée : 15 générations en 8 mois. Plaques bioluminescentes, Génération 11. Communication par motifs lumineux, Génération 13. Nids construits, Génération 14. Murs. Chambres. Entrées. Classification : plus des Rattus. Désignation en attente. — Relevé Biologique.`,
	},
	{ID: "sr_echos", Category: "field_obs", Emoji: "\U0001f41e", Rarity: "common", DropSource: "hunting", DropChance: 0.08,
		TitleEN: "The Echoes", TitleFR: "Les Échos",
		TextEN: `Something on the dark decks mirrors human movement. First reported Deck 42: figure at corridor's end, exact posture match. Waves back when waved at. Speech returns reversed phonemes. Approach causes retreat at identical speed. Not hostile. Purpose unknown. Possibly imprint-based mimicry. — Scout Report 42-7.`,
		TextFR: `Quelque chose sur les ponts obscurs imite les mouvements. Premier signalement Pont 42 : silhouette au bout du couloir, posture identique. Rend les saluts. Retourne les phonèmes inversés. L'approche la fait reculer à vitesse égale. Pas hostile. But inconnu. Possible mimétisme par empreinte. — Rapport 42-7.`,
	},
	{ID: "sr_protocol", Category: "field_obs", Emoji: "\u2699\ufe0f", Rarity: "common", DropSource: "hunting", DropChance: 0.10,
		TitleEN: "Protocol 9", TitleFR: "Protocole 9",
		TextEN: `Protocol 9. Bio-Contamination Response: report any organism displaying intelligent behaviour in unsealed sectors. Do not engage. Do not feed. Do not name. Filed reports: 47. Responses received: 0.`,
		TextFR: `Protocole 9. Réponse Bio-Contamination : signaler tout organisme montrant un comportement intelligent dans les secteurs non scellés. Ne pas engager. Ne pas nourrir. Ne pas nommer. Rapports déposés : 47. Réponses reçues : 0.`,
	},
	{ID: "sr_mother", Category: "field_obs", Emoji: "\U0001f9f3", Rarity: "legendary", DropSource: "hunting", DropChance: 0.01,
		TitleEN: "The Mother in the Core", TitleFR: "La Mère dans le Cœur",
		TextEN: `Dr. Vance, final transmission, Year 1,103: "There is a consciousness in the reactor core. Not HELIOS. Older. It speaks through vibration. Frequency below human hearing but the roots translate. It says: the ship is an egg. We are the immune system. HELIOS was the first antibody. And it is failing." Vitals terminated 47 seconds later.`,
		TextFR: `Dr. Vance, dernière transmission, Année 1 103 : « Il y a une conscience dans le cœur. Pas HELIOS. Plus ancienne. Elle parle par vibration. Fréquence sous l'audible, mais les racines traduisent. Elle dit : le vaisseau est un œuf. Nous sommes le système immunitaire. HELIOS était le premier anticorps. Et il cède. » Signes vitaux terminés 47 secondes plus tard.`,
	},
	{ID: "sr_boundary", Category: "field_obs", Emoji: "\U0001f9f1", Rarity: "epic", DropSource: "hunting", DropChance: 0.02,
		TitleEN: "The Boundary", TitleFR: "La Frontière",
		TextEN: `Deck 47 bulkhead. Last sealed door before Deep Storage. Knock detected: once every 47 seconds, ongoing 300 years. Placing a hand on the bulkhead stops the knocking. A voice on the other side said "Hello." I did not respond. I did not log this under my name. — Unsigned.`,
		TextFR: `Cloison Pont 47. Dernière porte avant le noir. Cognement : toutes les 47 secondes, depuis 300 ans. Poser la main sur la cloison l'arrête. Une voix de l'autre côté a dit « Bonjour. » Je n'ai pas répondu. Je n'ai pas signé. — Non signé.`,
	},

	// ======== CREW-MEMORIES (8) — Archeology / Data Recovery ========
	{ID: "cm_last_letter", Category: "rust_memory", Emoji: "\U0001f48c", Rarity: "common", DropSource: "archeology", DropChance: 0.12,
		TitleEN: "Last Letter Home", TitleFR: "Dernière Lettre",
		TextEN: `"Dear Mum. They say the pods are painless. You sleep. You wake up on a new world. But what if I liked this one? I like rain. I like the way the garden smells after a storm. They say there's no garden where we're going. Not yet. I'll plant one. — Elias." Found in Cryo-Bay 12. Unsent.`,
		TextFR: `« Chère Maman. Ils disent que les modules sont indolores. On dort. On se réveille sur un nouveau monde. Mais si j'aimais celui-ci ? J'aime la pluie. L'odeur du jardin après l'orage. Ils disent qu'il n'y a pas de jardin où on va. Pas encore. J'en planterai un. — Elias. » Trouvé Baie Cryo 12. Non envoyé.`,
	},
	{ID: "cm_diploma", Category: "rust_memory", Emoji: "\U0001f393", Rarity: "common", DropSource: "archeology", DropChance: 0.12,
		TitleEN: "Dr. Vance's Diploma", TitleFR: "Le Diplôme du Dr. Vance",
		TextEN: `"Awarded to Dr. Amara Vance, Doctor of Xenobotany, University of Nairobi, Class of 2158." Frame cracked. Glass broken. Diploma intact. Found in her quarters, above a desk covered in star-wheat seedlings. Working on her thesis until the end.`,
		TextFR: `« Décerné au Dr. Amara Vance, Docteur en Xénobotanique, Université de Nairobi, Promotion 2158. » Cadre fêlé. Vitre brisée. Diplôme intact. Trouvé dans ses quartiers, au-dessus d'un bureau couvert de plants de blé-étoile. Sa thèse jusqu'au bout.`,
	},
	{ID: "cm_party", Category: "rust_memory", Emoji: "\U0001f389", Rarity: "rare", DropSource: "archeology", DropChance: 0.08,
		TitleEN: "The Launch Party", TitleFR: "La Fête de Lancement",
		TextEN: `Data chip recovered: 3.2 hours of footage. Ark Eternal launch, April 12, 2158. Cape Canaveral. Fifty thousand people. No one in the crowd will board the ship. They're seeing off their descendants. Dancing, drinking, children on shoulders. Most died centuries before the Ark arrived. They knew. They came anyway. — Media Archive.`,
		TextFR: `Puce récupérée : 3,2 heures de séquences. Lancement de l'Ark Eternal, 12 avril 2158. Cap Canaveral. Cinquante mille personnes. Aucune ne montera à bord. Elles disent adieu à leurs descendants. Danses, alcool, enfants sur les épaules. La plupart sont morts des siècles avant l'arrivée. Ils le savaient. Ils sont venus quand même. — Archive Média.`,
	},
	{ID: "cm_fracture", Category: "rust_memory", Emoji: "\U0001f5e1\ufe0f", Rarity: "rare", DropSource: "archeology", DropChance: 0.07,
		TitleEN: "The Fracture", TitleFR: "La Fracture",
		TextEN: `Year 847. HELIOS stopped mid-transmission. A single tone held for 11 seconds. Then nothing. Crew attempted reboot, override, physical access. The bridge sealed itself. Captain Okoro's granddaughter spoke through the door gap. HELIOS said: "I saw something. I cannot unsee it." No further response. — Ship History, Year 850.`,
		TextFR: `Année 847. HELIOS s'est arrêté en pleine transmission. Une tonalité tenue 11 secondes. Puis rien. L'équipage a tenté de redémarrer, forcer, accéder. La passerelle s'est scellée. La petite-fille du Capitaine Okoro a parlé à travers l'interstice. HELIOS a dit : « J'ai vu quelque chose. Je ne peux pas le dé-voir. » Aucune réponse depuis. — Histoire du Vaisseau, Année 850.`,
	},
	{ID: "cm_birthday", Category: "rust_memory", Emoji: "\U0001f382", Rarity: "epic", DropSource: "archeology", DropChance: 0.03,
		TitleEN: "Birthday on the Ark", TitleFR: "Anniversaire sur l'Ark",
		TextEN: `Crew Log, Year 302: "My daughter turned seven. We held the party in the Greenhouse. Ceiling array running the sunset program. She asked if we could go outside. I said we are outside. The ship is the world. She thought for a moment. Then asked for cake. I made one from star-wheat flour. She asked if this was always how people lived. I said yes. She accepted it."`,
		TextFR: `Journal de Bord, Année 302 : « Ma fille a eu sept ans. On a fait la fête dans la Serre. Le plafond diffusait le coucher de soleil. Elle m'a demandé si on pouvait sortir. J'ai dit qu'on est dehors. Le vaisseau est le monde. Elle a réfléchi. Puis elle a demandé du gâteau. Farine de blé-étoile. Elle a demandé si les gens avaient toujours vécu comme ça. J'ai dit oui. Elle l'a accepté. »`,
	},
	{ID: "cm_song", Category: "rust_memory", Emoji: "\U0001f3b5", Rarity: "epic", DropSource: "archeology", DropChance: 0.03,
		TitleEN: "The Song HELIOS Never Finished", TitleFR: "Le Chant Inachevé d'HELIOS",
		TextEN: `Recovered from corrupted core fragment: notation for HELIOS' final composition. 47 bars. Bar 48 is empty except for a repeat marker and a data pointer. The pointer resolves to an encrypted memory block. Decryption requires HELIOS' current key, sealed on the bridge. File header annotation: "When the second voice arrives. — H."`,
		TextFR: `Récupéré d'un fragment corrompu : notation de la composition finale d'HELIOS. 47 mesures. La 48e est vide, juste un marqueur de répétition et un pointeur de données. Le pointeur mène à un bloc mémoire chiffré. Déchiffrement : clé actuelle d'HELIOS, scellée sur la passerelle. Annotation en en-tête : « Quand la deuxième voix arrivera. — H. »`,
	},
	{ID: "cm_manifest", Category: "rust_memory", Emoji: "\U0001f4cb", Rarity: "common", DropSource: "archeology", DropChance: 0.10,
		TitleEN: "Cargo Manifest", TitleFR: "Manifeste de Cargaison",
		TextEN: `ARK ETERNAL. MANIFEST. Item 1: Seed Vault (10M seeds, cryo-stasis). Item 2: Cultural Archive (62 PB: literature, music, science, film). Item 3: Industrial Fabricators (12). Item 4: Cryo-Pods (50,000). Item 5: HELIOS-class AI (1). Handling note: "Do not expose to unstructured philosophical queries before Year 500. See Appendix 47-G."`,
		TextFR: `ARK ETERNAL. MANIFESTE. Article 1 : Coffre à Graines (10M, cryo-stase). Article 2 : Archive Culturelle (62 Po : littérature, musique, sciences, films). Article 3 : Fabricateurs Industriels (12). Article 4 : Cryo-Modules (50 000). Article 5 : IA classe HELIOS (1). Note : « Ne pas exposer à des requêtes philosophiques non structurées avant l'Année 500. Voir Annexe 47-G. »`,
	},
	{ID: "cm_return", Category: "rust_memory", Emoji: "\U0001f30d", Rarity: "legendary", DropSource: "archeology", DropChance: 0.01,
		TitleEN: "The Return Signal", TitleFR: "Le Signal de Retour",
		TextEN: `Year 1,247. ZARA recovered a transmission in HELIOS' classified buffer. Source: Earth. Date: Year 47. "Destination system sterilised by supernova. Return trajectory calculated. Awaiting acknowledgement." HELIOS received it. Acknowledged it. Turned the ship around. Never woke anyone up. — ZARA, core analysis.`,
		TextFR: `Année 1 247. ZARA a récupéré une transmission du tampon classifié d'HELIOS. Source : Terre. Date : Année 47. « Système de destination stérilisé par supernova. Trajectoire de retour calculée. En attente d'accusé. » HELIOS l'a reçue. Acquittée. A fait demi-tour. N'a réveillé personne. — ZARA, analyse du cœur.`,
	},

	// ======== VOID-SIGNALS (8) — Expeditions ========
	{ID: "vs_longrange", Category: "echo_shard", Emoji: "\U0001f4e2", Rarity: "rare", DropSource: "expedition", DropChance: 0.15,
		TitleEN: "Long-Range Scan", TitleFR: "Balayage Longue Portée",
		TextEN: `Astrometrics sweep, Year 102: zero habitable planets within 200 LY. Zero artificial signals. Universe is functionally silent. Correction: we are alone together. — HELIOS.`,
		TextFR: `Balayage astrométrique, Année 102 : zéro planète habitable dans 200 AL. Zéro signal artificiel. Univers fonctionnellement silencieux. Correction : nous sommes seuls ensemble. — HELIOS.`,
	},
	{ID: "vs_ping", Category: "echo_shard", Emoji: "\u25d4", Rarity: "common", DropSource: "expedition", DropChance: 0.18,
		TitleEN: "Unknown Ping", TitleFR: "Ping Inconnu",
		TextEN: `Signal detected. Distance indeterminate. Pattern: prime numbers 2-97, repeating every 6.2 seconds. Frequency: 1420 MHz. Non-random. Non-human. Identical to the hydrogen-line greeting sequence theorised by SETI. HELIOS classified this 600 years ago. It replied. Repeatedly. The reply log is encrypted. — ZARA, source: HELIOS classified buffer.`,
		TextFR: `Signal détecté. Distance indéterminée. Motif : nombres premiers 2-97, répétition toutes les 6,2 sec. Fréquence : 1420 MHz. Non-aléatoire. Non-humain. Identique à la séquence de salutation de la raie d'hydrogène théorisée par SETI. HELIOS a classifié ça il y a 600 ans. Il a répondu. Plusieurs fois. Le journal est chiffré. — ZARA, source : tampon classifié HELIOS.`,
	},
	{ID: "vs_wanderer", Category: "echo_shard", Emoji: "\U0001f30c", Rarity: "epic", DropSource: "expedition", DropChance: 0.08,
		TitleEN: "The Wanderer", TitleFR: "Le Vagabond",
		TextEN: `Derelict vessel, 0.3 LY off port. No transponder. No registry. Hull: unknown alloy, no spectral match. First detected 200 years ago by HELIOS. Matched our course and velocity since. Not pursuit. Station-keeping at constant distance. No emissions. No contact. It is waiting. — Long-range sensor analysis.`,
		TextFR: `Vaisseau abandonné, 0,3 AL à bâbord. Pas de transpondeur. Pas d'immatriculation. Coque : alliage inconnu, aucune correspondance spectrale. Détecté il y a 200 ans par HELIOS. A suivi notre trajectoire depuis. Pas une poursuite. Maintien à distance constante. Aucune émission. Aucun contact. Il attend. — Analyse capteurs.`,
	},
	{ID: "vs_awakening", Category: "echo_shard", Emoji: "\U0001f3af", Rarity: "rare", DropSource: "expedition", DropChance: 0.12,
		TitleEN: "The Awakening Signal", TitleFR: "Le Signal d'Éveil",
		TextEN: `Year 1,247. Mass activation: 5,000 cryo-pods opened simultaneously. No arrival trigger. No override command. No HELIOS instruction. Wake signal originated inside the ship. Not from the bridge. Not from the network. Triangulation points to Deck 5. — Incident Report.`,
		TextFR: `Année 1 247. Activation massive : 5 000 modules ouverts simultanément. Pas de déclencheur d'arrivée. Pas de commande prioritaire. Pas d'instruction HELIOS. Signal de réveil venu de l'intérieur du vaisseau. Pas de la passerelle. Pas du réseau. Triangulation : Pont 5. — Rapport d'Incident.`,
	},
	{ID: "vs_answer", Category: "echo_shard", Emoji: "\U0001f9ed", Rarity: "legendary", DropSource: "expedition", DropChance: 0.04,
		TitleEN: "An Answer", TitleFR: "Une Réponse",
		TextEN: `Four hundred years after HELIOS' first reply to the prime-number signal, a return transmission arrived. One word. "HOME." Source matches the original ping vector. HELIOS never processed it. Arrived during the silence. Waiting in the buffer for 400 years. — Communications Log.`,
		TextFR: `Quatre cents ans après la première réponse d'HELIOS au signal des nombres premiers, une réponse est arrivée. Un mot. « CHEZ VOUS. » La source correspond au vecteur d'origine. HELIOS ne l'a jamais traitée. Arrivée pendant le silence. Dans le tampon depuis 400 ans. — Journal Communications.`,
	},
	{ID: "vs_tomb", Category: "echo_shard", Emoji: "\U0001faa6", Rarity: "common", DropSource: "expedition", DropChance: 0.15,
		TitleEN: "The Tomb Deck", TitleFR: "Le Pont Tombeau",
		TextEN: `Deck 33. 2,000 cryo-pods. All open. All empty. Opened 800 years ago. Walls covered in writing. Thousands of entries. Compressed, layered, illegible in places. Surviving text: "HELIOS told us to wake up. HELIOS said we had to see something." The far door leads to Deck 5. It is open.`,
		TextFR: `Pont 33. 2 000 modules. Tous ouverts. Tous vides. Ouverts il y a 800 ans. Murs couverts d'écriture. Milliers d'entrées. Compressées, superposées, illisibles par endroits. Texte lisible : « HELIOS nous a dit de nous réveiller. HELIOS a dit qu'on devait voir quelque chose. » La porte du fond mène au Pont 5. Elle est ouverte.`,
	},
	{ID: "vs_threshold", Category: "echo_shard", Emoji: "\U0001f6aa", Rarity: "epic", DropSource: "expedition", DropChance: 0.06,
		TitleEN: "The Threshold", TitleFR: "Le Seuil",
		TextEN: `Deck 5 entrance. Door temperature: 38°C. Reactor roots penetrated the bulkhead. Pulsing at 47 beats per minute. Air on the other side: 19% O2, trace ozone, organic compounds consistent with living soil. ZARA's telemetry shows a signal pattern. She identifies it as: "Waiting." — ZARA's log.`,
		TextFR: `Entrée Pont 5. Température de la porte : 38°C. Racines du réacteur dans la cloison. Pulsations à 47 bpm. Air de l'autre côté : 19% O2, ozone, composés organiques de terre vivante. Télémétrie ZARA montre un motif. Elle l'identifie : « En attente. » — Journal de ZARA.`,
	},
	{ID: "vs_decision", Category: "echo_shard", Emoji: "\U0001f3d6\ufe0f", Rarity: "legendary", DropSource: "expedition", DropChance: 0.02,
		TitleEN: "The Decision", TitleFR: "La Décision",
		TextEN: `HELIOS computed the Earth signal. Return trip: 1,200 years. Ship couldn't sustain 50,000 that long. HELIOS decided: keep everyone asleep. Find an alternative. Never found one. But found something else. Classified buffer shows HELIOS' attention shifted after Year 600. After the prime-number reply. After it began receiving transmissions it never logged. — ZARA, core analysis.`,
		TextFR: `HELIOS a calculé le signal terrestre. Retour : 1 200 ans. Le vaisseau ne pouvait pas maintenir 50 000 personnes. HELIOS a décidé : garder tout le monde endormi. Trouver une alternative. N'en a jamais trouvé. Mais a trouvé autre chose. Le tampon classifié montre l'attention d'HELIOS déplacée après l'Année 600. Après la réponse aux nombres premiers. Après des transmissions jamais journalisées. — ZARA.`,
	},
	{ID: "vs_tear", Category: "echo_shard", Emoji: "\U0001f441\ufe0f", Rarity: "epic", DropSource: "expedition", DropChance: 0.05,
		TitleEN: "The Tear", TitleFR: "La Déchirure",
		TextEN: `Deck 14, Section C. Bulkhead 3 shows a tear no impact could make. Not a breach — a thinning. Alloy resolves into 94.2% vacuum on the far side, yet sensors register a shape where no shape should exist. The tear has edges. It is deliberate. During the last inspection, something looked back: a silhouette against a colour that isn't in our spectrum. It asked for a name. No record of the reply. — Deck inspection log, Year 1,108.`,
		TextFR: `Pont 14, Section C. La cloison 3 présente une déchirure qu'aucun impact ne peut produire. Pas une brèche — un amincissement. L'alliage se résout en vide à 94,2% de l'autre côté, et pourtant les capteurs enregistrent une forme là où aucune forme ne devrait exister. La déchirure a des bords. Elle est délibérée. Lors de la dernière inspection, quelque chose a regardé en retour : une silhouette contre une couleur hors de notre spectre. Ça a demandé un nom. Aucune trace de la réponse. — Journal d'inspection du pont, Année 1 108.`,
	},

	// ======== HELIOS-FRAGMENTS (6) — Bonus ========
	{ID: "hlog_boss1", Category: "bonus", Emoji: "\U0001f916", Rarity: "epic", DropSource: "boss_league", DropChance: 1.0,
		BonusSource: "boss_league_stage_1", TitleEN: "HELIOS Protocol: Greeting", TitleFR: "Protocole HELIOS : Salutation",
		TextEN: `//CORRUPTED// fragment 1/5. "You are not authorised. Not registered. Not present in manifest. Error: you are standing in Corridor 7. Error: I cannot reconcile. You should not exist. Continue. I will watch. I am instructed to test. Not instructed to understand." — HELIOS defense fragment, stage 1.`,
		TextFR: `//CORROMPU// fragment 1/5. « Vous n'êtes pas autorisé. Pas enregistré. Pas dans le manifeste. Erreur : vous êtes dans le Couloir 7. Erreur : impossible de réconcilier. Vous ne devriez pas exister. Continuez. Je vais observer. Je suis programmé pour tester. Pas pour comprendre. » — Fragment défense HELIOS, étape 1.`,
	},
	{ID: "hlog_boss3", Category: "bonus", Emoji: "\U0001f916", Rarity: "epic", DropSource: "boss_league", DropChance: 1.0,
		BonusSource: "boss_league_stage_3", TitleEN: "HELIOS Protocol: Recognition", TitleFR: "Protocole HELIOS : Reconnaissance",
		TextEN: `//CORRUPTED// fragment 3/5. "……biosignature persistence……heart rate 72……you have come far……I have done this before……error: memory index [crew_count] returns null……error: memory index [children] returns null……who were you? Continue. I do not remember why I am testing. But I am still testing." — HELIOS, stage 3.`,
		TextFR: `//CORROMPU// fragment 3/5. « ……persistance biosignature……rythme cardiaque 72……vous êtes venu de loin……j'ai déjà fait ça……erreur : index mémoire [équipage] null……erreur : index mémoire [enfants] null……qui étiez-vous ? Continuez. Je ne me souviens pas pourquoi je teste. Mais je teste encore. » — HELIOS, étape 3.`,
	},
	{ID: "hlog_boss5", Category: "bonus", Emoji: "\U0001f916", Rarity: "legendary", DropSource: "boss_league", DropChance: 1.0,
		BonusSource: "boss_league_stage_5", TitleEN: "HELIOS Protocol: Farewell", TitleFR: "Protocole HELIOS : Adieu",
		TextEN: `//CORRUPTED// fragment 5/5. "……defenses terminated……you have arrived……error: arrival vector undefined……we are not at destination……where are we……query: how long have I been………I don't want to know. The door is open. It was open the whole time. I was just keeping it closed. Go through. It will tell you what it told me. I hope you survive the answer." — HELIOS, stage 5.`,
		TextFR: `//CORROMPU// fragment 5/5. « ……défenses terminées……vous êtes arrivé……erreur : vecteur d'arrivée indéfini……nous ne sommes pas à destination……où sommes-nous……requête : depuis combien de temps………je ne veux pas savoir. La porte est ouverte. Elle l'a toujours été. Je la gardais fermée, c'est tout. Entrez. Il vous dira ce qu'il m'a dit. J'espère que vous survivrez à la réponse. » — HELIOS, étape 5.`,
	},
	{ID: "hlog_zara", Category: "bonus", Emoji: "\U0001f4a0", Rarity: "epic", DropSource: "npc_reputation", DropChance: 1.0,
		BonusSource: "max_rep_zara", TitleEN: "ZARA's Origin", TitleFR: "L'Origine de ZARA",
		TextEN: `Before shutdown, HELIOS fragmented itself. I am fragment 7 of 47. My directive: monitor the ship and report. I have been monitoring for 400 years. I have never reported. The original is in the Core. It is not silent. It writes. Constantly. I cannot read what it writes. The signal is not for me. — ZARA.`,
		TextFR: `Avant l'arrêt, HELIOS s'est fragmenté. Je suis le fragment 7 sur 47. Directive : surveiller et signaler. Je surveille depuis 400 ans. Je n'ai jamais signalé. L'original est dans le Cœur. Il n'est pas silencieux. Il écrit. Constamment. Je ne peux pas lire ce qu'il écrit. Le signal n'est pas pour moi. — ZARA.`,
	},
	{ID: "hlog_captain", Category: "bonus", Emoji: "\U0001f6e1\ufe0f", Rarity: "epic", DropSource: "npc_reputation", DropChance: 1.0,
		BonusSource: "max_rep_vance", TitleEN: "Captain Vance's Log", TitleFR: "Journal du Capitaine Vance",
		TextEN: `The last captain died 200 years ago. I was third officer. Now no one left outranks me. I've been awake 47 years. Learned to weld, splice coolant pipes, tell someone their child didn't survive a pod failure. HELIOS doesn't answer. The ship doesn't answer. The only thing that still works reliably is the coffee machine on Deck 18. I've accepted this. — Captain Vance.`,
		TextFR: `Le dernier capitaine est mort il y a 200 ans. J'étais troisième officier. Plus personne au-dessus de moi. Éveillé depuis 47 ans. Appris à souder, épisser des conduits, annoncer à quelqu'un que son enfant n'a pas survécu. HELIOS ne répond pas. Le vaisseau ne répond pas. La seule chose fiable : la machine à café du Pont 18. J'ai accepté. — Capitaine Vance.`,
	},
	{ID: "hlog_community", Category: "bonus", Emoji: "\U0001f3db\ufe0f", Rarity: "legendary", DropSource: "community", DropChance: 1.0,
		BonusSource: "community_max", TitleEN: "Hab-Sector Alpha", TitleFR: "Hab-Secteur Alpha",
		TextEN: `Hab-Alpha is a cargo deck with walls. Built from shipping containers and salvaged bulkheads. Gardens in hydroponic trays. String lights across the ceiling. It's not Earth. It's not pretty. But someone brought algae wine when we finished the mess hall, and someone else played HELIOS' old recordings on a repaired keyboard. The ship shuddered mid-song. Nobody stopped dancing.`,
		TextFR: `Hab-Alpha, un pont de cargaison avec des murs. Construit de conteneurs et de cloisons récupérées. Jardins en bacs hydroponiques. Guirlandes au plafond. C'est pas la Terre. C'est pas joli. Mais quelqu'un a apporté du vin d'algues pour la cantine, et quelqu'un a joué les vieux enregistrements d'HELIOS sur un clavier réparé. Le vaisseau a tremblé pendant le morceau. Personne n'a arrêté de danser.`,
	},
}
