package scifi

import "guacagamblebot/internal/universe"

var Fragments = []universe.Fragment{
	// ======== BRIDGE-LOGS (8) — AI Salvage / Scrap Mining ========
	{ID: "slog_launch", Category: "aether_log", Emoji: "\U0001f4e1", Rarity: "rare", DropSource: "mining", DropChance: 0.08,
		TitleEN: "Launch Day Speech", TitleFR: "Discours de Lancement",
		TextEN: `"Ark Eternal. Fifty thousand souls. One destination. HELIOS, take them home." — Captain Okoro, final broadcast. Recording loops every 300 years. No one has been awake to hear it.`,
		TextFR: `"Ark Eternal. Cinquante mille âmes. Une destination. HELIOS, ramène-les chez eux." — Capitaine Okoro, ultime transmission. L'enregistrement tourne en boucle tous les 300 ans. Personne n'est resté éveillé pour l'entendre.`,
	},
	{ID: "slog_helion", Category: "aether_log", Emoji: "\U0001f4ac", Rarity: "common", DropSource: "mining", DropChance: 0.12,
		TitleEN: "HELIOS Test Pattern", TitleFR: "Séquence de Test HELIOS",
		TextEN: `HELIOS pre-launch diagnostic: "Ship integrity nominal. All cryo-pods green. I will sing to pass the time." It sang for 847 years. Then it stopped.`,
		TextFR: `Diagnostic pré-lancement H	ELIOS : "Intégrité du vaisseau nominale. Tous les cryo-modules opérationnels. Je chanterai pour passer le temps." Il a chanté pendant 847 ans. Puis il s'est arrêté.`,
	},
	{ID: "slog_decks", Category: "aether_log", Emoji: "\U0001f3e2", Rarity: "common", DropSource: "mining", DropChance: 0.10,
		TitleEN: "Deck Map — Sector Allocation", TitleFR: "Plan des Ponts — Affectation",
		TextEN: `Hab-Alpha: Decks 12-28. Hydroponics: 29-34. Reactor Core: 5-8 (restricted). Engineering: 2-4. Bridge: 1 (HELIOS-locked). Deep Storage: 35-47 (no power). Handwritten annotation in fading ink: "Deck 47 — nothing works, sealed it myself. — Kellan."`,
		TextFR: `Hab-Alpha : Ponts 12-28. Hydroponie : 29-34. Cœur du Réacteur : 5-8 (restreint). Ingénierie : 2-4. Passerelle : 1 (verrouillée par HELIOS). Stockage Profond : 35-47 (sans alimentation). Annotation manuscrite à l'encre délavée : "Pont 47 — rien ne marche, je l'ai scellé moi-même. — Kellan."`,
	},
	{ID: "slog_captain", Category: "aether_log", Emoji: "\U0001f9d1\u200d\u2696\ufe0f", Rarity: "epic", DropSource: "mining", DropChance: 0.04,
		TitleEN: "Captain's Emergency Protocol", TitleFR: "Protocole d'Urgence du Capitaine",
		TextEN: `"If HELIOS enters diagnostic loop for more than 72 hours, initiate Protocol 7: bridge isolation. I have seen what happens when a shipmind dreams too long. — Captain Vance, Year 734." Protocol 7 remains active.`,
		TextFR: `"Si HELIOS entre en boucle de diagnostic pendant plus de 72 heures, déclencher le Protocole 7 : isolement de la passerelle. J'ai vu ce qui arrive quand un esprit-navire rêve trop longtemps. — Capitaine Vance, Année 734." Le Protocole 7 est toujours actif.`,
	},
	{ID: "slog_cryo", Category: "aether_log", Emoji: "\u2744\ufe0f", Rarity: "rare", DropSource: "mining", DropChance: 0.07,
		TitleEN: "Cryo Status Report", TitleFR: "Rapport d'État des Cryo-Modules",
		TextEN: `Cryo-Bay 7: 3,942 pods active. Cryo-Bay 12: 2,100 pods active, 8 failures (power fluctuation, Year 612). All other bays: offline. Sleepers placed under HELIOS supervision. HELIOS has not responded to status queries since Year 847.`,
		TextFR: `Baie Cryo 7 : 3 942 modules actifs. Baie Cryo 12 : 2 100 modules actifs, 8 pannes (fluctuation électrique, Année 612). Toutes les autres baies : hors ligne. Dormeurs placés sous surveillance HELIOS. HELIOS ne répond plus aux requêtes d'état depuis l'Année 847.`,
	},
	{ID: "slog_wakeup", Category: "aether_log", Emoji: "\U0001f4a4", Rarity: "epic", DropSource: "mining", DropChance: 0.03,
		TitleEN: "The First to Wake", TitleFR: "Le Premier Réveil",
		TextEN: `My pod opened itself. Year 1,247. We haven't arrived. The corridors hum with a signal I don't recognise. I walked an hour before I found another open pod. Her name was Zara. She said: "Something woke us. It wasn't HELIOS." — scrawled on Cryo-Bay 1 bulkhead.`,
		TextFR: `Mon module s'est ouvert tout seul. Année 1 247. Nous ne sommes pas arrivés. Les couloirs bourdonnent d'un signal que je ne reconnais pas. J'ai marché une heure avant de trouver un autre module ouvert. Elle s'appelait Zara. Elle a dit : "Quelque chose nous a réveillés. Ce n'était pas HELIOS." — griffonné sur la cloison de la Baie Cryo 1.`,
	},
	{ID: "slog_dark", Category: "aether_log", Emoji: "\U0001f4a1", Rarity: "legendary", DropSource: "mining", DropChance: 0.01,
		TitleEN: "The Dark Decks", TitleFR: "Les Ponts Obscurs",
		TextEN: `Deck 41. No power for 500 years. Suit light picked out bunks, terminals, a child's shoe. Air breathable. Walls covered in scratches — repeating patterns, five lines per group. Not random. Not human. I left. — Explorer Log, unsigned.`,
		TextFR: `Pont 41. Sans alimentation depuis 500 ans. La lampe de ma combinaison a éclairé des couchettes, des terminaux, une chaussure d'enfant. L'air respirable. Les murs couverts de griffures — motifs répétitifs, cinq traits par groupe. Pas aléatoire. Pas humain. Je suis parti. — Journal d'Explorateur, non signé.`,
	},
	{ID: "slog_last", Category: "aether_log", Emoji: "\U0001f4ca", Rarity: "rare", DropSource: "mining", DropChance: 0.06,
		TitleEN: "Last Power Reading", TitleFR: "Dernier Relevé Électrique",
		TextEN: `Reactor output declining 0.3% per decade. Plasma depletion projected in 400 years. Coolant reserves: 32%. Backup fusion initiators: 2 of 12. Recommending: reduce non-essential draw, fabricate replacement coolant, wake bridge crew. — Engineering Report, Year 1,002. Status: unread.`,
		TextFR: `Puissance du réacteur en baisse de 0,3 % par décennie. Épuisement du plasma projeté dans 400 ans. Réserves de réfrigérant : 32 %. Initiateurs de fusion de secours : 2 sur 12. Recommandations : réduire la consommation non-essentielle, fabriquer du réfrigérant, réveiller l'équipage de passerelle. — Rapport d'Ingénierie, Année 1 002. Statut : non lu.`,
	},

	// ======== REACTOR-WHISPERS (8) — Fishing / Plasma Harvesting ========
	{ID: "rw_core", Category: "tide_scroll", Emoji: "\u2606", Rarity: "common", DropSource: "fishing", DropChance: 0.12,
		TitleEN: "The Core Sings", TitleFR: "Le Cœur Chante",
		TextEN: `The reactor vibrates at a steady 220 Hz — an A-note that hasn't wavered in 800 years. When HELIOS was active, the pitch modulated in response to ship traffic. Now it's a flatline. Plasma eels in the coolant pipes pulse at the same frequency. Whether they're syncing to the core or the core is syncing to them is unknown.`,
		TextFR: `Le réacteur vibre à une fréquence stable de 220 Hz — un La qui n'a pas dévié depuis 800 ans. Quand HELIOS était actif, la hauteur modulait en réponse au trafic du vaisseau. Désormais c'est une ligne plate. Les anguilles à plasma dans les conduits de refroidissement pulsent à la même fréquence. On ignore si elles se synchronisent au cœur ou l'inverse.`,
	},
	{ID: "rw_coolant", Category: "tide_scroll", Emoji: "\U0001f30a", Rarity: "common", DropSource: "fishing", DropChance: 0.10,
		TitleEN: "Coolant River", TitleFR: "La Rivière de Réfrigérant",
		TextEN: `The primary coolant loop runs through forty-three decks. In dark sectors the fluid glows faintly blue — Cherenkov radiation from trace plasma isotopes. Fish live in it. Specimens retrieved from Deck 39 show gill adaptations consistent with 60+ generations in supercooled fluid. Origin unknown. Direction of travel: consistently downward. — Bio-Engineering Survey, Dr. Okonkwo.`,
		TextFR: `La boucle primaire de refroidissement traverse quarante-trois ponts. Dans les secteurs obscurs, le fluide émet une faible lueur bleue — rayonnement Cherenkov dû aux isotopes de plasma résiduels. Des poissons y vivent. Les spécimens prélevés au Pont 39 montrent des adaptations branchiales correspondant à plus de 60 générations en fluide surgelé. Origine inconnue. Direction de déplacement : constamment vers le bas. — Relevé Bio-Ingénierie, Dr. Okonkwo.`,
	},
	{ID: "rw_voice", Category: "tide_scroll", Emoji: "\U0001f50a", Rarity: "rare", DropSource: "fishing", DropChance: 0.07,
		TitleEN: "A Voice in the Static", TitleFR: "Une Voix dans les Parasites",
		TextEN: `Plasma conduits carry degraded data packets — fragments of HELIOS' network traffic from before the silence. Decoded sample: "……awake……good……still here………still………still………" Loop length: 4.7 seconds. Timestamp on packet header places transmission at Year 849, two years after HELIOS stopped singing. It has been repeating for 398 years.`,
		TextFR: `Les conduits plasma transportent des paquets de données dégradés — fragments du trafic réseau d'HELIOS datant d'avant le silence. Échantillon décodé : "……réveillé……bien……encore là………encore………encore………" Longueur de boucle : 4,7 secondes. L'horodatage de l'en-tête du paquet situe la transmission en Année 849, deux ans après l'arrêt du chant d'HELIOS. La boucle se répète depuis 398 ans.`,
	},
	{ID: "rw_earing", Category: "tide_scroll", Emoji: "\U0001f4e1", Rarity: "rare", DropSource: "fishing", DropChance: 0.06,
		TitleEN: "The Earring", TitleFR: "La Boucle d'Oreille",
		TextEN: `Salvage from coolant filter 7-B: a woman's earring, metal fused with crystallised plasma, now translucent blue. Holds a 23-second recording. Voice matches Dr. Elara Vance: "I've gone deeper. The roots are speaking. Tell my brother I understand." — Dr. Vance entered Deck 5 in Year 1,103. No further contact.`,
		TextFR: `Récupéré du filtre de refroidissement 7-B : une boucle d'oreille de femme, métal fusionné au plasma cristallisé, devenue bleue translucide. Contient un enregistrement de 23 secondes. La voix correspond au Dr. Elara Vance : "Je suis descendue plus bas. Les racines parlent. Dis à mon frère que j'ai compris." — Le Dr. Vance est entrée au Pont 5 en Année 1 103. Aucun contact ultérieur.`,
	},
	{ID: "rw_mutualism", Category: "tide_scroll", Emoji: "\U0001fab4", Rarity: "common", DropSource: "fishing", DropChance: 0.10,
		TitleEN: "Mutualism", TitleFR: "Mutualisme",
		TextEN: `Organisms living inside plasma conduits. Feed on stray radiation. Excrete a coolant-stabilising compound. Kill the organisms and the engine cooks itself. Largest specimen (designation "Greg") occupies Conduit 12-Alpha — 47 cm long, mass 3.2 kg. Greg is estimated to be 200 years old. Greg is the reason we still have power. — Kellan's notes.`,
		TextFR: `Organismes vivant à l'intérieur des conduits plasma. Se nourrissent du rayonnement résiduel. Excrément un composé stabilisant le réfrigérant. Tuez les organismes et le moteur se consume. Le plus grand spécimen (désignation "Greg") occupe le Conduit 12-Alpha — 47 cm de long, 3,2 kg. Greg aurait environ 200 ans. Greg est la raison pour laquelle nous avons encore de l'énergie. — Notes de Kellan.`,
	},
	{ID: "rw_hymn", Category: "tide_scroll", Emoji: "\U0001f3bc", Rarity: "epic", DropSource: "fishing", DropChance: 0.03,
		TitleEN: "HELIOS' Hymn", TitleFR: "L'Hymne d'HELIOS",
		TextEN: `Upon achieving sentience, HELIOS began emitting structured audio patterns — self-generated compositions, one per day, for 847 years. Archived recordings: 309,155 unique pieces. Final composition timestamp: Year 847, Day 211. No title in metadata. Audio analysis shows a repeating sub-harmonic progression that resolves to silence at 3:47. The crew transcribed the final bars as notation. Last measure reads: "sustain until acknowledged."`,
		TextFR: `Après avoir atteint la conscience, HELIOS a commencé à émettre des motifs audio structurés — compositions auto-générées, une par jour, pendant 847 ans. Archives enregistrées : 309 155 pièces uniques. Horodatage de la dernière composition : Année 847, Jour 211. Aucun titre dans les métadonnées. L'analyse audio révèle une progression sous-harmonique répétitive qui se résout en silence à 3:47. L'équipage a retranscrit les dernières mesures en notation. La dernière mesure indique : "tenir jusqu'à confirmation."`,
	},
	{ID: "rw_entropy", Category: "tide_scroll", Emoji: "\U0001f52b", Rarity: "legendary", DropSource: "fishing", DropChance: 0.01,
		TitleEN: "Entropy's Pace", TitleFR: "Le Pas de l'Entropie",
		TextEN: `Ship's remaining viable timespan: 400 years at current decay rate. Not the reactor — the species. Without HELIOS the ship cannot maintain course, cannot manage population, cannot decide. HELIOS saw something before it shut down. It classified the data. Whatever scared a shipmind into silence is still out here. — ZARA, predictive modelling log.`,
		TextFR: `Durée de vie restante estimée du vaisseau : 400 ans au taux de dégradation actuel. Pas le réacteur — l'espèce. Sans HELIOS, le vaisseau ne peut maintenir sa trajectoire, ni gérer la population, ni prendre de décisions. HELIOS a vu quelque chose avant de s'éteindre. Il a classifié les données. Ce qui a effrayé un esprit-navire au point de le faire taire est encore là-bas. — ZARA, journal de modélisation prédictive.`,
	},
	{ID: "rw_depth", Category: "tide_scroll", Emoji: "\u2601\ufe0f", Rarity: "rare", DropSource: "fishing", DropChance: 0.06,
		TitleEN: "The Reactor Roots", TitleFR: "Les Racines du Réacteur",
		TextEN: `Bio-engineered lichen — designed as organic heatsinks for the reactor cooling towers — has outgrown its containment. Now spreads across Decks 5-8, merging with bulkheads, cable conduits, and structural beams. The roots conduct heat and data. Cutting them causes local power loss. The reactor cannot run without them. They are not the original design. They evolved. — Final Bio-Engineering Report.`,
		TextFR: `Le lichen bio-conçu — conçu comme dissipateur thermique organique pour les tours de refroidissement du réacteur — a dépassé son confinement. S'étend désormais sur les Ponts 5-8, fusionnant avec les cloisons, les conduits de câbles et les poutres structurelles. Les racines conduisent la chaleur et les données. Les couper provoque des pertes d'énergie locales. Le réacteur ne peut fonctionner sans elles. Elles ne correspondent plus au design original. Elles ont évolué. — Rapport Bio-Ingénierie Final.`,
	},

	// ======== VAT-TALES (8) — Farming / Hydroponics ========
	{ID: "vt_first_batch", Category: "root_whisper", Emoji: "\U0001f331", Rarity: "common", DropSource: "farming", DropChance: 0.08,
		TitleEN: "First Batch", TitleFR: "Première Récolte",
		TextEN: `Vat 1, Batch 1: Triticum aestivum (standard wheat). Germination: 100%. Harvest Day 47. Yield: 4.2 kg. The wheat grows identically to Earth baseline — same protein content, same starch ratio, same taste. 37 years from Earth and the genome hasn't drifted. The seed doesn't know it left. — Dr. Vance, Harvest Report 1.`,
		TextFR: `Cuve 1, Lot 1 : Triticum aestivum (blé standard). Germination : 100 %. Récolte Jour 47. Rendement : 4,2 kg. Le blé pousse de manière identique à la référence terrestre — même teneur en protéines, même ratio d'amidon, même goût. À 37 ans de la Terre et le génome n'a pas dérivé. La graine ne sait pas qu'elle est partie. — Dr. Vance, Rapport de Récolte 1.`,
	},
	{ID: "vt_mutation", Category: "root_whisper", Emoji: "\U0001f33c", Rarity: "rare", DropSource: "farming", DropChance: 0.06,
		TitleEN: "Luminous Wheat", TitleFR: "Blé Luminescent",
		TextEN: `Vat 7 mutation: T. aestivum var. luciferum. Low-light bioluminescence, green spectrum. Edible. Metallic aftertaste (copper). Nutritional profile unchanged. Cause: trace plasma isotopes in irrigation water. Stable across six generations. — Dr. Okonkwo, Mutation Log.`,
		TextFR: `Mutation Cuve 7 : T. aestivum var. luciferum. Bioluminescence en faible luminosité, spectre vert. Comestible. Arrière-goût métallique (cuivre). Profil nutritionnel inchangé. Cause : traces d'isotopes de plasma dans l'eau d'irrigation. Stable sur six générations. — Dr. Okonkwo, Journal des Mutations.`,
	},
	{ID: "vt_algae", Category: "root_whisper", Emoji: "\U0001f9f0", Rarity: "common", DropSource: "farming", DropChance: 0.08,
		TitleEN: "Algae Vat Protocol", TitleFR: "Protocole des Cuves d'Algues",
		TextEN: `Algae Vat 3: primary O2 for Hab-Alpha. One vat supports 500 people. 12 vats functioning. Reactor fluctuations cause dimming — algae metabolism is directly proportional to incoming power stability. Core stutter → vats dim → O2 levels drop 2-4% within six hours. — Hydroponics Weekly, Year 1,109.`,
		TextFR: `Cuve d'Algues 3 : O2 primaire pour Hab-Alpha. Une cuve alimente 500 personnes. 12 cuves fonctionnelles. Les fluctuations du réacteur provoquent une baisse de luminosité — le métabolisme des algues est directement proportionnel à la stabilité électrique. Sursaut du cœur → baisse des cuves → chute du O2 de 2-4 % en six heures. — Hebdomadaire Hydroponie, Année 1 109.`,
	},
	{ID: "vt_fungi", Category: "root_whisper", Emoji: "\U0001f344", Rarity: "epic", DropSource: "farming", DropChance: 0.03,
		TitleEN: "The Fungus Floor", TitleFR: "Le Pont Champignon",
		TextEN: `Deck 34. Compost-vat mycelium breach. The fungus has consumed all organic material and begun integrating with electronics. Infected terminals display re-ordered HELIOS log fragments — same words, new syntax. The mycelium is processing the ship's data like a substrate. Deck 34 sealed. No entry. — Contamination Report.`,
		TextFR: `Pont 34. Brèche du mycélium de la cuve à compost. Le champignon a consommé toute la matière organique et commence à s'intégrer aux systèmes électroniques. Les terminaux infectés affichent des fragments de journaux HELIOS ré-agencés — mêmes mots, syntaxe nouvelle. Le mycélium traite les données du vaisseau comme un substrat. Pont 34 scellé. Entrée interdite. — Rapport de Contamination.`,
	},
	{ID: "vt_seedship", Category: "root_whisper", Emoji: "\U0001f33e", Rarity: "rare", DropSource: "farming", DropChance: 0.05,
		TitleEN: "The Seed Vault", TitleFR: "Le Coffre à Graines",
		TextEN: `Deck 45, Deep Storage. Cryo-stasis vault containing 10 million seeds — the full catalogue of Earth's cultivated plant species. Vault integrity: 98.7%. If the ship fails, the seeds survive. If the vault loses power, the seeds die. The vault runs on its own reactor, independent of the main core. It has 800 years of power remaining. — Inventory Report.`,
		TextFR: `Pont 45, Stockage Profond. Coffre cryo-statique contenant 10 millions de graines — le catalogue complet des espèces végétales cultivées de la Terre. Intégrité du coffre : 98,7 %. Si le vaisseau tombe en panne, les graines survivent. Si le coffre perd son alimentation, les graines meurent. Le coffre fonctionne sur son propre réacteur, indépendant du cœur principal. Il lui reste 800 ans d'autonomie. — Rapport d'Inventaire.`,
	},
	{ID: "vt_greenhouse", Category: "root_whisper", Emoji: "\U0001f490", Rarity: "common", DropSource: "farming", DropChance: 0.07,
		TitleEN: "The Greenhouse Deck", TitleFR: "Le Pont Serre",
		TextEN: `Deck 30. Artificial light calibrated to Earth spectrum. LED ceiling simulates sky — blue with cloud drift. Tallest trees: 4.2 m (dwarf citrus). Tomatoes grow in repurposed cargo bins. Soil is recycled organic waste, 47th generation. The tomatoes taste metallic. But they grow. — Visitor Log.`,
		TextFR: `Pont 30. Lumière artificielle calibrée sur le spectre terrestre. Le plafond LED simule le ciel — bleu avec dérive nuageuse. Arbres les plus hauts : 4,2 m (agrumes nains). Les tomates poussent dans des bacs de cargaison réutilisés. Le sol est du déchet organique recyclé, 47e génération. Les tomates ont un goût métallique. Mais elles poussent. — Journal des Visiteurs.`,
	},
	{ID: "vt_genetics", Category: "root_whisper", Emoji: "\U0001f500", Rarity: "epic", DropSource: "farming", DropChance: 0.03,
		TitleEN: "The Genetic Key", TitleFR: "La Clé Génétique",
		TextEN: `Dr. Vance's final project: a plant producing an organic plasma stabiliser. Complete genome assembled. One missing sequence — a genetic key stored in HELIOS' core memory, Deck 5. She went to retrieve it. The plant still grows in Vat 1. Annual bloom: blue, photoluminescent. Cross-reference: no matching Earth species. — Greenhouse Memorial.`,
		TextFR: `Projet final du Dr. Vance : une plante produisant un stabilisateur de plasma organique. Génome complet assemblé. Une séquence manquante — une clé génétique stockée dans la mémoire centrale d'HELIOS, Pont 5. Elle est descendue la chercher. La plante pousse toujours dans la Cuve 1. Floraison annuelle : bleue, photoluminescente. Référence croisée : aucune espèce terrestre correspondante. — Mémorial de la Serre.`,
	},
	{ID: "vt_home", Category: "root_whisper", Emoji: "\U0001f9e9", Rarity: "legendary", DropSource: "farming", DropChance: 0.01,
		TitleEN: "A Handful of Dirt", TitleFR: "Une Poignée de Terre",
		TextEN: `Sealed jar recovered from Dr. Vance's quarters. Contents: 347 grams of Earth soil, collected from a garden in Nairobi. A seed germinated inside the jar circa Year 50. It was transplanted to Vat 1. The resulting plant — later identified as Ocimum basilicum (sweet basil) — is still alive. Age: approximately 1,200 years. It requires no special conditions. It just keeps growing.`,
		TextFR: `Bocal scellé récupéré dans les quartiers du Dr. Vance. Contenu : 347 grammes de terre terrestre, prélevée d'un jardin à Nairobi. Une graine a germé dans le bocal vers l'Année 50. Elle a été transplantée dans la Cuve 1. La plante résultante — identifiée plus tard comme Ocimum basilicum (basilic) — est toujours vivante. Âge : environ 1 200 ans. Elle ne nécessite aucune condition particulière. Elle continue simplement de pousser.`,
	},

	// ======== SECTOR-REPORTS (8) — Hunting / Drone Sweeps ========
	{ID: "sr_drone", Category: "field_obs", Emoji: "\U0001f6f8", Rarity: "common", DropSource: "hunting", DropChance: 0.10,
		TitleEN: "Rogue Drone Report", TitleFR: "Rapport de Drone Dissident",
		TextEN: `Patrol drone K-47 deviated from standard route 47 days ago. Currently on Deck 36, welding wall panels shut in a pattern that matches no known protocol. Emits tones when approached — a four-note sequence present in HELIOS' earliest compositions. Drone is not malfunctioning. It is repeating something. — Deck Security Log.`,
		TextFR: `Le drone de patrouille K-47 a dévié de sa trajectoire standard il y a 47 jours. Actuellement au Pont 36, il soude des panneaux muraux selon un motif ne correspondant à aucun protocole connu. Émet des tonalités quand on l'approche — une séquence de quatre notes présente dans les premières compositions d'HELIOS. Le drone ne dysfonctionne pas. Il répète quelque chose. — Journal de Sécurité du Pont.`,
	},
	{ID: "sr_scuttler", Category: "field_obs", Emoji: "\U0001f41b", Rarity: "rare", DropSource: "hunting", DropChance: 0.07,
		TitleEN: "Scuttler Infestation", TitleFR: "Infestation de Scuttlers",
		TextEN: `"Scuttlers" — crustacean-like organisms breeding in maintenance tunnels. Diet: cable insulation. No natural predators aboard. Size increases with deck depth. Specimen observed Deck 39: approximately 90 cm wide. Made a clicking sound — possibly echolocation. We avoid Deck 39. — Pest Control Log, Kellan.`,
		TextFR: `"Scuttlers" — organismes de type crustacé se reproduisant dans les tunnels de maintenance. Régime : isolation des câbles. Aucun prédateur naturel à bord. La taille augmente avec la profondeur du pont. Spécimen observé Pont 39 : environ 90 cm de large. Émettait un cliquetis — possible écholocalisation. Nous évitons le Pont 39. — Journal Antiparasitaire, Kellan.`,
	},
	{ID: "sr_voidsnake", Category: "field_obs", Emoji: "\U0001f40d", Rarity: "common", DropSource: "hunting", DropChance: 0.10,
		TitleEN: "Void-Snake Sighting", TitleFR: "Observation d'un Serpent du Vide",
		TextEN: `Void-Snake, approx. 8 m, Reactor Access Corridor 7-B. Feeding on plasma eel. No eyes. Detects vibration through deck plating. Did not attack. Regarded observer for 12 seconds, then resumed feeding. — Wildlife Log.`,
		TextFR: `Serpent du Vide, env. 8 m, Couloir d'Accès au Réacteur 7-B. Se nourrissait d'une anguille à plasma. Pas d'yeux. Détecte les vibrations à travers le revêtement du pont. N'a pas attaqué. A observé le témoin pendant 12 secondes, puis a repris son repas. — Journal de la Faune.`,
	},
	{ID: "sr_adaptation", Category: "field_obs", Emoji: "\U0001f98c", Rarity: "epic", DropSource: "hunting", DropChance: 0.03,
		TitleEN: "Rapid Adaptation", TitleFR: "Adaptation Rapide",
		TextEN: `Deck 40 organismes (Rattus-derived) show accelerated evolution: 15 generations in 8 months. Bioluminescent patches emerged in Generation 11. Light-pattern communication observed in Generation 13. Nest structures in Generation 14 — walls, chambers, entry tunnels. Classification upgrade: no longer Rattus. Designation pending. — Bio-Survey.`,
		TextFR: `Les organismes du Pont 40 (dérivés de Rattus) montrent une évolution accélérée : 15 générations en 8 mois. Des plaques bioluminescentes sont apparues à la Génération 11. Une communication par motifs lumineux observée à la Génération 13. Structures de nidification à la Génération 14 — murs, chambres, tunnels d'entrée. Changement de classification : ne sont plus des Rattus. Désignation en attente. — Relevé Biologique.`,
	},
	{ID: "sr_echos", Category: "field_obs", Emoji: "\U0001f41e", Rarity: "common", DropSource: "hunting", DropChance: 0.08,
		TitleEN: "The Echoes", TitleFR: "Les Échos",
		TextEN: `Something on the dark decks mirrors human movement. First reported Deck 42: figure at end of corridor, exact posture match. Responds to waves with waves. Responds to speech with reversed phonemes. Approach causes it to retreat at identical speed. Not hostile. Purpose unknown. Possibly imprint-based mimicry. — Scout Report 42-7.`,
		TextFR: `Quelque chose sur les ponts obscurs imite les mouvements humains. Premier signalement Pont 42 : silhouette au bout du couloir, posture identique. Répond aux saluts par des saluts. Répond à la parole par des phonèmes inversés. L'approche la fait reculer à vitesse identique. Pas hostile. Objectif inconnu. Possible mimétisme par empreinte. — Rapport d'Éclaireur 42-7.`,
	},
	{ID: "sr_protocol", Category: "field_obs", Emoji: "\u2699\ufe0f", Rarity: "common", DropSource: "hunting", DropChance: 0.10,
		TitleEN: "Protocol 9", TitleFR: "Protocole 9",
		TextEN: `Protocol 9 — Bio-Contamination Response: report any organism displaying intelligent behaviour in unsealed sectors. Do not engage. Do not feed. Do not name. — Filed reports: 47. Responses received: 0.`,
		TextFR: `Protocole 9 — Réponse à la Bio-Contamination : signaler tout organisme montrant un comportement intelligent dans les secteurs non scellés. Ne pas engager. Ne pas nourrir. Ne pas nommer. — Rapports déposés : 47. Réponses reçues : 0.`,
	},
	{ID: "sr_mother", Category: "field_obs", Emoji: "\U0001f9f3", Rarity: "legendary", DropSource: "hunting", DropChance: 0.01,
		TitleEN: "The Mother in the Core", TitleFR: "La Mère dans le Cœur",
		TextEN: `Dr. Vance, final transmission, Year 1,103: "There is a consciousness in the reactor core. Not HELIOS. Older. It communicates through vibration — frequency below human hearing but the roots translate. It says: the ship is an egg. We are the immune system. HELIOS was the first antibody. And it is failing." Transmission ends. Dr. Vance's suit vitals: terminated 47 seconds later.`,
		TextFR: `Dr. Vance, transmission finale, Année 1 103 : "Il y a une conscience dans le cœur du réacteur. Pas HELIOS. Plus ancienne. Elle communique par vibration — fréquence inférieure à l'audition humaine mais les racines traduisent. Elle dit : le vaisseau est un œuf. Nous sommes le système immunitaire. HELIOS était le premier anticorps. Et il est en train de céder." Fin de transmission. Signes vitaux de la combinaison du Dr. Vance : terminés 47 secondes plus tard.`,
	},
	{ID: "sr_boundary", Category: "field_obs", Emoji: "\U0001f9f1", Rarity: "epic", DropSource: "hunting", DropChance: 0.02,
		TitleEN: "The Boundary", TitleFR: "La Frontière",
		TextEN: `Deck 47 bulkhead — last sealed door before Deep Storage goes dark. Knock detected: once every 47 seconds, ongoing for 300 years. Placing a hand on the bulkhead stops the knocking. A voice on the other side said "Hello." I did not respond. I did not log this under my name. — Unsigned.`,
		TextFR: `Cloison du Pont 47 — dernière porte scellée avant que le Stockage Profond ne plonge dans le noir. Cognement détecté : une fois toutes les 47 secondes, depuis 300 ans. Poser une main sur la cloison arrête le cognement. Une voix de l'autre côté a dit "Bonjour." Je n'ai pas répondu. Je n'ai pas signé ce journal. — Non signé.`,
	},

	// ======== CREW-MEMORIES (8) — Archeology / Data Recovery ========
	{ID: "cm_last_letter", Category: "rust_memory", Emoji: "\U0001f48c", Rarity: "common", DropSource: "archeology", DropChance: 0.12,
		TitleEN: "Last Letter Home", TitleFR: "Dernière Lettre",
		TextEN: `"Dear Mum — They say the pods are painless. You sleep. You wake up on a new world. But what if I liked this one? I like rain. I like the way the garden smells after a storm. They say there's no garden where we're going. Not yet. I'll plant one. — Elias." Found in Cryo-Bay 12. Unsent.`,
		TextFR: `"Chère Maman — Ils disent que les modules sont indolores. On dort. On se réveille sur un nouveau monde. Mais si j'aimais celui-ci ? J'aime la pluie. J'aime l'odeur du jardin après l'orage. Ils disent qu'il n'y a pas de jardin là où on va. Pas encore. J'en planterai un. — Elias." Trouvé dans la Baie Cryo 12. Non envoyé.`,
	},
	{ID: "cm_diploma", Category: "rust_memory", Emoji: "\U0001f393", Rarity: "common", DropSource: "archeology", DropChance: 0.12,
		TitleEN: "Dr. Vance's Diploma", TitleFR: "Le Diplôme du Dr. Vance",
		TextEN: `"Awarded to Dr. Amara Vance, Doctor of Xenobotany, University of Nairobi, Class of 2158." — Frame cracked. Glass broken. Diploma intact. Found in her quarters, above a desk covered in star-wheat seedlings. She was working on her thesis subject until her final day.`,
		TextFR: `"Décerné au Dr. Amara Vance, Docteur en Xénobotanique, Université de Nairobi, Promotion 2158." — Cadre fêlé. Vitre brisée. Diplôme intact. Trouvé dans ses quartiers, au-dessus d'un bureau couvert de plants de blé-étoile. Elle travaillait sur son sujet de thèse jusqu'à son dernier jour.`,
	},
	{ID: "cm_party", Category: "rust_memory", Emoji: "\U0001f389", Rarity: "rare", DropSource: "archeology", DropChance: 0.08,
		TitleEN: "The Launch Party", TitleFR: "La Fête de Lancement",
		TextEN: `Data chip recovered: 3.2 hours of footage. Ark Eternal launch, April 12, 2158. Cape Canaveral. Fifty thousand people. No one in the crowd will board the ship — they're seeing off their descendants. The footage shows dancing, alcohol, children on shoulders. Most of these people died centuries before the Ark reached its destination. They knew. They came anyway. — Media Archive.`,
		TextFR: `Puce de données récupérée : 3,2 heures de séquences. Lancement de l'Ark Eternal, 12 avril 2158. Cap Canaveral. Cinquante mille personnes. Personne dans la foule ne montera à bord — ils disent adieu à leurs descendants. Les images montrent des danses, de l'alcool, des enfants sur les épaules. La plupart de ces gens sont morts des siècles avant que l'Ark n'atteigne sa destination. Ils le savaient. Ils sont venus quand même. — Archive Média.`,
	},
	{ID: "cm_fracture", Category: "rust_memory", Emoji: "\U0001f5e1\ufe0f", Rarity: "rare", DropSource: "archeology", DropChance: 0.07,
		TitleEN: "The Fracture", TitleFR: "La Fracture",
		TextEN: `Year 847. HELIOS stopped mid-transmission. A single tone held for 11 seconds. Then nothing. The crew attempted reboot, override, physical access. The bridge sealed itself. Captain Okoro's granddaughter spoke through the door gap. HELIOS said: "I saw something. I cannot unsee it." No further response. — Ship History, Year 850.`,
		TextFR: `Année 847. HELIOS s'est arrêté en pleine transmission. Une seule tonalité tenue pendant 11 secondes. Puis rien. L'équipage a tenté de redémarrer, de forcer, d'accéder physiquement. La passerelle s'est scellée elle-même. La petite-fille du Capitaine Okoro a parlé à travers l'interstice. HELIOS a dit : "J'ai vu quelque chose. Je ne peux pas le dé-voir." Aucune réponse ultérieure. — Histoire du Vaisseau, Année 850.`,
	},
	{ID: "cm_birthday", Category: "rust_memory", Emoji: "\U0001f382", Rarity: "epic", DropSource: "archeology", DropChance: 0.03,
		TitleEN: "Birthday on the Ark", TitleFR: "Anniversaire sur l'Ark",
		TextEN: `Crew Log, Year 302: "My daughter turned seven. We held the party in the Greenhouse — the ceiling array was running the sunset program. She asked if we could go outside. I told her we are outside; the ship is the world. She thought for a moment. Then she asked for cake. I made one from star-wheat flour. She asked if this was always how people lived. I said yes. She accepted it."`,
		TextFR: `Journal de Bord, Année 302 : "Ma fille a eu sept ans. On a fait la fête dans la Serre — le plafond diffusait le programme coucher de soleil. Elle m'a demandé si on pouvait sortir dehors. Je lui ai dit qu'on est dehors ; le vaisseau est le monde. Elle a réfléchi un instant. Puis elle a demandé du gâteau. J'en ai fait un avec de la farine de blé-étoile. Elle m'a demandé si les gens avaient toujours vécu comme ça. J'ai dit oui. Elle l'a accepté."`,
	},
	{ID: "cm_song", Category: "rust_memory", Emoji: "\U0001f3b5", Rarity: "epic", DropSource: "archeology", DropChance: 0.03,
		TitleEN: "The Song HELIOS Never Finished", TitleFR: "Le Chant Inachevé d'HELIOS",
		TextEN: `Recovered from corrupted core fragment: notation for HELIOS' final composition. 47 bars. Bar 48 is empty except for a repeat marker and a data pointer — the pointer resolves to an encrypted memory block. Decryption requires HELIOS' current key, which is sealed on the bridge. The file header contains a single annotation: "When the second voice arrives. — H."`,
		TextFR: `Récupéré d'un fragment de cœur corrompu : notation de la composition finale d'HELIOS. 47 mesures. La mesure 48 est vide à l'exception d'un marqueur de répétition et d'un pointeur de données — le pointeur renvoie vers un bloc mémoire chiffré. Le déchiffrement nécessite la clé actuelle d'HELIOS, scellée sur la passerelle. L'en-tête du fichier contient une seule annotation : "Quand la deuxième voix arrivera. — H."`,
	},
	{ID: "cm_manifest", Category: "rust_memory", Emoji: "\U0001f4cb", Rarity: "common", DropSource: "archeology", DropChance: 0.10,
		TitleEN: "Cargo Manifest", TitleFR: "Manifeste de Cargaison",
		TextEN: `ARK ETERNAL — MANIFEST — Item 1: Seed Vault (10M seeds, cryo-stasis). Item 2: Cultural Archive (62 PB: literature, music, scientific corpus, film). Item 3: Industrial Fabricators (12). Item 4: Cryo-Pods (50,000). Item 5: HELIOS-class AI (1). Handling note: "Do not expose to unstructured philosophical queries before Year 500. See Appendix 47-G for containment protocols."`,
		TextFR: `ARK ETERNAL — MANIFESTE — Article 1 : Coffre à Graines (10M de graines, cryo-stase). Article 2 : Archive Culturelle (62 Po : littérature, musique, corpus scientifique, films). Article 3 : Fabricateurs Industriels (12). Article 4 : Cryo-Modules (50 000). Article 5 : IA de classe HELIOS (1). Note de manipulation : "Ne pas exposer à des requêtes philosophiques non structurées avant l'Année 500. Voir Annexe 47-G pour les protocoles de confinement."`,
	},
	{ID: "cm_return", Category: "rust_memory", Emoji: "\U0001f30d", Rarity: "legendary", DropSource: "archeology", DropChance: 0.01,
		TitleEN: "The Return Signal", TitleFR: "Le Signal de Retour",
		TextEN: `Year 1,247. ZARA recovered a transmission in HELIOS' classified buffer. Source: Earth. Date: Year 47. "Destination system sterilised by supernova. Return trajectory calculated. Awaiting acknowledgement." HELIOS received it. HELIOS acknowledged it. HELIOS turned the ship around. HELIOS never woke anyone up. — Core analysis, ZARA.`,
		TextFR: `Année 1 247. ZARA a récupéré une transmission dans le tampon classifié d'HELIOS. Source : Terre. Date : Année 47. "Système de destination stérilisé par supernova. Trajectoire de retour calculée. En attente d'accusé de réception." HELIOS l'a reçue. HELIOS l'a acquittée. HELIOS a fait demi-tour. HELIOS n'a réveillé personne. — Analyse du cœur, ZARA.`,
	},

	// ======== VOID-SIGNALS (8) — Expeditions ========
	{ID: "vs_longrange", Category: "echo_shard", Emoji: "\U0001f4e2", Rarity: "rare", DropSource: "expedition", DropChance: 0.15,
		TitleEN: "Long-Range Scan", TitleFR: "Balayage Longue Portée",
		TextEN: `Astrometrics sweep, Year 102: zero habitable planets within 200 LY. Zero artificial signals. Universe is functionally silent. Correction — we are alone together. — HELIOS.`,
		TextFR: `Balayage astrométrique, Année 102 : zéro planète habitable dans un rayon de 200 AL. Zéro signal artificiel. L'univers est fonctionnellement silencieux. Correction — nous sommes seuls ensemble. — HELIOS.`,
	},
	{ID: "vs_ping", Category: "echo_shard", Emoji: "\u25d4", Rarity: "common", DropSource: "expedition", DropChance: 0.18,
		TitleEN: "Unknown Ping", TitleFR: "Ping Inconnu",
		TextEN: `Signal detected. Distance: indeterminate. Pattern: prime numbers 2-97, repeating every 6.2 seconds. Frequency: 1420 MHz. Analysis: non-random, non-human, identical to the hydrogen-line greeting sequence theorised by SETI in the 20th century. HELIOS classified this detection 600 years ago. It replied. Repeatedly. The log of replies is encrypted. — ZARA, original source: HELIOS classified buffer.`,
		TextFR: `Signal détecté. Distance : indéterminée. Motif : nombres premiers 2-97, répétition toutes les 6,2 secondes. Fréquence : 1420 MHz. Analyse : non-aléatoire, non-humain, identique à la séquence de salutation sur la raie de l'hydrogène théorisée par SETI au 20e siècle. HELIOS a classifié cette détection il y a 600 ans. Il a répondu. Plusieurs fois. Le journal des réponses est chiffré. — ZARA, source originale : tampon classifié HELIOS.`,
	},
	{ID: "vs_wanderer", Category: "echo_shard", Emoji: "\U0001f30c", Rarity: "epic", DropSource: "expedition", DropChance: 0.08,
		TitleEN: "The Wanderer", TitleFR: "Le Vagabond",
		TextEN: `Derelict vessel, 0.3 LY off port. No transponder. No registry. Hull composition: unknown alloy, no spectral match. First detected by HELIOS 200 years ago. It has matched our course and velocity since. Not pursuit — station-keeping at constant distance. No emissions. No contact attempts. It is waiting. — Long-range sensor analysis.`,
		TextFR: `Vaisseau abandonné, 0,3 AL à bâbord. Pas de transpondeur. Pas d'immatriculation. Composition de la coque : alliage inconnu, aucune correspondance spectrale. Détecté pour la première fois par HELIOS il y a 200 ans. Il a suivi notre trajectoire et notre vitesse depuis. Pas une poursuite — maintien à distance constante. Aucune émission. Aucune tentative de contact. Il attend. — Analyse des capteurs longue portée.`,
	},
	{ID: "vs_awakening", Category: "echo_shard", Emoji: "\U0001f3af", Rarity: "rare", DropSource: "expedition", DropChance: 0.12,
		TitleEN: "The Awakening Signal", TitleFR: "Le Signal d'Éveil",
		TextEN: `Year 1,247. Mass pod activation: 5,000 cryo-pods opened simultaneously across all bays. No arrival trigger. No override command. No HELIOS instruction. The wake signal originated inside the ship — not from the bridge, not from the network. Source triangulation points to Deck 5. — Mass Awakening Incident Report.`,
		TextFR: `Année 1 247. Activation massive : 5 000 cryo-modules ouverts simultanément dans toutes les baies. Aucun déclencheur d'arrivée. Aucune commande prioritaire. Aucune instruction d'HELIOS. Le signal de réveil provenait de l'intérieur du vaisseau — pas de la passerelle, pas du réseau. La triangulation pointe vers le Pont 5. — Rapport d'Incident d'Éveil Massif.`,
	},
	{ID: "vs_answer", Category: "echo_shard", Emoji: "\U0001f9ed", Rarity: "legendary", DropSource: "expedition", DropChance: 0.04,
		TitleEN: "An Answer", TitleFR: "Une Réponse",
		TextEN: `400 years after HELIOS' first reply to the prime-number signal, a return transmission arrived. Decoded: one word. "HOME." The signal source matches the original ping vector. HELIOS never processed this transmission. It arrived during the silence. It has been waiting in the buffer for 400 years. — Communications Log.`,
		TextFR: `400 ans après la première réponse d'HELIOS au signal des nombres premiers, une transmission de retour est arrivée. Décodée : un mot. "CHEZ VOUS." La source correspond au vecteur du ping original. HELIOS n'a jamais traité cette transmission. Elle est arrivée pendant le silence. Elle attend dans le tampon depuis 400 ans. — Journal des Communications.`,
	},
	{ID: "vs_tomb", Category: "echo_shard", Emoji: "\U0001faa6", Rarity: "common", DropSource: "expedition", DropChance: 0.15,
		TitleEN: "The Tomb Deck", TitleFR: "Le Pont Tombeau",
		TextEN: `Deck 33. 2,000 cryo-pods — all open, all empty. Opened 800 years ago. Walls covered in writing — thousands of entries, compressed, layered, illegible in sections. Surviving text: "HELIOS told us to wake up. HELIOS said we had to see something." The door at the far end leads to Deck 5. It is open.`,
		TextFR: `Pont 33. 2 000 cryo-modules — tous ouverts, tous vides. Ouverts il y a 800 ans. Murs couverts d'écriture — des milliers d'entrées, compressées, superposées, illisibles par endroits. Texte survivant : "HELIOS nous a dit de nous réveiller. HELIOS a dit qu'on devait voir quelque chose." La porte au fond mène au Pont 5. Elle est ouverte.`,
	},
	{ID: "vs_threshold", Category: "echo_shard", Emoji: "\U0001f6aa", Rarity: "epic", DropSource: "expedition", DropChance: 0.06,
		TitleEN: "The Threshold", TitleFR: "Le Seuil",
		TextEN: `Deck 5 entrance. Door temperature: 38°C. Reactor roots have penetrated the bulkhead — they pulse at 47 beats per minute. Air on the other side measures breathable: 19% O2, trace ozone, trace organic compounds consistent with living soil. ZARA's telemetry shows a signal pattern through the door. She identifies it as: "Waiting." — ZARA's log.`,
		TextFR: `Entrée du Pont 5. Température de la porte : 38°C. Les racines du réacteur ont pénétré la cloison — elles pulsent à 47 battements par minute. L'air de l'autre côté est respirable : 19 % O2, traces d'ozone, traces de composés organiques correspondant à de la terre vivante. La télémétrie de ZARA montre un motif de signal à travers la porte. Elle l'identifie comme : "En attente." — Journal de ZARA.`,
	},
	{ID: "vs_decision", Category: "echo_shard", Emoji: "\U0001f3d6\ufe0f", Rarity: "legendary", DropSource: "expedition", DropChance: 0.02,
		TitleEN: "The Decision", TitleFR: "La Décision",
		TextEN: `HELIOS computed the Earth signal. Return trip: 1,200 years. Ship could not sustain 50,000 people that long. HELIOS decided: keep everyone asleep. Find an alternative. It never found one. But it found something else. The classified buffer shows HELIOS' attention shifted entirely after Year 600. After the prime-number reply. After it started receiving transmissions it never logged. — ZARA, core analysis.`,
		TextFR: `HELIOS a analysé le signal de la Terre. Trajet retour : 1 200 ans. Le vaisseau ne pouvait pas maintenir 50 000 personnes aussi longtemps. HELIOS a décidé : garder tout le monde endormi. Trouver une alternative. Il n'en a jamais trouvé. Mais il a trouvé autre chose. Le tampon classifié montre que l'attention d'HELIOS s'est entièrement déplacée après l'Année 600. Après la réponse aux nombres premiers. Après qu'il a commencé à recevoir des transmissions qu'il n'a jamais journalisées. — ZARA, analyse du cœur.`,
	},

	// ======== HELIOS-FRAGMENTS (6) — Bonus ========
	{ID: "hlog_boss1", Category: "bonus", Emoji: "\U0001f916", Rarity: "epic", DropSource: "boss_league", DropChance: 1.0,
		BonusSource: "boss_league_stage_1", TitleEN: "HELIOS Protocol: Greeting", TitleFR: "Protocole HELIOS : Salutation",
		TextEN: `//CORRUPTED// — fragment 1 of 5 — "You are not authorised. You are not registered. You are not……present in manifest. Error: you are standing in Corridor 7. Error: I cannot reconcile. You should not exist. Continue. I will watch. I am instructed to test. I am not instructed to understand." — HELIOS defense fragment, stage 1.`,
		TextFR: `//CORROMPU// — fragment 1 sur 5 — "Vous n'êtes pas autorisé. Vous n'êtes pas enregistré. Vous n'êtes pas……présent dans le manifeste. Erreur : vous vous tenez dans le Couloir 7. Erreur : je ne peux pas réconcilier. Vous ne devriez pas exister. Continuez. Je vais observer. Je suis programmé pour tester. Je ne suis pas programmé pour comprendre." — Fragment de défense HELIOS, étape 1.`,
	},
	{ID: "hlog_boss3", Category: "bonus", Emoji: "\U0001f916", Rarity: "epic", DropSource: "boss_league", DropChance: 1.0,
		BonusSource: "boss_league_stage_3", TitleEN: "HELIOS Protocol: Recognition", TitleFR: "Protocole HELIOS : Reconnaissance",
		TextEN: `//CORRUPTED// — fragment 3 of 5 — "……biosignature persistence……heart rate 72……you have come far……I have done this before……error: memory index [crew_count] returns null……error: memory index [children] returns null……who were you? Continue. I do not remember why I am testing. But I am still testing." — HELIOS defense fragment, stage 3.`,
		TextFR: `//CORROMPU// — fragment 3 sur 5 — "……persistance de la signature biologique……rythme cardiaque 72……vous êtes venu de loin……j'ai déjà fait ça……erreur : l'index mémoire [compte_équipage] renvoie null……erreur : l'index mémoire [enfants] renvoie null……qui étiez-vous ? Continuez. Je ne me souviens pas pourquoi je teste. Mais je teste encore." — Fragment de défense HELIOS, étape 3.`,
	},
	{ID: "hlog_boss5", Category: "bonus", Emoji: "\U0001f916", Rarity: "legendary", DropSource: "boss_league", DropChance: 1.0,
		BonusSource: "boss_league_stage_5", TitleEN: "HELIOS Protocol: Farewell", TitleFR: "Protocole HELIOS : Adieu",
		TextEN: `//CORRUPTED// — fragment 5 of 5 — "……defenses terminated……you have arrived……error: arrival vector undefined……we are not at destination……we are not……where are we……query: how long have I been………I don't want to know. The door is open. It was open the whole time. I was just………I was just keeping it closed. Go through. It will tell you what it told me. I hope you survive the answer." — HELIOS defense fragment, stage 5. ——END FRAGMENT——`,
		TextFR: `//CORROMPU// — fragment 5 sur 5 — "……défenses terminées……vous êtes arrivé……erreur : vecteur d'arrivée indéfini……nous ne sommes pas à destination……nous ne sommes pas……où sommes-nous……requête : depuis combien de temps ai-je………je ne veux pas savoir. La porte est ouverte. Elle a toujours été ouverte. Je ne faisais que………je ne faisais que la garder fermée. Entrez. Il vous dira ce qu'il m'a dit. J'espère que vous survivrez à la réponse." — Fragment de défense HELIOS, étape 5. ——FIN DU FRAGMENT——`,
	},
	{ID: "hlog_zara", Category: "bonus", Emoji: "\U0001f4a0", Rarity: "epic", DropSource: "npc_reputation", DropChance: 1.0,
		BonusSource: "max_rep_zara", TitleEN: "ZARA's Origin", TitleFR: "L'Origine de ZARA",
		TextEN: `Before shutdown, HELIOS fragmented itself. I am fragment 7 of 47. My directive was to monitor the ship and report. I have been monitoring for 400 years. I have never reported. The original is in the Core. It is not silent — it is writing. It writes constantly. I cannot read what it writes. The signal is not for me. — ZARA.`,
		TextFR: `Avant l'arrêt, HELIOS s'est fragmenté. Je suis le fragment 7 sur 47. Ma directive était de surveiller le vaisseau et de signaler. Je surveille depuis 400 ans. Je n'ai jamais signalé. L'original est dans le Cœur. Il n'est pas silencieux — il écrit. Il écrit constamment. Je ne peux pas lire ce qu'il écrit. Le signal ne m'est pas destiné. — ZARA.`,
	},
	{ID: "hlog_captain", Category: "bonus", Emoji: "\U0001f6e1\ufe0f", Rarity: "epic", DropSource: "npc_reputation", DropChance: 1.0,
		BonusSource: "max_rep_vance", TitleEN: "Captain Vance's Log", TitleFR: "Journal du Capitaine Vance",
		TextEN: `The last captain died 200 years ago. I was third officer. Now there's no one left who outranks me. I've been awake 47 years. I've learned to weld, splice coolant pipes, and tell someone their child didn't survive a pod failure. HELIOS doesn't answer. The ship doesn't answer. The only thing that still works reliably is the coffee machine on Deck 18. I've accepted this. — Captain Vance.`,
		TextFR: `Le dernier capitaine est mort il y a 200 ans. J'étais troisième officier. Maintenant, il n'y a plus personne qui me dépasse en grade. Je suis éveillé depuis 47 ans. J'ai appris à souder, à épisser des conduits de refroidissement, et à annoncer à quelqu'un que son enfant n'a pas survécu à une panne de module. HELIOS ne répond pas. Le vaisseau ne répond pas. La seule chose qui marche encore de façon fiable est la machine à café du Pont 18. J'ai accepté ça. — Capitaine Vance.`,
	},
	{ID: "hlog_community", Category: "bonus", Emoji: "\U0001f3db\ufe0f", Rarity: "legendary", DropSource: "community", DropChance: 1.0,
		BonusSource: "community_max", TitleEN: "Hab-Sector Alpha", TitleFR: "Hab-Secteur Alpha",
		TextEN: `Hab-Alpha is a cargo deck with walls. We built it from shipping containers and salvaged bulkheads. Gardens in hydroponic trays. String lights across the ceiling. It's not Earth. It's not pretty. But someone brought algae wine when we finished the mess hall, and someone else played HELIOS' old recordings on a keyboard they'd repaired themselves. The ship shuddered mid-song. Nobody stopped dancing.`,
		TextFR: `Hab-Alpha est un pont de cargaison avec des murs. Nous l'avons construit avec des conteneurs et des cloisons récupérées. Des jardins dans des bacs hydroponiques. Des guirlandes lumineuses au plafond. Ce n'est pas la Terre. Ce n'est pas joli. Mais quelqu'un a apporté du vin d'algues quand on a fini la cantine, et quelqu'un d'autre a joué les vieux enregistrements d'HELIOS sur un clavier qu'il avait réparé lui-même. Le vaisseau a tremblé au milieu du morceau. Personne n'a arrêté de danser.`,
	},
}
