package archeology

var Sites = map[string]*SiteDef{
	"riverbed": {
		Key:      "riverbed",
		NameID:   "site_riverbed_name",
		DescID:   "site_riverbed_desc",
		Depth:    30,
		Cost:     0,
		MinLevel: 0,
		FossilRarities: []string{"common", "rare"},
		Color:    0x2ECC71,
		LayerSeqs: [][]LayerType{
			{LayerSoftSoil, LayerGravel, LayerClay},
			{LayerGravel, LayerSoftSoil, LayerClay},
			{LayerClay, LayerGravel, LayerSoftSoil},
		},
	},
	"cliffside": {
		Key:      "cliffside",
		NameID:   "site_cliffside_name",
		DescID:   "site_cliffside_desc",
		Depth:    50,
		Cost:     0,
		MinLevel: 0,
		FossilRarities: []string{"common", "rare", "epic"},
		Color:    0xE67E22,
		LayerSeqs: [][]LayerType{
			{LayerHardRock, LayerGravel, LayerSoftSoil, LayerHardRock},
			{LayerGravel, LayerHardRock, LayerClay, LayerHardRock},
			{LayerSoftSoil, LayerHardRock, LayerGravel, LayerBedrock},
		},
	},
	"fault": {
		Key:      "fault",
		NameID:   "site_fault_name",
		DescID:   "site_fault_desc",
		Depth:    50,
		Cost:     200,
		MinLevel: 0,
		FossilRarities: []string{"rare", "epic", "legendary"},
		Color:    0xE74C3C,
		LayerSeqs: [][]LayerType{
			{LayerHardRock, LayerBedrock, LayerGravel, LayerBedrock},
			{LayerGravel, LayerHardRock, LayerBedrock, LayerHardRock},
			{LayerBedrock, LayerHardRock, LayerGravel, LayerBedrock},
		},
	},
	"ice_sheet": {
		Key:      "ice_sheet",
		NameID:   "site_ice_sheet_name",
		DescID:   "site_ice_sheet_desc",
		Depth:    40,
		Cost:     50,
		MinLevel: 3,
		FossilRarities: []string{"rare", "epic", "pure_dna"},
		Color:    0x00BFFF,
		LayerSeqs: [][]LayerType{
			{LayerClay, LayerSoftSoil, LayerGravel, LayerHardRock},
			{LayerSoftSoil, LayerClay, LayerHardRock, LayerBedrock},
			{LayerGravel, LayerClay, LayerSoftSoil, LayerBedrock},
		},
	},
	"volcanic": {
		Key:      "volcanic",
		NameID:   "site_volcanic_name",
		DescID:   "site_volcanic_desc",
		Depth:    70,
		Cost:     100,
		MinLevel: 5,
		FossilRarities: []string{"epic", "legendary", "pure_dna"},
		Color:    0x8B0000,
		LayerSeqs: [][]LayerType{
			{LayerBedrock, LayerHardRock, LayerBedrock, LayerHardRock},
			{LayerHardRock, LayerBedrock, LayerGravel, LayerBedrock},
			{LayerBedrock, LayerGravel, LayerBedrock, LayerHardRock},
		},
	},
}
